// @generated by pop_lifter — DO NOT EDIT.
// POP source segment `BOOT` (7 routines),
// lifted to free functions over the shared `Cpu`.

use crate::cpu::Cpu;
use crate::sym;

pub fn entry(cpu: &mut Cpu) {
    cpu.mem[sym::entry] = 0x60;
    cpu.set_a(0xff);
    cpu.mem[0x04fb] = cpu.reg.a;
    cpu.mem[0x03f3] = cpu.reg.a;
    cpu.mem[0x03f4] = cpu.reg.a;
    cpu.mem[0xc000] = cpu.reg.a;
    cpu.mem[0xc002] = cpu.reg.a;
    cpu.mem[0xc004] = cpu.reg.a;
    cpu.mem[0xc00c] = cpu.reg.a;
    cpu.mem[0xc00e] = cpu.reg.a;
    cpu.mem[0xc081] = cpu.reg.a;
    crate::unpack::TEXT(cpu);
    crate::ext::home(cpu);
    crate::ext::normal(cpu);
    crate::ext::pr0(cpu);
    crate::ext::in0(cpu);
    cpu.set_x(cpu.mem[sym::SLOT]);
    cpu.set_a(cpu.reg.x);
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shr(1));
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shr(1));
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shr(1));
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shr(1));
    cpu.set_a(cpu.reg.a | 0xc0);
    cpu.local.insert((":rdsect", 2), cpu.reg.a);
    cpu.set_a(0x0f);
    cpu.mem[sym::sector] = cpu.reg.a;
    loop {
        cpu.set_y(cpu.mem[sym::sector]);
        cpu.mem[0x003d] = cpu.mem[(sym::skewtbl + cpu.reg.y as usize) & 0xffff];
        cpu.set_a(cpu.mem[(sym::sectaddr + cpu.reg.y as usize) & 0xffff]);
        if cpu.reg.a == 0x00 {
        } else {
            cpu.mem[0x0027] = cpu.reg.a;
            crate::ext::_24005c(cpu);
        }
        let _v = cpu.mem[sym::sector].wrapping_sub(1);
        cpu.mem[sym::sector] = _v;
        cpu.set_nz(_v);
        if cpu.flags.z {
            break;
        }
    }
    cpu.set_a(cpu.mem[sym::SLOT]);
    crate::ext::_24900(cpu);
    return;
}

pub fn stage2(cpu: &mut Cpu) {
    cpu.mem[sym::slot] = cpu.reg.x;
    check128k(cpu);
    moverw18(cpu);
    cpu.set_a(0x00);
    cpu.mem[sym::lastrack] = cpu.reg.a;
    cpu.mem[0x03f3] = cpu.reg.a;
    cpu.mem[0x03f4] = cpu.reg.a;
    crate::ext::rw18(cpu);
    crate::ext::rw18(cpu);
    crate::ext::rw18(cpu);
    crate::ext::rw18(cpu);
    crate::ext::_24ee00(cpu);
    return;
}

pub fn CHECKER(cpu: &mut Cpu) {
    'b3: {
        cpu.set_a(0xee);
        cpu.mem[0xc005] = cpu.reg.a;
        cpu.mem[0xc003] = cpu.reg.a;
        cpu.mem[0x0800] = cpu.reg.a;
        cpu.set_a(cpu.mem[0x0c00]);
        if cpu.reg.a == 0xee {
            cpu.flags.c = (cpu.mem[0x0c00] >> 7) != 0;
            cpu.mem[0x0c00] = cpu.mem[0x0c00].wrapping_shl(1);
            cpu.set_nz(cpu.mem[0x0c00]);
            cpu.set_a(cpu.mem[0x0800]);
            if cpu.reg.a == cpu.mem[0x0c00] {
                break 'b3;
            }
        }
    }
    cpu.mem[0xc004] = cpu.reg.a;
    cpu.mem[0xc002] = cpu.reg.a;
    return;
}

pub fn check128k(cpu: &mut Cpu) {
    cpu.mem[0xc081] = cpu.reg.a;
    cpu.set_a(cpu.mem[0xfbb3]);
    let _o: u8 = 0x06;
    cpu.flags.c = cpu.reg.a >= _o;
    cpu.flags.z = cpu.reg.a == _o;
    cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
    if cpu.reg.a != 0x06 {
        NOT128K(cpu);
        return;
    }
    let _o: u8 = cpu.mem[0xc017];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    if cpu.flags.n {
        NOT128K(cpu);
        return;
    }
    cpu.reg.x = 0x25;
    loop {
        cpu.set_a(cpu.mem[(sym::CHECKER + cpu.reg.x as usize) & 0xffff]);
        cpu.mem[(0x0180 + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    crate::ext::_24180(cpu);
    if cpu.flags.c {
        NOT128K(cpu);
        return;
    }
    return;
}

pub fn NOT128K(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_x(cpu.mem[sym::SLOT]);
                cpu.set_a(cpu.mem[(0xc088 + cpu.reg.x as usize) & 0xffff]);
                crate::unpack::TEXT(cpu);
                crate::ext::home(cpu);
                cpu.set_a(0x08);
                crate::ext::vtab(cpu);
                cpu.set_y(0x00);
                pc = 1;
            }
            1 => {
                cpu.set_a(cpu.mem[(sym::MEMTEXT + cpu.reg.y as usize) & 0xffff]);
                pc = 2;
            }
            2 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 3;
                }
            }
            3 => {
                crate::ext::cout(cpu);
                let _o: u8 = 0x8d;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != 0x8d {
                    pc = 5;
                } else {
                    pc = 4;
                }
            }
            4 => {
                cpu.set_a(0x04);
                cpu.mem[0x0024] = cpu.reg.a;
                pc = 5;
            }
            5 => {
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                if cpu.reg.y != 0x00 {
                    pc = 1;
                } else {
                    pc = 6;
                }
            }
            6 => {
                let _o: u8 = cpu.mem[0xc08b];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                let _o: u8 = cpu.mem[0xc08b];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                cpu.set_a(0xd0);
                cpu.set_x(0x30);
                cpu.set_y(0x40);
                pc = 7;
            }
            7 => {
                cpu.mem[sym::dest + 1] = cpu.reg.a;
                cpu.mem[sym::source + 1] = cpu.reg.x;
                cpu.mem[sym::endsourc + 1] = cpu.reg.y;
                cpu.set_y(0x00);
                cpu.mem[sym::dest] = cpu.reg.y;
                cpu.mem[sym::source] = cpu.reg.y;
                cpu.mem[sym::endsourc] = cpu.reg.y;
                pc = 8;
            }
            8 => {
                cpu.set_a(cpu.mem[((cpu.mem[sym::source] as usize | (cpu.mem[sym::source + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff]);
                cpu.mem[((cpu.mem[sym::dest] as usize | (cpu.mem[sym::dest + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                if cpu.reg.y != 0x00 {
                    pc = 8;
                } else {
                    pc = 9;
                }
            }
            9 => {
                let _v = cpu.mem[sym::source + 1].wrapping_add(1);
                cpu.mem[sym::source + 1] = _v;
                cpu.set_nz(_v);
                let _v = cpu.mem[sym::dest + 1].wrapping_add(1);
                cpu.mem[sym::dest + 1] = _v;
                cpu.set_nz(_v);
                cpu.set_a(cpu.mem[sym::source + 1]);
                let _o: u8 = cpu.mem[sym::endsourc + 1];
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != cpu.mem[sym::endsourc + 1] {
                    pc = 8;
                } else {
                    pc = 10;
                }
            }
            10 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn moverw18(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                let _o: u8 = cpu.mem[0xc08b];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                let _o: u8 = cpu.mem[0xc08b];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                cpu.set_a(0xd0);
                cpu.set_x(0x30);
                cpu.set_y(0x40);
                pc = 1;
            }
            1 => {
                cpu.mem[sym::dest + 1] = cpu.reg.a;
                cpu.mem[sym::source + 1] = cpu.reg.x;
                cpu.mem[sym::endsourc + 1] = cpu.reg.y;
                cpu.set_y(0x00);
                cpu.mem[sym::dest] = cpu.reg.y;
                cpu.mem[sym::source] = cpu.reg.y;
                cpu.mem[sym::endsourc] = cpu.reg.y;
                pc = 2;
            }
            2 => {
                cpu.set_a(cpu.mem[((cpu.mem[sym::source] as usize | (cpu.mem[sym::source + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff]);
                cpu.mem[((cpu.mem[sym::dest] as usize | (cpu.mem[sym::dest + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                if cpu.reg.y != 0x00 {
                    pc = 2;
                } else {
                    pc = 3;
                }
            }
            3 => {
                let _v = cpu.mem[sym::source + 1].wrapping_add(1);
                cpu.mem[sym::source + 1] = _v;
                cpu.set_nz(_v);
                let _v = cpu.mem[sym::dest + 1].wrapping_add(1);
                cpu.mem[sym::dest + 1] = _v;
                cpu.set_nz(_v);
                cpu.set_a(cpu.mem[sym::source + 1]);
                let _o: u8 = cpu.mem[sym::endsourc + 1];
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != cpu.mem[sym::endsourc + 1] {
                    pc = 2;
                } else {
                    pc = 4;
                }
            }
            4 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn movemem(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.mem[sym::dest + 1] = cpu.reg.a;
                cpu.mem[sym::source + 1] = cpu.reg.x;
                cpu.mem[sym::endsourc + 1] = cpu.reg.y;
                cpu.set_y(0x00);
                cpu.mem[sym::dest] = cpu.reg.y;
                cpu.mem[sym::source] = cpu.reg.y;
                cpu.mem[sym::endsourc] = cpu.reg.y;
                pc = 1;
            }
            1 => {
                cpu.set_a(cpu.mem[((cpu.mem[sym::source] as usize | (cpu.mem[sym::source + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff]);
                cpu.mem[((cpu.mem[sym::dest] as usize | (cpu.mem[sym::dest + 1] as usize) << 8) + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                if cpu.reg.y != 0x00 {
                    pc = 1;
                } else {
                    pc = 2;
                }
            }
            2 => {
                let _v = cpu.mem[sym::source + 1].wrapping_add(1);
                cpu.mem[sym::source + 1] = _v;
                cpu.set_nz(_v);
                let _v = cpu.mem[sym::dest + 1].wrapping_add(1);
                cpu.mem[sym::dest + 1] = _v;
                cpu.set_nz(_v);
                cpu.set_a(cpu.mem[sym::source + 1]);
                let _o: u8 = cpu.mem[sym::endsourc + 1];
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != cpu.mem[sym::endsourc + 1] {
                    pc = 1;
                } else {
                    pc = 3;
                }
            }
            3 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}
