// @generated by pop_lifter — DO NOT EDIT.
// Shared 6502 CPU state for the assembled crate (issue #47):
// registers, status flags (V untracked), 64 KiB memory, the
// pha/pla value stack, and recognised self-modifying-code operand
// variables. Every segment routine operates on a `&mut Cpu`.

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
    pub AMASK: u8,
    pub BMASK: u8,
    pub RAMRD1_lo: u8,
    pub RAMRD2_lo: u8,
    pub RAMRD_lo: u8,
    pub _90_hi: u8,
    pub _90_lo: u8,
    pub _91_hi: u8,
    pub _91_lo: u8,
    pub _92_hi: u8,
    pub _92_lo: u8,
    pub _93_hi: u8,
    pub _93_lo: u8,
    pub _94_hi: u8,
    pub _94_lo: u8,
    pub _96_hi: u8,
    pub _96_lo: u8,
    pub c1_hi: u8,
    pub c1_lo: u8,
    pub c2_hi: u8,
    pub c2_lo: u8,
    pub dst1_hi: u8,
    pub dst2_hi: u8,
    pub loop_hi: u8,
    pub org1_hi: u8,
    pub org2_hi: u8,
    pub s1_hi: u8,
    pub s1_lo: u8,
    pub sm: u8,
    pub sm1: u8,
    pub sm2: u8,
    pub smBASE_hi: u8,
    pub smBASE_lo: u8,
    pub smCOLOR: u8,
    pub smPAGE: u8,
    pub smSTART: u8,
    pub smTOP: u8,
    pub smWIDTH: u8,
    pub smXCO: u8,
    pub smodCD_lo: u8,
    pub smodSN_lo: u8,
    pub smod_hi: u8,
    pub smod_lo: u8,
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
    // Local-label / Merlin-variable byte store, keyed by symbolic
    // `(name, offset)`: StoreLocal writes, LoadLocal/CmpLocal read.
    pub local: std::collections::HashMap<(&'static str, u8), u8>,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
            local: std::collections::HashMap::new(),
        }
    }
}
