// @generated by pop_lifter — DO NOT EDIT.
// POP source segment `GAMEBG` (41 routines),
// lifted to free functions over the shared `Cpu`.

use crate::cpu::Cpu;
use crate::sym;

pub fn YELLOW(cpu: &mut Cpu) {
    cpu.reg.a = 0x80;
    cpu.mem[sym::yellowflag] = cpu.reg.a;
    return;
}

pub fn TIMELEFTMSG(cpu: &mut Cpu) {
    cpu.reg.a = 0x71;
    cpu.reg.x = 0x01;
    setupimage(cpu);
    cpu.reg.a = cpu.mem[sym::MinLeft];
    if cpu.reg.a < 0x02 {
        cpu.reg.a = cpu.mem[sym::KidAction];
        if cpu.reg.a != 0x03 {
            if cpu.reg.a != 0x04 {
                cpu.reg.a = cpu.mem[sym::KidBlockY];
                if cpu.reg.a == 0x01 {
                    cpu.reg.a = 0x99;
                    cpu.mem[sym::YCO] = cpu.reg.a;
                }
            }
        }
    }
    superim1(cpu);
    cpu.mem[sym::YCO] = (cpu.mem[sym::YCO]).wrapping_sub(0x05);
    cpu.reg.a = cpu.mem[sym::XCO];
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x01) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::XCO] = cpu.reg.a;
    cpu.mem[sym::OPACITY] = 0x00;
    cpu.reg.a = 0x01;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::getminleft(cpu);
    cpu.reg.a = cpu.mem[sym::MinLeft];
    if cpu.reg.a < 0x02 {
        cpu.reg.a = cpu.mem[sym::SecLeft];
    }
    cpu.mem[sym::temp] = cpu.reg.a;
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.reg.a = cpu.reg.a.wrapping_shr(1);
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.reg.a = cpu.reg.a.wrapping_shr(1);
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.reg.a = cpu.reg.a.wrapping_shr(1);
    cpu.flags.c = (cpu.reg.a & 1) != 0;
    cpu.reg.a = cpu.reg.a.wrapping_shr(1);
    if cpu.reg.a != 0x00 {
        cpu.reg.x = cpu.reg.a;
        cpu.reg.a = cpu.mem[sym::digit2 + cpu.reg.x as usize];
        cpu.mem[sym::IMAGE] = cpu.reg.a;
        crate::ext::addmsg(cpu);
    }
    cpu.reg.a = cpu.mem[sym::XCO];
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x01) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::XCO] = cpu.reg.a;
    cpu.reg.a = cpu.mem[sym::temp];
    cpu.reg.a &= 0x0f;
    cpu.reg.x = cpu.reg.a;
    cpu.reg.a = cpu.mem[sym::digit2 + cpu.reg.x as usize];
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    cpu.reg.a = cpu.mem[sym::MinLeft];
    if cpu.reg.a >= 0x02 {
        return;
    }
    cpu.reg.a = cpu.mem[sym::YCO];
    let tmp0 = cpu.reg.a;
    cpu.reg.a = 0x72;
    cpu.reg.x = 0x01;
    setupimage(cpu);
    cpu.reg.a = tmp0;
    cpu.mem[sym::YCO] = cpu.reg.a;
    cpu.reg.a = 0x02;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn PRINTLEVEL(cpu: &mut Cpu) {
    cpu.reg.a = 0x6e;
    cpu.reg.x = 0x01;
    superimage(cpu);
    cpu.reg.a = 0x6f;
    cpu.reg.x = 0x01;
    setupimage(cpu);
    getlevelno(cpu);
    if cpu.reg.x >= 0x0a {
        cpu.reg.a = 0x00;
        cpu.mem[sym::OFFSET] = cpu.reg.a;
    }
    cpu.reg.a = 0x01;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    cpu.reg.a = cpu.mem[sym::XCO];
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x06) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::XCO] = cpu.reg.a;
    getlevelno(cpu);
    cpu.reg.a = cpu.mem[sym::digit1 + cpu.reg.x as usize];
    if cpu.reg.a != 0x00 {
        cpu.mem[sym::IMAGE] = cpu.reg.a;
        cpu.reg.a = 0x01;
        cpu.mem[sym::OPACITY] = cpu.reg.a;
        crate::ext::addmsg(cpu);
        cpu.reg.a = cpu.mem[sym::XCO];
        cpu.flags.c = false;
        let _r = (cpu.reg.a as u16) + (0x01) as u16 + (cpu.flags.c as u16);
        cpu.reg.a = _r as u8;
        cpu.flags.c = (_r >> 8) != 0;
        cpu.mem[sym::XCO] = cpu.reg.a;
        getlevelno(cpu);
    }
    cpu.mem[sym::IMAGE] = cpu.mem[sym::digit2 + cpu.reg.x as usize];
    cpu.reg.a = 0x01;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn getlevelno(cpu: &mut Cpu) {
    cpu.reg.x = cpu.mem[sym::level];
    if cpu.reg.x >= 0x0d {
        cpu.reg.x = 0x0c;
    }
    return;
}

pub fn CONTINUEMSG(cpu: &mut Cpu) {
    cpu.reg.a = 0x6d;
    cpu.reg.x = 0x01;
    setupimage(cpu);
    cpu.reg.a = cpu.mem[sym::KidBlockX];
    cpu.reg.a &= 0x01;
    if cpu.reg.a != 0x00 {
        superim1(cpu);
        return;
    }
    cpu.mem[sym::YCO] = 0xa8;
    superim1(cpu);
    return;
}

pub fn FLIPDISKMSG(cpu: &mut Cpu) {
    cpu.reg.a = 0x70;
    cpu.reg.x = 0x01;
    superimage(cpu);
    return;
}

pub fn superimage(cpu: &mut Cpu) {
    setupimage(cpu);
    cpu.reg.a = 0x42;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn superim1(cpu: &mut Cpu) {
    cpu.reg.a = 0x42;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn setupimage(cpu: &mut Cpu) {
    cpu.mem[sym::addr] = cpu.reg.a;
    cpu.mem[sym::addr + 1] = cpu.reg.x;
    cpu.reg.y = 0x00;
    cpu.mem[sym::YCO] = cpu.mem[(cpu.mem[sym::addr] as usize | (cpu.mem[sym::addr + 1] as usize) << 8) + cpu.reg.y as usize];
    cpu.reg.y = cpu.reg.y.wrapping_add(1);
    cpu.mem[sym::XCO] = cpu.mem[(cpu.mem[sym::addr] as usize | (cpu.mem[sym::addr + 1] as usize) << 8) + cpu.reg.y as usize];
    cpu.reg.y = cpu.reg.y.wrapping_add(1);
    cpu.mem[sym::OFFSET] = cpu.mem[(cpu.mem[sym::addr] as usize | (cpu.mem[sym::addr + 1] as usize) << 8) + cpu.reg.y as usize];
    cpu.reg.y = cpu.reg.y.wrapping_add(1);
    cpu.reg.a = cpu.mem[(cpu.mem[sym::addr] as usize | (cpu.mem[sym::addr + 1] as usize) << 8) + cpu.reg.y as usize];
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    return;
}

pub fn DRAWKID(cpu: &mut Cpu) {
    cpu.reg.a = cpu.mem[sym::backtolife];
    if cpu.reg.a != 0x00 {
        cpu.reg.a = cpu.mem[sym::PAGE];
        if cpu.reg.a == 0x00 {
            return;
        }
    }
    cpu.reg.a = cpu.mem[sym::mergetimer];
    if (cpu.reg.a as i8) < 0 {
        DrawNormal(cpu);
        return;
    }
    cpu.reg.a &= 0x01;
    if cpu.reg.a == 0x00 {
        DrawNormal(cpu);
        return;
    }
    DrawEored(cpu);
    return;
}

pub fn DRAWSWORD(cpu: &mut Cpu) {
    DrawNormal(cpu);
    return;
}

pub fn DRAWSHAD(cpu: &mut Cpu) {
    DrawEored(cpu);
    return;
}

pub fn DrawNormal(cpu: &mut Cpu) {
    cpu.mem[sym::OPACITY] = 0x04;
    cpu.reg.a = 0x82;
    crate::ext::addmid(cpu);
    return;
}

pub fn DrawShifted(cpu: &mut Cpu) {
    cpu.reg.a = 0x01;
    chgoffset(cpu);
    cpu.mem[sym::OPACITY] = 0x04;
    cpu.reg.a = 0x82;
    crate::ext::addmid(cpu);
    return;
}

pub fn DrawEored(cpu: &mut Cpu) {
    cpu.mem[sym::OPACITY] = 0x03;
    cpu.reg.a = 0x82;
    crate::ext::addmid(cpu);
    return;
}

pub fn chgoffset(cpu: &mut Cpu) {
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + cpu.mem[sym::OFFSET] as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    if cpu.reg.a >= 0x07 {
        cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
        cpu.flags.c = true;
        let _r = (cpu.reg.a as u16) + (!0x07_u8) as u16 + (cpu.flags.c as u16);
        cpu.reg.a = _r as u8;
        cpu.flags.c = (_r >> 8) != 0;
    }
    cpu.mem[sym::OFFSET] = cpu.reg.a;
    return;
}

pub fn UPDATEMETERS(cpu: &mut Cpu) {
    cpu.reg.a = cpu.mem[sym::redkidmeter];
    if cpu.reg.a != 0x00 {
        crate::ext::DrawKidMeter(cpu);
    }
    cpu.reg.a = cpu.mem[sym::redoppmeter];
    if cpu.reg.a == 0x00 {
        return;
    }
    crate::ext::DrawOppMeter(cpu);
    return;
}

pub fn DRAWKIDMETER(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.reg.a = cpu.mem[sym::inbuilder];
                if cpu.reg.a != 0x00 {
                    pc = 19;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.reg.a = 0xbf;
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.reg.a = 0x02;
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.reg.x = 0x00;
                cpu.mem[sym::xsave] = cpu.reg.x;
                pc = 2;
            }
            2 => {
                cpu.reg.a = cpu.mem[sym::KidStrength];
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!cpu.mem[sym::xsave]) as u16 + (cpu.flags.c as u16);
                cpu.reg.a = _r as u8;
                cpu.flags.c = (_r >> 8) != 0;
                if cpu.reg.a == 0x00 {
                    pc = 16;
                } else {
                    pc = 3;
                }
            }
            3 => {
                let _o: u8 = 0x04;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x04 {
                    pc = 8;
                } else {
                    pc = 4;
                }
            }
            4 => {
                let _o: u8 = 0x03;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x03 {
                    pc = 7;
                } else {
                    pc = 5;
                }
            }
            5 => {
                let _o: u8 = 0x02;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a < 0x02 {
                    pc = 9;
                } else {
                    pc = 6;
                }
            }
            6 => {
                cpu.reg.y = 0x01;
                if cpu.reg.y != 0x00 {
                    pc = 13;
                } else {
                    pc = 7;
                }
            }
            7 => {
                cpu.reg.y = 0x02;
                if cpu.reg.y != 0x00 {
                    pc = 13;
                } else {
                    pc = 8;
                }
            }
            8 => {
                cpu.reg.y = 0x03;
                if cpu.reg.y != 0x00 {
                    pc = 13;
                } else {
                    pc = 9;
                }
            }
            9 => {
                cpu.reg.a = cpu.mem[sym::KidStrength];
                let _o: u8 = 0x02;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x02 {
                    pc = 11;
                } else {
                    pc = 10;
                }
            }
            10 => {
                cpu.reg.a = cpu.mem[sym::PAGE];
                if cpu.reg.a == 0x00 {
                    pc = 12;
                } else {
                    pc = 11;
                }
            }
            11 => {
                cpu.reg.a = 0x88;
                cpu.reg.y = 0x01;
                _3adraw(cpu);
                pc = 12;
            }
            12 => {
                pc = 16;
            }
            13 => {
                cpu.reg.a = cpu.mem[sym::bline - 1 + cpu.reg.y as usize];
                _3adraw(cpu);
                pc = 2;
            }
            14 => {
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                cpu.reg.x = cpu.mem[sym::xsave];
                cpu.reg.a = cpu.reg.y;
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + cpu.mem[sym::xsave] as u16 + (cpu.flags.c as u16);
                cpu.reg.a = _r as u8;
                cpu.flags.c = (_r >> 8) != 0;
                cpu.mem[sym::xsave] = cpu.reg.a;
                pc = 15;
            }
            15 => {
                cpu.reg.a = cpu.mem[sym::KidStrX + cpu.reg.x as usize];
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.reg.a = cpu.mem[sym::KidStrOFF + cpu.reg.x as usize];
                cpu.mem[sym::OFFSET] = cpu.reg.a;
                crate::ext::addmsg(cpu);
                return;
            }
            16 => {
                cpu.reg.a = 0x00;
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.reg.a = 0x8c;
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                pc = 17;
            }
            17 => {
                cpu.reg.x = cpu.mem[sym::xsave];
                let _o: u8 = cpu.mem[sym::MaxKidStr];
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.x >= cpu.mem[sym::MaxKidStr] {
                    pc = 19;
                } else {
                    pc = 18;
                }
            }
            18 => {
                _3adrawimg(cpu);
                cpu.mem[sym::xsave] = cpu.mem[sym::xsave].wrapping_add(1);
                if !cpu.flags.z {
                    pc = 17;
                } else {
                    pc = 19;
                }
            }
            19 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn DRAWOPPMETER(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.reg.a = cpu.mem[sym::inbuilder];
                if cpu.reg.a != 0x00 {
                    pc = 21;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.reg.a = cpu.mem[sym::OppStrength];
                if cpu.reg.a == 0x00 {
                    pc = 21;
                } else {
                    pc = 2;
                }
            }
            2 => {
                cpu.reg.a = cpu.mem[sym::ShadID];
                let _o: u8 = 0x18;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a == 0x18 {
                    pc = 21;
                } else {
                    pc = 3;
                }
            }
            3 => {
                let _o: u8 = 0x04;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a == 0x04 {
                    pc = 21;
                } else {
                    pc = 4;
                }
            }
            4 => {
                let _o: u8 = 0x01;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != 0x01 {
                    pc = 6;
                } else {
                    pc = 5;
                }
            }
            5 => {
                cpu.reg.a = cpu.mem[sym::level];
                let _o: u8 = 0x0c;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != 0x0c {
                    pc = 21;
                } else {
                    pc = 6;
                }
            }
            6 => {
                cpu.reg.a = 0xbf;
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.reg.a = 0x82;
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.reg.x = 0x00;
                cpu.mem[sym::xsave] = cpu.reg.x;
                pc = 7;
            }
            7 => {
                cpu.reg.a = cpu.mem[sym::OppStrength];
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!cpu.mem[sym::xsave]) as u16 + (cpu.flags.c as u16);
                cpu.reg.a = _r as u8;
                cpu.flags.c = (_r >> 8) != 0;
                if cpu.reg.a == 0x00 {
                    pc = 20;
                } else {
                    pc = 8;
                }
            }
            8 => {
                let _o: u8 = 0x04;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x04 {
                    pc = 13;
                } else {
                    pc = 9;
                }
            }
            9 => {
                let _o: u8 = 0x03;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x03 {
                    pc = 12;
                } else {
                    pc = 10;
                }
            }
            10 => {
                let _o: u8 = 0x02;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a < 0x02 {
                    pc = 14;
                } else {
                    pc = 11;
                }
            }
            11 => {
                cpu.reg.y = 0x01;
                if cpu.reg.y != 0x00 {
                    pc = 17;
                } else {
                    pc = 12;
                }
            }
            12 => {
                cpu.reg.y = 0x02;
                if cpu.reg.y != 0x00 {
                    pc = 17;
                } else {
                    pc = 13;
                }
            }
            13 => {
                cpu.reg.y = 0x03;
                if cpu.reg.y != 0x00 {
                    pc = 17;
                } else {
                    pc = 14;
                }
            }
            14 => {
                cpu.reg.a = cpu.mem[sym::OppStrength];
                let _o: u8 = 0x02;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a >= 0x02 {
                    pc = 16;
                } else {
                    pc = 15;
                }
            }
            15 => {
                cpu.reg.a = cpu.mem[sym::PAGE];
                if cpu.reg.a == 0x00 {
                    pc = 20;
                } else {
                    pc = 16;
                }
            }
            16 => {
                cpu.reg.a = 0x88;
                cpu.reg.y = 0x01;
                pc = 18;
            }
            17 => {
                cpu.reg.a = cpu.mem[sym::bline - 1 + cpu.reg.y as usize];
                _3adraw(cpu);
                pc = 7;
            }
            18 => {
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                cpu.reg.x = cpu.mem[sym::xsave];
                cpu.reg.a = cpu.reg.y;
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + cpu.mem[sym::xsave] as u16 + (cpu.flags.c as u16);
                cpu.reg.a = _r as u8;
                cpu.flags.c = (_r >> 8) != 0;
                cpu.mem[sym::xsave] = cpu.reg.a;
                pc = 19;
            }
            19 => {
                cpu.reg.a = cpu.mem[sym::OppStrX + cpu.reg.x as usize];
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.reg.a = cpu.mem[sym::OppStrOFF + cpu.reg.x as usize];
                cpu.mem[sym::OFFSET] = cpu.reg.a;
                crate::ext::addmsg(cpu);
                return;
            }
            20 => {
                cpu.reg.a = 0x80;
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.reg.a = 0x8c;
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                cpu.reg.x = cpu.mem[sym::xsave];
                pc = 19;
            }
            21 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn SETUPFLASK(cpu: &mut Cpu) {
    cpu.mem[sym::OFFSET] = 0x02;
    cpu.reg.a = cpu.reg.x;
    cpu.reg.a &= 0xe0;
    let _o: u8 = 0x00;
    cpu.flags.c = cpu.reg.a >= _o;
    cpu.flags.z = cpu.reg.a == _o;
    cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
    if cpu.reg.a == 0x00 {
        cpu.reg.x = 0x00;
        if cpu.reg.x != 0x00 {
            let _o: u8 = 0x12;
            cpu.flags.c = cpu.reg.x >= _o;
            cpu.flags.z = cpu.reg.x == _o;
            cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
            if cpu.reg.x >= 0x12 {
                return;
            }
            cpu.mem[sym::IMAGE] = cpu.mem[sym::torchflame + cpu.reg.x as usize];
            cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
            cpu.reg.a = cpu.mem[sym::YCO];
            cpu.flags.c = true;
            let _r = (cpu.reg.a as u16) + (!0x2b_u8) as u16 + (cpu.flags.c as u16);
            cpu.reg.a = _r as u8;
            cpu.flags.c = (_r >> 8) != 0;
            cpu.mem[sym::YCO] = cpu.reg.a;
            cpu.mem[sym::OPACITY] = 0x02;
            cpu.mem[sym::TABLE] = 0x00;
            cpu.reg.a = 0x60;
            cpu.mem[sym::TABLE + 1] = cpu.reg.a;
            return;
        }
    } else {
        'b5: {
            let _o: u8 = 0x40;
            cpu.flags.c = cpu.reg.a >= _o;
            cpu.flags.z = cpu.reg.a == _o;
            cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
            if cpu.reg.a != 0x40 {
                if !cpu.flags.c {
                    break 'b5;
                } else {
                    cpu.mem[sym::OFFSET] = cpu.mem[sym::OFFSET].wrapping_add(1);
                }
            }
            cpu.reg.a = cpu.mem[sym::YCO];
            cpu.flags.c = true;
            let _r = (cpu.reg.a as u16) + (!0x04_u8) as u16 + (cpu.flags.c as u16);
            cpu.reg.a = _r as u8;
            cpu.flags.c = (_r >> 8) != 0;
            cpu.mem[sym::YCO] = cpu.reg.a;
        }
        cpu.reg.a = cpu.reg.x;
        cpu.reg.a &= 0x1f;
        cpu.reg.x = cpu.reg.a;
        let _o: u8 = 0x09;
        cpu.flags.c = cpu.reg.x >= _o;
        cpu.flags.z = cpu.reg.x == _o;
        cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
        if cpu.reg.x >= 0x09 {
            cpu.reg.x = 0x00;
        }
    }
    cpu.mem[sym::IMAGE] = cpu.mem[sym::bubble + cpu.reg.x as usize];
    cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
    cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
    cpu.reg.a = cpu.mem[sym::YCO];
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!0x0e_u8) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::YCO] = cpu.reg.a;
    cpu.mem[sym::OPACITY] = 0x02;
    cpu.mem[sym::TABLE] = 0x00;
    cpu.reg.a = 0x84;
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    return;
}

pub fn SETUPFLAME(cpu: &mut Cpu) {
    if cpu.reg.x >= 0x12 {
        return;
    }
    cpu.mem[sym::IMAGE] = cpu.mem[sym::torchflame + cpu.reg.x as usize];
    cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
    cpu.reg.a = cpu.mem[sym::YCO];
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!0x2b_u8) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::YCO] = cpu.reg.a;
    cpu.mem[sym::OPACITY] = 0x02;
    cpu.mem[sym::TABLE] = 0x00;
    cpu.reg.a = 0x60;
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    return;
}

pub fn PSETUPFLAME(cpu: &mut Cpu) {
    if cpu.reg.x >= 0x12 {
        return;
    }
    cpu.mem[sym::IMAGE] = cpu.mem[sym::ptorchflame + cpu.reg.x as usize];
    cpu.reg.a = 0x02;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::ext::initlay(cpu);
    cpu.mem[sym::TABLE] = 0x00;
    cpu.reg.a = 0x60;
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    return;
}

pub fn TWINKLE(cpu: &mut Cpu) {
    cpu.mem[sym::XCO] = 0x02;
    cpu.mem[sym::YCO] = cpu.mem[sym::stary + cpu.reg.x as usize];
    cpu.mem[sym::IMAGE] = cpu.mem[sym::stari + cpu.reg.x as usize];
    cpu.mem[sym::OPACITY] = 0x03;
    _5dsetch6(cpu);
    crate::hires::fastlay(cpu);
    cpu.reg.a = cpu.mem[sym::PAGE];
    cpu.reg.a ^= 0x20;
    cpu.mem[sym::PAGE] = cpu.reg.a;
    crate::hires::fastlay(cpu);
    cpu.reg.a = cpu.mem[sym::PAGE];
    cpu.reg.a ^= 0x20;
    cpu.mem[sym::PAGE] = cpu.reg.a;
    return;
}

pub fn DRAWPOST(cpu: &mut Cpu) {
    cpu.mem[sym::XCO] = 0x1f;
    cpu.mem[sym::YCO] = 0x98;
    cpu.mem[sym::IMAGE] = 0x0c;
    cpu.mem[sym::OPACITY] = 0x01;
    _5dsetch6(cpu);
    crate::ext::addfore(cpu);
    return;
}

pub fn DRAWGLASS(cpu: &mut Cpu) {
    cpu.mem[sym::XCO] = 0x13;
    cpu.mem[sym::YCO] = 0x97;
    cpu.mem[sym::IMAGE] = cpu.mem[sym::glassimg + cpu.reg.x as usize];
    cpu.mem[sym::OPACITY] = 0x02;
    _5dsetch6(cpu);
    crate::ext::addback(cpu);
    return;
}

pub fn PMASK(cpu: &mut Cpu) {
    'b7: {
        cpu.reg.x = cpu.mem[sym::CharPosn];
        if cpu.reg.x == 0x13 {
            cpu.reg.x = 0x00;
            if (cpu.reg.x as i8) >= 0 {
                break 'b7;
            }
        }
        'b5: {
            if cpu.reg.x != 0x01 {
                if cpu.reg.x != 0x12 {
                    break 'b5;
                }
            }
            cpu.reg.x = 0x01;
            if (cpu.reg.x as i8) >= 0 {
                break 'b7;
            }
        }
        return;
    }
    cpu.mem[sym::YCO] = (cpu.mem[sym::FCharY]).wrapping_add(cpu.mem[sym::pmaskdy + cpu.reg.x as usize]);
    cpu.reg.a = cpu.mem[sym::XCO];
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + cpu.mem[sym::pmaskdx + cpu.reg.x as usize] as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::XCO] = cpu.reg.a;
    cpu.mem[sym::IMAGE] = cpu.mem[sym::pmaski + cpu.reg.x as usize];
    cpu.mem[sym::TABLE] = 0x05;
    cpu.mem[sym::OPACITY] = 0x00;
    cpu.reg.a = 0x82;
    crate::ext::addmid(cpu);
    return;
}

pub fn RECHECKYEL(cpu: &mut Cpu) {
    cpu.mem[sym::tempblockx] = cpu.reg.a;
    cpu.mem[sym::tempblocky] = cpu.reg.a;
    crate::ext::indexblock(cpu);
    cpu.reg.a = cpu.mem[(cpu.mem[sym::locals] as usize | (cpu.mem[sym::locals + 1] as usize) << 8) + cpu.reg.y as usize];
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.reg.x = 0x05;
    crate::ext::yellow(cpu);
    cpu.reg.a = 0xff;
    return;
}

pub fn FLOW(cpu: &mut Cpu) {
    if cpu.reg.y >= 0x08 {
        return;
    }
    crate::ext::initlay(cpu);
    cpu.reg.a = 0x97;
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!cpu.mem[sym::sandht + cpu.reg.y as usize]) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::BOTCUT] = cpu.reg.a;
    cpu.mem[sym::IMAGE] = cpu.mem[sym::flowimg + cpu.reg.x as usize];
    cpu.mem[sym::XCO] = 0x14;
    cpu.mem[sym::OFFSET] = 0x00;
    cpu.mem[sym::YCO] = 0x95;
    cpu.mem[sym::OPACITY] = 0x02;
    _5dsetch6(cpu);
    crate::hires::lay(cpu);
    return;
}

pub fn saveFChar(cpu: &mut Cpu) {
    cpu.reg.x = 0x0f;
    loop {
        cpu.reg.a = cpu.mem[sym::FCharVars + cpu.reg.x as usize];
        cpu.mem[sym::tempsave + cpu.reg.x as usize] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    return;
}

pub fn restoreFChar(cpu: &mut Cpu) {
    cpu.reg.x = 0x0f;
    loop {
        cpu.reg.a = cpu.mem[sym::tempsave + cpu.reg.x as usize];
        cpu.mem[sym::FCharVars + cpu.reg.x as usize] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    return;
}

pub fn SETUPCOMIX(cpu: &mut Cpu) {
    saveFChar(cpu);
    _3asub(cpu);
    restoreFChar(cpu);
    return;
}

pub fn ADDCHAROBJ(cpu: &mut Cpu) {
    cpu.reg.x = cpu.mem[sym::objX];
    cpu.reg.x = cpu.reg.x.wrapping_add(1);
    if cpu.reg.x >= 0x14 {
        return;
    }
    cpu.mem[sym::objX] = cpu.reg.x;
    cpu.mem[sym::objTYP + cpu.reg.x as usize] = cpu.reg.a;
    cpu.mem[sym::XCO] = cpu.mem[sym::FCharX];
    cpu.mem[sym::OFFSET] = cpu.mem[sym::FCharX + 1];
    cpu.reg.a = cpu.reg.x;
    let tmp0 = cpu.reg.a;
    crate::ext::cvtx(cpu);
    cpu.reg.a = tmp0;
    cpu.reg.x = cpu.reg.a;
    cpu.mem[sym::objX + cpu.reg.x as usize] = cpu.mem[sym::XCO];
    cpu.mem[sym::objOFF + cpu.reg.x as usize] = cpu.mem[sym::OFFSET];
    cpu.mem[sym::objY + cpu.reg.x as usize] = cpu.mem[sym::FCharY];
    cpu.mem[sym::objCU + cpu.reg.x as usize] = cpu.mem[sym::FCharCU];
    cpu.mem[sym::objCL + cpu.reg.x as usize] = cpu.mem[sym::FCharCL];
    cpu.mem[sym::objCR + cpu.reg.x as usize] = cpu.mem[sym::FCharCR];
    cpu.mem[sym::objCD + cpu.reg.x as usize] = cpu.mem[sym::FCharCD];
    cpu.mem[sym::objIMG + cpu.reg.x as usize] = cpu.mem[sym::FCharImage];
    cpu.mem[sym::objTAB + cpu.reg.x as usize] = cpu.mem[sym::FCharTable];
    cpu.mem[sym::objFACE + cpu.reg.x as usize] = cpu.mem[sym::FCharFace];
    SETOBJINDX(cpu);
    return;
}

pub fn SETOBJINDX(cpu: &mut Cpu) {
    cpu.reg.a = cpu.mem[sym::FCharIndex];
    cpu.mem[sym::objINDX + cpu.reg.x as usize] = cpu.reg.a;
    if cpu.reg.a >= 0x1e {
        return;
    }
    cpu.reg.x = cpu.reg.a;
    cpu.reg.a = 0x01;
    cpu.mem[sym::objbuf + cpu.reg.x as usize] = cpu.reg.a;
    return;
}

pub fn pretext(cpu: &mut Cpu) {
    crate::ext::initlay(cpu);
    cpu.mem[sym::TABLE] = 0x00;
    cpu.reg.a = 0x84;
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    return;
}

pub fn SETRECHECK0(cpu: &mut Cpu) {
    cpu.mem[sym::locals] = 0xf8;
    cpu.mem[sym::locals + 1] = 0x03;
    cpu.mem[sym::BANK] = 0x03;
    cpu.mem[sym::RIGHTCUT] = 0x28;
    cpu.mem[sym::BOTCUT] = 0xc0;
    cpu.reg.a = 0x00;
    cpu.mem[sym::LEFTCUT] = cpu.reg.a;
    cpu.mem[sym::TOPCUT] = cpu.reg.a;
    return;
}

pub fn INITLAY(cpu: &mut Cpu) {
    cpu.mem[sym::BANK] = 0x03;
    cpu.mem[sym::RIGHTCUT] = 0x28;
    cpu.mem[sym::BOTCUT] = 0xc0;
    cpu.reg.a = 0x00;
    cpu.mem[sym::LEFTCUT] = cpu.reg.a;
    cpu.mem[sym::TOPCUT] = cpu.reg.a;
    return;
}

pub fn prchar(cpu: &mut Cpu) {
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!0x2f_u8) as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    cpu.reg.a = 0x01;
    cpu.mem[sym::OPACITY] = cpu.reg.a;
    crate::hires::lay(cpu);
    cpu.mem[sym::XCO] = cpu.mem[sym::XCO].wrapping_add(1);
    return;
}

pub fn _3adraw(cpu: &mut Cpu) {
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    cpu.reg.x = cpu.mem[sym::xsave];
    cpu.reg.a = cpu.reg.y;
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + cpu.mem[sym::xsave] as u16 + (cpu.flags.c as u16);
    cpu.reg.a = _r as u8;
    cpu.flags.c = (_r >> 8) != 0;
    cpu.mem[sym::xsave] = cpu.reg.a;
    cpu.mem[sym::XCO] = cpu.mem[sym::OppStrX + cpu.reg.x as usize];
    cpu.reg.a = cpu.mem[sym::OppStrOFF + cpu.reg.x as usize];
    cpu.mem[sym::OFFSET] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn _3adrawimg(cpu: &mut Cpu) {
    cpu.mem[sym::XCO] = cpu.mem[sym::OppStrX + cpu.reg.x as usize];
    cpu.reg.a = cpu.mem[sym::OppStrOFF + cpu.reg.x as usize];
    cpu.mem[sym::OFFSET] = cpu.reg.a;
    crate::ext::addmsg(cpu);
    return;
}

pub fn _5dsetch6(cpu: &mut Cpu) {
    cpu.mem[sym::TABLE] = 0x00;
    cpu.reg.a = 0x60;
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    return;
}

pub fn _3asub(cpu: &mut Cpu) {
    'b11: {
        'b10: {
            'b8: {
                cpu.reg.a = 0xff;
                cpu.mem[sym::FCharIndex] = cpu.reg.a;
                cpu.reg.a = cpu.mem[sym::CharPosn];
                if cpu.reg.a != 0xb9 {
                    let _o: u8 = 0xb1;
                    cpu.flags.c = cpu.reg.a >= _o;
                    cpu.flags.z = cpu.reg.a == _o;
                    cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if cpu.reg.a == 0xb1 {
                        // raw: ??? lda #-5 impaled            ; GAMEBG.S:1004
                        if !cpu.flags.z {
                            break 'b11;
                        } else {
                            break 'b10;
                        }
                    } else {
                        if cpu.reg.a >= 0x6a {
                            if cpu.reg.a < 0x6f {
                                break 'b8;
                            }
                        }
                        if cpu.reg.a == 0xb2 {
                            return;
                        }
                        cpu.reg.a = 0xf1;
                        cpu.reg.x = cpu.mem[sym::CharID];
                        if cpu.reg.x != 0x00 {
                            cpu.reg.a = 0xf5;
                        }
                        cpu.flags.c = false;
                        let _r = (cpu.reg.a as u16) + cpu.mem[sym::FCharY] as u16 + (cpu.flags.c as u16);
                        cpu.reg.a = _r as u8;
                        cpu.flags.c = (_r >> 8) != 0;
                        cpu.mem[sym::FCharY] = cpu.reg.a;
                        break 'b10;
                    }
                }
            }
            cpu.reg.a = 0x04;
            cpu.flags.c = false;
            let _r = (cpu.reg.a as u16) + cpu.mem[sym::FCharY] as u16 + (cpu.flags.c as u16);
            cpu.reg.a = _r as u8;
            cpu.flags.c = (_r >> 8) != 0;
            cpu.mem[sym::FCharY] = cpu.reg.a;
        }
        cpu.reg.a = 0x05;
    }
    crate::ext::addfcharx(cpu);
    cpu.reg.a = cpu.mem[sym::CharID];
    if cpu.reg.a != 0x00 {
        cpu.reg.a = 0x01;
    }
    cpu.reg.a ^= cpu.mem[sym::FCharX];
    cpu.reg.a ^= cpu.mem[sym::FCharFace];
    cpu.reg.a &= 0x01;
    if cpu.reg.a == 0x00 {
        cpu.mem[sym::FCharX] = cpu.mem[sym::FCharX].wrapping_add(1);
        if cpu.flags.z {
            cpu.mem[sym::FCharX + 1] = cpu.mem[sym::FCharX + 1].wrapping_add(1);
        }
    }
    cpu.mem[sym::FCharImage] = 0x41;
    cpu.mem[sym::FCharTable] = 0x00;
    cpu.mem[sym::FCharCU] = 0x00;
    cpu.mem[sym::FCharCL] = 0x00;
    cpu.mem[sym::FCharCR] = 0x28;
    cpu.mem[sym::FCharCD] = 0xc0;
    cpu.reg.a = 0x05;
    crate::ext::addcharobj(cpu);
    return;
}
