// @generated by pop_lifter — DO NOT EDIT.
// POP source segment `GRAFIX` (98 routines),
// lifted to free functions over the shared `Cpu`.

use crate::cpu::Cpu;
use crate::sym;

pub fn VBLvect(cpu: &mut Cpu) {
    VBLANK(cpu);
    return;
}

#[doc(alias = "addback")]
pub fn ADDBACK(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::bgX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x < 0xc8 {
        cpu.mem[(sym::bgX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
        cpu.set_a(cpu.mem[sym::YCO]);
        if cpu.reg.a < 0xc0 {
            cpu.mem[(sym::bgY + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
            cpu.mem[(sym::bgIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
            cpu.set_a(cpu.mem[sym::OPACITY]);
            cpu.mem[(sym::bgOP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
            cpu.mem[sym::bgX] = cpu.reg.x;
        }
    }
    return;
}

#[doc(alias = "addfore")]
pub fn ADDFORE(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::fgX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x64 {
        return;
    }
    cpu.mem[(sym::fgX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.set_a(cpu.mem[sym::YCO]);
    if cpu.reg.a >= 0xc0 {
        return;
    }
    cpu.mem[(sym::fgY + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[(sym::fgIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
    cpu.set_a(cpu.mem[sym::OPACITY]);
    cpu.mem[(sym::fgOP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::fgX] = cpu.reg.x;
    return;
}

#[doc(alias = "addmsg")]
pub fn ADDMSG(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::msgX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x20 {
        return;
    }
    cpu.mem[(sym::msgX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.mem[(sym::msgOFF + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OFFSET];
    cpu.mem[(sym::msgY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::YCO];
    cpu.mem[(sym::msgIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
    cpu.set_a(cpu.mem[sym::OPACITY]);
    cpu.mem[(sym::msgOP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::msgX] = cpu.reg.x;
    return;
}

#[doc(alias = "addwipe")]
pub fn ADDWIPE(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::wipeX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x14 {
        return;
    }
    cpu.mem[(sym::wipeCOL + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.set_a(cpu.mem[sym::blackflag]);
    if cpu.reg.a != 0x00 {
        cpu.set_a(0xff);
        cpu.mem[(sym::wipeCOL + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    }
    cpu.mem[(sym::wipeX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.mem[(sym::wipeY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::YCO];
    cpu.mem[(sym::wipeH + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::height];
    cpu.set_a(cpu.mem[sym::width]);
    cpu.mem[(sym::wipeW + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::wipeX] = cpu.reg.x;
    return;
}

#[doc(alias = "addmid")]
pub fn ADDMID(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::midX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x2e {
        return;
    }
    cpu.mem[(sym::midTYP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[(sym::midX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.mem[(sym::midOFF + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OFFSET];
    cpu.mem[(sym::midY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::YCO];
    cpu.mem[(sym::midIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
    cpu.mem[(sym::midTAB + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::TABLE];
    cpu.set_a(cpu.mem[sym::FCharFace]);
    cpu.set_a(cpu.reg.a ^ 0xff);
    cpu.set_a(cpu.reg.a & 0x80);
    cpu.set_a(cpu.reg.a | cpu.mem[sym::OPACITY]);
    cpu.mem[(sym::midOP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[(sym::midCU + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::FCharCU];
    cpu.mem[(sym::midCD + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::FCharCD];
    cpu.mem[(sym::midCL + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::FCharCL];
    cpu.set_a(cpu.mem[sym::FCharCR]);
    cpu.mem[(sym::midCR + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::midX] = cpu.reg.x;
    return;
}

#[doc(alias = "addmidez")]
pub fn ADDMIDEZ(cpu: &mut Cpu) {
    cpu.set_a(0x00);
    cpu.mem[sym::OFFSET] = cpu.reg.a;
    cpu.set_x(cpu.mem[sym::midX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x2e {
        return;
    }
    cpu.mem[(sym::midTYP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[(sym::midX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.mem[(sym::midOFF + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OFFSET];
    cpu.mem[(sym::midY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::YCO];
    cpu.mem[(sym::midIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
    cpu.mem[(sym::midTAB + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::TABLE];
    cpu.mem[(sym::midOP + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OPACITY];
    cpu.mem[(sym::midCU + cpu.reg.x as usize) & 0xffff] = 0x00;
    cpu.mem[(sym::midCL + cpu.reg.x as usize) & 0xffff] = 0x00;
    cpu.mem[(sym::midCR + cpu.reg.x as usize) & 0xffff] = 0x28;
    cpu.set_a(0xc0);
    cpu.mem[(sym::midCD + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::midX] = cpu.reg.x;
    return;
}

#[doc(alias = "addmidezo")]
pub fn ADDMIDEZO(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::midX]);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    if cpu.reg.x >= 0x2e {
        return;
    }
    cpu.mem[(sym::midTYP + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[(sym::midX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::XCO];
    cpu.mem[(sym::midOFF + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OFFSET];
    cpu.mem[(sym::midY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::YCO];
    cpu.mem[(sym::midIMG + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::IMAGE];
    cpu.mem[(sym::midTAB + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::TABLE];
    cpu.mem[(sym::midOP + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::OPACITY];
    cpu.mem[(sym::midCU + cpu.reg.x as usize) & 0xffff] = 0x00;
    cpu.mem[(sym::midCL + cpu.reg.x as usize) & 0xffff] = 0x00;
    cpu.mem[(sym::midCR + cpu.reg.x as usize) & 0xffff] = 0x28;
    cpu.set_a(0xc0);
    cpu.mem[(sym::midCD + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.mem[sym::midX] = cpu.reg.x;
    return;
}

#[doc(alias = "addpeel")]
pub fn ADDPEEL(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::PEELIMG + 1]);
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.set_a(cpu.mem[sym::PAGE]);
    if cpu.reg.a != 0x00 {
        cpu.set_x(cpu.mem[sym::purpleflag]);
        cpu.set_a(cpu.mem[(sym::dummy + cpu.reg.x as usize) & 0xffff]);
    }
    cpu.smc.sm = cpu.reg.a;
    cpu.set_x(cpu.reg.a);
    cpu.set_a(cpu.mem[(sym::peelX + cpu.reg.x as usize) & 0xffff]);
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x01) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    if cpu.reg.a >= 0x2e {
        return;
    }
    cpu.mem[(sym::peelX + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (cpu.smc.sm) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.set_x(cpu.reg.a);
    cpu.mem[(sym::peelX + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::PEELXCO];
    cpu.mem[(sym::peelY + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::PEELYCO];
    cpu.mem[(sym::peelIMGL + cpu.reg.x as usize) & 0xffff] = cpu.mem[sym::PEELIMG];
    cpu.set_a(cpu.mem[sym::PEELIMG + 1]);
    cpu.mem[(sym::peelIMGH + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    return;
}

#[doc(alias = "drawall")]
pub fn DRAWALL(cpu: &mut Cpu) {
    DOGEN(cpu);
    cpu.set_a(cpu.mem[sym::blackflag]);
    if cpu.reg.a == 0x00 {
        SNGPEEL(cpu);
    }
    ZEROPEEL(cpu);
    DRAWWIPE(cpu);
    DRAWBACK(cpu);
    DRAWMID(cpu);
    DRAWFORE(cpu);
    DRAWMSG(cpu);
    return;
}

pub fn DOGEN(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::genCLS]);
    if cpu.reg.a != 0x00 {
        crate::hires::cls(cpu);
    }
    cpu.set_x(cpu.mem[sym::BGset1]);
    if cpu.reg.x != 0x01 {
        return;
    }
    cpu.set_a(0x00);
    cpu.mem[(sym::dummy - 1 + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    return;
}

pub fn DRAWWIPE(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(cpu.mem[sym::wipeX]);
                if cpu.reg.a == 0x00 {
                    pc = 4;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.set_a(0x01);  // start with image #1
                pc = 2;
            }
            2 => {
                cpu.stack.push(cpu.reg.a);
                cpu.set_x(cpu.reg.a);
                cpu.set_a(cpu.mem[(sym::wipeH + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::wipeW + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE + 1] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::wipeX + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::wipeY + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::wipeCOL + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                crate::hires::fastblack(cpu);
                let _v = cpu.stack.pop().expect("pla on empty stack");
                cpu.set_a(_v);
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + (0x01) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                let _o: u8 = cpu.mem[sym::wipeX];
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a < cpu.mem[sym::wipeX] {
                    pc = 2;
                } else {
                    pc = 3;
                }
            }
            3 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 4;
                }
            }
            4 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn DRAWBACK(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(cpu.mem[sym::bgX]);
                if cpu.reg.a == 0x00 {
                    pc = 4;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.set_x(0x01);
                pc = 2;
            }
            2 => {
                cpu.mem[sym::index] = cpu.reg.x;
                cpu.set_a(cpu.mem[(sym::bgIMG + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                setbgimg(cpu);
                cpu.set_a(cpu.mem[(sym::bgX + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::bgY + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::bgOP + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                crate::hires::fastlay(cpu);
                cpu.set_x(cpu.mem[sym::index]);
                cpu.set_x(cpu.reg.x.wrapping_add(1));
                let _o: u8 = cpu.mem[sym::bgX];
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.x < cpu.mem[sym::bgX] {
                    pc = 2;
                } else {
                    pc = 3;
                }
            }
            3 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 4;
                }
            }
            4 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn DRAWFORE(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(cpu.mem[sym::fgX]);
                if cpu.reg.a == 0x00 {
                    pc = 7;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.set_x(0x01);
                pc = 2;
            }
            2 => {
                cpu.mem[sym::index] = cpu.reg.x;
                cpu.set_a(cpu.mem[(sym::fgIMG + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                setbgimg(cpu);
                cpu.set_a(cpu.mem[(sym::fgX + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::fgY + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::fgOP + cpu.reg.x as usize) & 0xffff]);
                let _o: u8 = 0x04;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != 0x04 {
                    pc = 4;
                } else {
                    pc = 3;
                }
            }
            3 => {
                crate::hires::fastmask(cpu);
                pc = 5;
            }
            4 => {
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                crate::hires::fastlay(cpu);
                pc = 5;
            }
            5 => {
                cpu.set_x(cpu.mem[sym::index]);
                cpu.set_x(cpu.reg.x.wrapping_add(1));
                let _o: u8 = cpu.mem[sym::fgX];
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.x < cpu.mem[sym::fgX] {
                    pc = 2;
                } else {
                    pc = 6;
                }
            }
            6 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 7;
                }
            }
            7 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

#[doc(alias = "sngpeel")]
pub fn SNGPEEL(cpu: &mut Cpu) {
    cpu.set_x(cpu.mem[sym::PAGE]);
    if cpu.reg.x == 0x00 {
    } else {
        cpu.set_x(0x2e);
    }
    cpu.smc.sm = cpu.reg.x;
    cpu.set_a(cpu.mem[(sym::peelX + cpu.reg.x as usize) & 0xffff]);
    if cpu.reg.a == 0x00 {
    } else {
        loop {
            let tmp0 = cpu.reg.a;
            cpu.flags.c = false;
            let _r = (cpu.reg.a as u16) + (cpu.smc.sm) as u16 + (cpu.flags.c as u16);
            cpu.flags.c = (_r >> 8) != 0;
            cpu.set_a(_r as u8);
            cpu.set_x(cpu.reg.a);
            cpu.mem[sym::IMAGE] = cpu.mem[(sym::peelIMGL + cpu.reg.x as usize) & 0xffff];
            cpu.mem[sym::IMAGE + 1] = cpu.mem[(sym::peelIMGH + cpu.reg.x as usize) & 0xffff];
            cpu.mem[sym::XCO] = cpu.mem[(sym::peelX + cpu.reg.x as usize) & 0xffff];
            cpu.mem[sym::YCO] = cpu.mem[(sym::peelY + cpu.reg.x as usize) & 0xffff];
            cpu.set_a(0x02);
            cpu.mem[sym::OPACITY] = cpu.reg.a;
            crate::hires::peel(cpu);
            cpu.reg.a = tmp0;
            cpu.flags.c = true;
            let _r = (cpu.reg.a as u16) + (!0x01_u8) as u16 + (cpu.flags.c as u16);
            cpu.flags.c = (_r >> 8) != 0;
            cpu.set_a(_r as u8);
            if !(cpu.reg.a != 0x00) {
                break;
            }
        }
    }
    return;
}

pub fn DRAWMID(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(cpu.mem[sym::midX]);
                if cpu.reg.a == 0x00 {
                    pc = 10;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.set_x(0x01);
                pc = 2;
            }
            2 => {
                cpu.mem[sym::index] = cpu.reg.x;
                cpu.set_a(cpu.mem[(sym::midIMG + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midTAB + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::TABLE] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midX + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midY + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midOP + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midTYP + cpu.reg.x as usize) & 0xffff]);
                if (cpu.reg.a as i8) < 0 {
                    pc = 4;
                } else {
                    pc = 3;
                }
            }
            3 => {
                setbgimg(cpu);
                pc = 5;
            }
            4 => {
                setcharimg(cpu);
                pc = 5;
            }
            5 => {
                cpu.set_a(cpu.reg.a & 0x7f);
                if cpu.reg.a == 0x00 {
                    pc = 11;
                } else {
                    pc = 6;
                }
            }
            6 => {
                let _o: u8 = 0x01;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a == 0x01 {
                    pc = 13;
                } else {
                    pc = 7;
                }
            }
            7 => {
                let _o: u8 = 0x02;
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a == 0x02 {
                    pc = 12;
                } else {
                    pc = 8;
                }
            }
            8 => {
                cpu.set_x(cpu.mem[sym::index]);
                cpu.set_x(cpu.reg.x.wrapping_add(1));
                let _o: u8 = cpu.mem[sym::midX];
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.x < cpu.mem[sym::midX] {
                    pc = 2;
                } else {
                    pc = 9;
                }
            }
            9 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 10;
                }
            }
            10 => {
                return;
            }
            11 => {
                crate::hires::fastlay(cpu);
                pc = 8;
            }
            12 => {
                _3asetaddl(cpu);
                crate::hires::layrsave(cpu);
                ADDPEEL(cpu);
                crate::hires::lay(cpu);
                pc = 8;
            }
            13 => {
                _3asetaddl(cpu);
                crate::hires::lay(cpu);
                pc = 8;
            }
            14 => {
                cpu.set_a(cpu.mem[(sym::midOFF + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OFFSET] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midCL + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::LEFTCUT] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midCR + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::RIGHTCUT] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midCU + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::TOPCUT] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::midCD + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::BOTCUT] = cpu.reg.a;
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn DRAWMSG(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(cpu.mem[sym::msgX]);
                if cpu.reg.a == 0x00 {
                    pc = 6;
                } else {
                    pc = 1;
                }
            }
            1 => {
                cpu.set_x(0x01);
                pc = 2;
            }
            2 => {
                cpu.mem[sym::index] = cpu.reg.x;
                cpu.set_a(cpu.mem[(sym::msgIMG + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                setbgimg(cpu);
                cpu.set_a(cpu.mem[(sym::msgX + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::XCO] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::msgOFF + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OFFSET] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::msgY + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::YCO] = cpu.reg.a;
                cpu.set_a(0x00);
                cpu.mem[sym::LEFTCUT] = cpu.reg.a;
                cpu.mem[sym::TOPCUT] = cpu.reg.a;
                cpu.set_a(0x28);
                cpu.mem[sym::RIGHTCUT] = cpu.reg.a;
                cpu.set_a(0xc0);
                cpu.mem[sym::BOTCUT] = cpu.reg.a;
                cpu.set_a(cpu.mem[(sym::msgOP + cpu.reg.x as usize) & 0xffff]);
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                cpu.set_a(cpu.reg.a & 0x40);
                if cpu.reg.a == 0x00 {
                    pc = 4;
                } else {
                    pc = 3;
                }
            }
            3 => {
                cpu.set_a(cpu.mem[sym::OPACITY]);
                cpu.set_a(cpu.reg.a & 0xbf);
                cpu.mem[sym::OPACITY] = cpu.reg.a;
                crate::hires::layrsave(cpu);
                ADDPEEL(cpu);
                pc = 4;
            }
            4 => {
                crate::hires::lay(cpu);
                cpu.set_x(cpu.mem[sym::index]);
                cpu.set_x(cpu.reg.x.wrapping_add(1));
                let _o: u8 = cpu.mem[sym::msgX];
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.x < cpu.mem[sym::msgX] {
                    pc = 2;
                } else {
                    pc = 5;
                }
            }
            5 => {
                if cpu.flags.z {
                    pc = 2;
                } else {
                    pc = 6;
                }
            }
            6 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn setbgimg(cpu: &mut Cpu) {
    'b3: {
        cpu.set_y(cpu.reg.a);
        cpu.set_a(0x03);  // auxmem
        cpu.mem[sym::BANK] = cpu.reg.a;
        cpu.set_a(0x00);
        cpu.mem[sym::TABLE] = cpu.reg.a;
        cpu.set_a(cpu.mem[sym::IMAGE]);
        if (cpu.reg.a as i8) < 0 {
            cpu.set_a(cpu.reg.a & 0x7f);
            cpu.mem[sym::IMAGE] = cpu.reg.a;
            cpu.set_a(0x84);
            if cpu.reg.a != 0x00 {
                break 'b3;
            }
        }
        cpu.set_a(0x60);
    }
    cpu.mem[sym::TABLE + 1] = cpu.reg.a;
    cpu.set_a(cpu.reg.y);
    return;
}

pub fn setcharimg(cpu: &mut Cpu) {
    let tmp0 = cpu.reg.a;
    cpu.set_y(cpu.mem[sym::TABLE]);
    cpu.mem[sym::BANK] = cpu.mem[(sym::chtabbank + cpu.reg.y as usize) & 0xffff];
    cpu.mem[sym::TABLE] = 0x00;
    cpu.mem[sym::TABLE + 1] = cpu.mem[(sym::chtablist + cpu.reg.y as usize) & 0xffff];
    cpu.reg.a = tmp0;
    return;
}

#[doc(alias = "dimchar")]
pub fn DIMCHAR(cpu: &mut Cpu) {
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    cpu.mem[sym::TABLE] = cpu.reg.x;
    setcharimg(cpu);
    crate::hires::getwidth(cpu);
    return;
}

#[doc(alias = "cvtx")]
pub fn CVTX(cpu: &mut Cpu) {
    cpu.mem[0x00f0] = 0x00;
    cpu.set_a(cpu.mem[0x0003]);
    if (cpu.reg.a as i8) < 0 {
        loop {
            cpu.mem[0x00f0] = (cpu.mem[0x00f0]).wrapping_sub(0x24);
            let _lo = (cpu.mem[0x0001] as u16) + (0xfc as u16);
            cpu.mem[0x0001] = _lo as u8;
            let _hi = (cpu.mem[0x0003] as u16) + (0x00 as u16) + (_lo >> 8);
            cpu.mem[0x0003] = _hi as u8;
            cpu.flags.c = (_hi >> 8) != 0;
            cpu.set_a(_hi as u8);
            if cpu.flags.z {
                break;
            }
        }
        if cpu.flags.z {
            cpu.set_y(cpu.mem[0x0001]);
            cpu.set_a(cpu.mem[(sym::ByteTable + cpu.reg.y as usize) & 0xffff]);
            cpu.flags.c = false;
            let _r = (cpu.reg.a as u16) + cpu.mem[0x00f0] as u16 + (cpu.flags.c as u16);
            cpu.flags.c = (_r >> 8) != 0;
            cpu.set_a(_r as u8);
            cpu.mem[sym::XCO] = cpu.reg.a;
            cpu.set_a(cpu.mem[(sym::OffsetTable + cpu.reg.y as usize) & 0xffff]);
            cpu.mem[sym::OFFSET] = cpu.reg.a;
            return;
        }
        return;
    }
    if cpu.flags.z {
    } else {
        loop {
            cpu.mem[0x00f0] = (cpu.mem[0x00f0]).wrapping_add(0x24);
            let _lo = (cpu.mem[0x0001] as u16) + (!0xfc_u8 as u16) + 1;
            cpu.mem[0x0001] = _lo as u8;
            let _hi = (cpu.mem[0x0003] as u16) + (!0x00_u8 as u16) + (_lo >> 8);
            cpu.mem[0x0003] = _hi as u8;
            cpu.flags.c = (_hi >> 8) != 0;
            cpu.set_a(_hi as u8);
            if cpu.flags.z {
                break;
            }
        }
    }
    cpu.set_y(cpu.mem[0x0001]);
    cpu.set_a(cpu.mem[(sym::ByteTable + cpu.reg.y as usize) & 0xffff]);
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + cpu.mem[0x00f0] as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.mem[sym::XCO] = cpu.reg.a;
    cpu.set_a(cpu.mem[(sym::OffsetTable + cpu.reg.y as usize) & 0xffff]);
    cpu.mem[sym::OFFSET] = cpu.reg.a;
    return;
}

#[doc(alias = "zerolsts")]
pub fn ZEROLSTS(cpu: &mut Cpu) {
    cpu.set_a(0x00);
    cpu.mem[sym::genCLS] = cpu.reg.a;
    cpu.mem[sym::wipeX] = cpu.reg.a;
    cpu.mem[sym::bgX] = cpu.reg.a;
    cpu.mem[sym::midX] = cpu.reg.a;
    cpu.mem[sym::objX] = cpu.reg.a;
    cpu.mem[sym::fgX] = cpu.reg.a;
    cpu.mem[sym::msgX] = cpu.reg.a;
    return;
}

#[doc(alias = "zeropeels")]
pub fn ZEROPEELS(cpu: &mut Cpu) {
    cpu.set_a(0x00);
    cpu.mem[sym::peelX] = cpu.reg.a;
    cpu.mem[0xb143] = cpu.reg.a;
    return;
}

#[doc(alias = "zeropeel")]
pub fn ZEROPEEL(cpu: &mut Cpu) {
    cpu.set_a(0x00);
    cpu.set_x(cpu.mem[sym::PAGE]);
    if cpu.reg.x == 0x00 {
        cpu.mem[sym::peelX] = cpu.reg.a;
        cpu.mem[sym::PEELBUF] = 0x00;
        cpu.set_a(0xd0);
        cpu.mem[sym::PEELBUF + 1] = cpu.reg.a;
        return;
    }
    cpu.mem[0xb143] = cpu.reg.a;
    cpu.mem[sym::PEELBUF] = 0x00;
    cpu.set_a(0xd6);
    cpu.mem[sym::PEELBUF + 1] = cpu.reg.a;
    return;
}

#[doc(alias = "getselect")]
pub fn GETSELECT(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::joyon]);
    if cpu.reg.a == 0x00 {
        if cpu.flags.z {
            getkbd(cpu);
            return;
        }
        cpu.set_a(cpu.mem[sym::joyon]);
        if cpu.reg.a != 0x00 {
            getkbd(cpu);
            return;
        }
        if cpu.flags.z {
        }
    }
    cpu.mem[sym::JSTKX] = cpu.mem[sym::joyX];
    cpu.mem[sym::JSTKY] = cpu.mem[sym::joyY];
    cpu.set_a(cpu.mem[sym::BTN1]);
    cpu.set_x(cpu.mem[sym::ManCtrl]);
    if (cpu.reg.x as i8) >= 0 {
        cpu.set_a(cpu.reg.a | cpu.mem[sym::BTN0]);
    }
    cpu.mem[sym::btn] = cpu.reg.a;
    return;
}

#[doc(alias = "getdesel")]
pub fn GETDESEL(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::joyon]);
    if cpu.reg.a != 0x00 {
        getkbd(cpu);
        return;
    }
    if cpu.flags.z {
    }
    cpu.mem[sym::JSTKX] = cpu.mem[sym::joyX];
    cpu.mem[sym::JSTKY] = cpu.mem[sym::joyY];
    cpu.set_a(cpu.mem[sym::BTN1]);
    cpu.set_x(cpu.mem[sym::ManCtrl]);
    if (cpu.reg.x as i8) >= 0 {
        cpu.set_a(cpu.reg.a | cpu.mem[sym::BTN0]);
    }
    cpu.mem[sym::btn] = cpu.reg.a;
    return;
}

pub fn getjoy(cpu: &mut Cpu) {
    cpu.mem[sym::JSTKX] = cpu.mem[sym::joyX];
    cpu.mem[sym::JSTKY] = cpu.mem[sym::joyY];
    cpu.set_a(cpu.mem[sym::BTN1]);
    cpu.set_x(cpu.mem[sym::ManCtrl]);
    if (cpu.reg.x as i8) >= 0 {
        cpu.set_a(cpu.reg.a | cpu.mem[sym::BTN0]);
    }
    cpu.mem[sym::btn] = cpu.reg.a;
    return;
}

pub fn getkbd(cpu: &mut Cpu) {
    cpu.mem[sym::JSTKX] = cpu.mem[sym::kbdX];
    cpu.mem[sym::JSTKY] = cpu.mem[sym::kbdY];
    cpu.set_a(cpu.mem[sym::BTN0]);
    cpu.set_x(cpu.mem[sym::ManCtrl]);
    if (cpu.reg.x as i8) >= 0 {
        cpu.set_a(cpu.reg.a | cpu.mem[sym::BTN1]);
    }
    cpu.mem[sym::btn] = cpu.reg.a;
    return;
}

#[doc(alias = "controller")]
pub fn CONTROLLER(cpu: &mut Cpu) {
    JREAD(cpu);
    BREAD(cpu);
    return;
}

pub fn JREAD(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::joyon]);
    if cpu.reg.a == 0x00 {
        return;
    }
    PREAD(cpu);
    cpu.set_x(0x00);
    cvtpdl(cpu);
    cpu.set_x(cpu.reg.x.wrapping_add(1));
    cvtpdl(cpu);
    cpu.set_a(cpu.mem[sym::jvert]);
    if cpu.reg.a != 0x00 {
        cpu.set_a(0x00);
        cpu.flags.c = true;
        let _r = (cpu.reg.a as u16) + (!cpu.mem[sym::joyY]) as u16 + (cpu.flags.c as u16);
        cpu.flags.c = (_r >> 8) != 0;
        cpu.set_a(_r as u8);
        cpu.mem[sym::joyY] = cpu.reg.a;
    }
    cpu.set_a(cpu.mem[sym::jhoriz]);
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.set_a(0x00);
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!cpu.mem[sym::joyX]) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.mem[sym::joyX] = cpu.reg.a;
    return;
}

pub fn BREAD(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::jbtns]);
    if cpu.reg.a != 0x00 {
        cpu.set_x(cpu.mem[0xc062]);
        cpu.set_a(cpu.mem[0xc061]);
    } else {
        cpu.set_a(cpu.mem[0xc061]);
        cpu.set_x(cpu.mem[0xc062]);
    }
    cpu.mem[sym::BTN0] = cpu.reg.a;
    cpu.mem[sym::BTN1] = cpu.reg.x;
    return;
}

pub fn cvtpdl(cpu: &mut Cpu) {
    'b5: {
        cpu.set_a(cpu.mem[(sym::joyX + cpu.reg.x as usize) & 0xffff]);
        let _o: u8 = cpu.mem[(sym::jthres1x + cpu.reg.x as usize) & 0xffff];
        cpu.flags.c = cpu.reg.a >= _o;
        cpu.flags.z = cpu.reg.a == _o;
        cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
        if cpu.reg.a < cpu.mem[(sym::jthres1x + cpu.reg.x as usize) & 0xffff] {
            cpu.set_a(0xff);
            if cpu.reg.a != 0x00 {
                break 'b5;
            }
        }
        let _o: u8 = cpu.mem[(sym::jthres2x + cpu.reg.x as usize) & 0xffff];
        cpu.flags.c = cpu.reg.a >= _o;
        cpu.flags.z = cpu.reg.a == _o;
        cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
        if cpu.reg.a < cpu.mem[(sym::jthres2x + cpu.reg.x as usize) & 0xffff] {
            cpu.set_a(0x00);
            if cpu.reg.a == 0x00 {
                break 'b5;
            }
        }
        cpu.set_a(0x01);
    }
    cpu.mem[(sym::joyX + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
    return;
}

#[doc(alias = "pread")]
pub fn PREAD(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_a(0x00);
                cpu.mem[sym::joyX] = cpu.reg.a;
                cpu.mem[sym::joyY] = cpu.reg.a;
                cpu.set_a(cpu.mem[0xc070]);
                pc = 1;
            }
            1 => {
                cpu.set_x(0x01);
                pc = 2;
            }
            2 => {
                cpu.set_a(cpu.mem[(0xc064 + cpu.reg.x as usize) & 0xffff]);
                if (cpu.reg.a as i8) >= 0 {
                    pc = 8;
                } else {
                    pc = 3;
                }
            }
            3 => {
                let _v = cpu.mem[(sym::joyX + cpu.reg.x as usize) & 0xffff].wrapping_add(1);
                cpu.mem[(sym::joyX + cpu.reg.x as usize) & 0xffff] = _v;
                cpu.set_nz(_v);
                pc = 4;
            }
            4 => {
                cpu.set_x(cpu.reg.x.wrapping_sub(1));
                if (cpu.reg.x as i8) >= 0 {
                    pc = 2;
                } else {
                    pc = 5;
                }
            }
            5 => {
                cpu.set_a(cpu.mem[0xc064]);
                cpu.set_a(cpu.reg.a | cpu.mem[0xc065]);
                if (cpu.reg.a as i8) >= 0 {
                    pc = 12;
                } else {
                    pc = 6;
                }
            }
            6 => {
                cpu.set_a(cpu.mem[sym::joyX]);
                cpu.set_a(cpu.reg.a | cpu.mem[sym::joyY]);
                if (cpu.reg.a as i8) >= 0 {
                    pc = 1;
                } else {
                    pc = 7;
                }
            }
            7 => {
                return;
            }
            8 => {
                // raw: nop                              ; GRAFIX.S:1222
                if !cpu.flags.n {
                    pc = 4;
                } else {
                    pc = 9;
                }
            }
            9 => {
                NORMSPEED(cpu);
                cpu.set_a(0xff);
                cpu.mem[sym::joyon] = cpu.reg.a;
                cpu.set_a(0x00);
                cpu.mem[sym::jvert] = cpu.reg.a;
                cpu.mem[sym::jhoriz] = cpu.reg.a;
                cpu.mem[sym::jbtns] = cpu.reg.a;
                PREAD(cpu);
                cpu.set_a(cpu.mem[sym::joyX]);
                cpu.set_a(cpu.reg.a | cpu.mem[sym::joyY]);
                if (cpu.reg.a as i8) < 0 {
                    pc = 11;
                } else {
                    pc = 10;
                }
            }
            10 => {
                cpu.set_a(cpu.mem[sym::joyX]);
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!0x0a_u8) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                cpu.mem[sym::jthres1x] = cpu.reg.a;
                cpu.set_a(cpu.mem[sym::joyX]);
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + (0x0a) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                cpu.mem[sym::jthres2x] = cpu.reg.a;
                cpu.set_a(cpu.mem[sym::joyY]);
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!0x0f_u8) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                cpu.mem[sym::jthres1y] = cpu.reg.a;
                cpu.set_a(cpu.mem[sym::joyY]);
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + (0x0f) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                cpu.mem[sym::jthres2y] = cpu.reg.a;
                return;
            }
            11 => {
                cpu.set_a(0x00);
                cpu.mem[sym::joyon] = cpu.reg.a;
                pc = 12;
            }
            12 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

#[doc(alias = "setcenter")]
pub fn SETCENTER(cpu: &mut Cpu) {
    NORMSPEED(cpu);
    cpu.mem[sym::joyon] = 0xff;
    cpu.set_a(0x00);
    cpu.mem[sym::jvert] = cpu.reg.a;
    cpu.mem[sym::jhoriz] = cpu.reg.a;
    cpu.mem[sym::jbtns] = cpu.reg.a;
    PREAD(cpu);
    cpu.set_a(cpu.mem[sym::joyX]);
    cpu.set_a(cpu.reg.a | cpu.mem[sym::joyY]);
    if (cpu.reg.a as i8) < 0 {
        cpu.set_a(0x00);
        cpu.mem[sym::joyon] = cpu.reg.a;
        return;
    }
    cpu.mem[sym::jthres1x] = (cpu.mem[sym::joyX]).wrapping_sub(0x0a);
    cpu.mem[sym::jthres2x] = (cpu.mem[sym::joyX]).wrapping_add(0x0a);
    cpu.mem[sym::jthres1y] = (cpu.mem[sym::joyY]).wrapping_sub(0x0f);
    cpu.set_a(cpu.mem[sym::joyY]);
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x0f) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.mem[sym::jthres2y] = cpu.reg.a;
    return;
}

pub fn MOVEMEM(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.mem[0x00f1] = cpu.reg.a;
                cpu.mem[0x00f3] = cpu.reg.x;
                cpu.mem[0x00f5] = cpu.reg.y;
                cpu.set_y(0x00);
                cpu.mem[0x00f0] = cpu.reg.y;
                cpu.mem[0x00f2] = cpu.reg.y;
                cpu.mem[0x00f4] = cpu.reg.y;
                pc = 1;
            }
            1 => {
                cpu.set_a(cpu.mem[((cpu.mem[0x00f2] as usize | (cpu.mem[0x00f3] as usize) << 8) + cpu.reg.y as usize) & 0xffff]);
                cpu.mem[((cpu.mem[0x00f0] as usize | (cpu.mem[0x00f1] as usize) << 8) + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                if cpu.reg.y != 0x00 {
                    pc = 1;
                } else {
                    pc = 2;
                }
            }
            2 => {
                let _v = cpu.mem[0x00f3].wrapping_add(1);
                cpu.mem[0x00f3] = _v;
                cpu.set_nz(_v);
                let _v = cpu.mem[0x00f1].wrapping_add(1);
                cpu.mem[0x00f1] = _v;
                cpu.set_nz(_v);
                cpu.set_a(cpu.mem[0x00f3]);
                let _o: u8 = cpu.mem[0x00f5];
                cpu.flags.c = cpu.reg.a >= _o;
                cpu.flags.z = cpu.reg.a == _o;
                cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
                if cpu.reg.a != cpu.mem[0x00f5] {
                    pc = 1;
                } else {
                    pc = 3;
                }
            }
            3 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

#[doc(alias = "gtone")]
pub fn GTONE(cpu: &mut Cpu) {
    cpu.set_y(0x0f);
    cpu.set_x(0x00);
    cpu.set_a(0x32);
    tone(cpu);
    return;
}

#[doc(alias = "whoop")]
pub fn WHOOP(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.set_y(0x00);
                pc = 1;
            }
            1 => {
                cpu.set_a(cpu.reg.y);
                let _o: u8 = cpu.mem[0xc030];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                pc = 2;
            }
            2 => {
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!0x01_u8) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                if cpu.reg.a != 0x00 {
                    pc = 2;
                } else {
                    pc = 3;
                }
            }
            3 => {
                cpu.set_y(cpu.reg.y.wrapping_sub(1));
                if cpu.reg.y != 0x00 {
                    pc = 1;
                } else {
                    pc = 4;
                }
            }
            4 => {
                return;
            }
            _ => unreachable!(),
        }
    }
}

pub fn tone(cpu: &mut Cpu) {
    let mut pc: u32 = 0;
    loop {
        match pc {
            0 => {
                cpu.local.insert((":pitch", 0), cpu.reg.y);
                cpu.local.insert((":pitch", 1), cpu.reg.x);
                pc = 1;
            }
            1 => {
                let _o: u8 = cpu.mem[0xc030];
                cpu.flags.z = (cpu.reg.a & _o) == 0;
                cpu.flags.n = (_o >> 7) != 0;
                cpu.set_x(0x00);
                pc = 2;
            }
            2 => {
                cpu.set_y(0x00);
                pc = 3;
            }
            3 => {
                cpu.set_y(cpu.reg.y.wrapping_add(1));
                let _o: u8 = cpu.local.get(&(":pitch", 0)).copied().unwrap_or(0);
                cpu.flags.c = cpu.reg.y >= _o;
                cpu.flags.z = cpu.reg.y == _o;
                cpu.flags.n = (cpu.reg.y.wrapping_sub(_o) >> 7) != 0;
                if !cpu.flags.c {
                    pc = 3;
                } else {
                    pc = 4;
                }
            }
            4 => {
                cpu.set_x(cpu.reg.x.wrapping_add(1));
                let _o: u8 = cpu.local.get(&(":pitch", 1)).copied().unwrap_or(0);
                cpu.flags.c = cpu.reg.x >= _o;
                cpu.flags.z = cpu.reg.x == _o;
                cpu.flags.n = (cpu.reg.x.wrapping_sub(_o) >> 7) != 0;
                if !cpu.flags.c {
                    pc = 2;
                } else {
                    pc = 5;
                }
            }
            5 => {
                cpu.flags.c = true;
                let _r = (cpu.reg.a as u16) + (!0x01_u8) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                if cpu.reg.a != 0x00 {
                    pc = 1;
                } else {
                    pc = 6;
                }
            }
            6 => {
                return;
            }
            7 => {
                cpu.set_a(cpu.mem[sym::PAGE]);
                cpu.flags.c = false;
                let _r = (cpu.reg.a as u16) + (0x20) as u16 + (cpu.flags.c as u16);
                cpu.flags.c = (_r >> 8) != 0;
                cpu.set_a(_r as u8);
                cpu.mem[sym::IMAGE + 1] = cpu.reg.a;
                cpu.set_a(cpu.reg.a ^ 0x60);
                cpu.mem[sym::IMAGE] = cpu.reg.a;
                COPY2000(cpu);
                return;
            }
            _ => unreachable!(),
        }
    }
}

#[doc(alias = "copyscrn")]
pub fn COPYSCRN(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::PAGE]);
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x20) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.mem[sym::IMAGE + 1] = cpu.reg.a;
    cpu.set_a(cpu.reg.a ^ 0x60);
    cpu.mem[sym::IMAGE] = cpu.reg.a;
    COPY2000(cpu);
    return;
}

#[doc(alias = "rnd")]
pub fn RND(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::RNDseed]);
    cpu.flags.c = (cpu.reg.a >> 7) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shl(1));
    cpu.flags.c = (cpu.reg.a >> 7) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shl(1));
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + cpu.mem[sym::RNDseed] as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.flags.c = false;
    let _r = (cpu.reg.a as u16) + (0x17) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.mem[sym::RNDseed] = cpu.reg.a;
    return;
}

#[doc(alias = "loadlevel")]
pub fn LOADLEVEL(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::LOADLEVEL(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "attractmode")]
pub fn ATTRACTMODE(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::ATTRACTMODE(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "cutprincess")]
pub fn CUTPRINCESS(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::CUTPRINCESS(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "reload")]
pub fn RELOAD(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::ext::_reload(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "loadstage2")]
pub fn LOADSTAGE2(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::LoadStage2(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "savegame")]
pub fn SAVEGAME(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::SAVEGAME(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "loadgame")]
pub fn LOADGAME(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::LOADGAME(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "dostartgame")]
pub fn DOSTARTGAME(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::ext::_dostartgame(cpu);
    return;
}

#[doc(alias = "epilog")]
pub fn EPILOG(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::EPILOG(cpu);
    return;
}

#[doc(alias = "loadaltset")]
pub fn LOADALTSET(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::master::LOADALTSET(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "screendump")]
pub fn SCREENDUMP(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::ext::_screendump(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "SAVELEVELG")]
#[doc(alias = "READDIR")]
#[doc(alias = "WRITEDIR")]
#[doc(alias = "GOBUILD")]
#[doc(alias = "GOGAME")]
#[doc(alias = "EDREBOOT")]
#[doc(alias = "savelevel")]
pub fn SAVELEVEL(cpu: &mut Cpu) {
    return;
}

pub fn CLS(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::cls(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn LAY(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::lay(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn FASTLAY(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::fastlay(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn LAYRSAVE(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::layrsave(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    posthr(cpu);
    return;
}

pub fn LRCLS(cpu: &mut Cpu) {
    cpu.mem[sym::scrncolor] = cpu.reg.a;
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::lrcls(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn FASTMASK(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::fastmask(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn FASTBLACK(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::fastblack(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn PEEL(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::peel(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn GETWIDTH(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::getwidth(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "copy2000")]
pub fn COPY2000(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::copyscrnMM(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "copy2000am")]
pub fn COPY2000AM(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::copyscrnAM(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "copy2000ma")]
pub fn COPY2000MA(cpu: &mut Cpu) {
    prehr(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::copyscrnMA(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "setfastaux")]
pub fn SETFASTAUX(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::SETFASTAUX(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "setfastmain")]
pub fn SETFASTMAIN(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::hires::SETFASTMAIN(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "inverty")]
pub fn INVERTY(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    crate::unpack::INVERTY(cpu);
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

#[doc(alias = "minit")]
pub fn MINIT(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    CALLMINIT(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "mplay")]
pub fn MPLAY(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    CALLMPLAY(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "xminit")]
pub fn XMINIT(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    MINIT(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    return;
}

#[doc(alias = "xmplay")]
pub fn XMPLAY(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    MPLAY(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    return;
}

#[doc(alias = "xtitle")]
pub fn XTITLE(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    crate::ext::titlescreen(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    return;
}

#[doc(alias = "xplaycut")]
pub fn XPLAYCUT(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    crate::subs::PLAYCUT(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    return;
}

#[doc(alias = "xmovemusic")]
pub fn XMOVEMUSIC(cpu: &mut Cpu) {
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    crate::misc::MOVEMUSIC(cpu);
    cpu.mem[sym::ALTZPoff] = cpu.reg.a;
    return;
}

pub fn prehr(cpu: &mut Cpu) {
    cpu.reg.x = 0x17;
    loop {
        cpu.mem[sym::ALTZPon] = cpu.reg.a;
        cpu.set_a(cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff]);
        cpu.mem[sym::ALTZPoff] = cpu.reg.a;
        cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    cpu.mem[sym::ALTZPon] = cpu.reg.a;
    return;
}

pub fn posthr(cpu: &mut Cpu) {
    cpu.reg.x = 0x17;
    loop {
        cpu.mem[sym::ALTZPoff] = cpu.reg.a;
        cpu.set_a(cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff]);
        cpu.mem[sym::ALTZPon] = cpu.reg.a;
        cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    return;
}

#[doc(alias = "saveblue")]
pub fn SAVEBLUE(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    cpu.set_a(0xd7);
    cpu.set_x(0xb7);
    cpu.set_y(0xc0);
    crate::boot::movemem(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "savebinfo")]
pub fn SAVEBINFO(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    cpu.set_a(0xd0);
    cpu.set_x(0xa6);
    cpu.set_y(0xac);
    crate::boot::movemem(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "reloadblue")]
pub fn RELOADBLUE(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    cpu.set_a(0xb7);
    cpu.set_x(0xd7);
    cpu.set_y(0xe0);
    crate::boot::movemem(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "reloadbinfo")]
pub fn RELOADBINFO(cpu: &mut Cpu) {
    _5dbank1in(cpu);
    cpu.set_a(0xa6);
    cpu.set_x(0xd0);
    cpu.set_y(0xd6);
    crate::boot::movemem(cpu);
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK2];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}

#[doc(alias = "gr")]
pub fn GR(cpu: &mut Cpu) {
    GTONE(cpu);
    return;
}

#[doc(alias = "calcblue")]
pub fn CALCBLUE(cpu: &mut Cpu) {
    if cpu.reg.a == 0x00 {
        calcmenu(cpu);
        return;
    }
    cpu.flags.c = true;
    let _r = (cpu.reg.a as u16) + (!0x01_u8) as u16 + (cpu.flags.c as u16);
    cpu.flags.c = (_r >> 8) != 0;
    cpu.set_a(_r as u8);
    cpu.flags.c = (cpu.reg.a >> 7) != 0;
    cpu.set_a(cpu.reg.a.wrapping_shl(1));
    cpu.set_x(cpu.reg.a);
    let _lo = (cpu.mem[(sym::Mult30 + cpu.reg.x as usize) & 0xffff] as u16) + (0x00 as u16);
    cpu.mem[sym::BlueType] = _lo as u8;
    let _hi = (cpu.mem[(sym::Mult30 + 1 + cpu.reg.x as usize) & 0xffff] as u16) + (0xb7 as u16) + (_lo >> 8);
    cpu.mem[sym::BlueType + 1] = _hi as u8;
    cpu.flags.c = (_hi >> 8) != 0;
    cpu.set_a(_hi as u8);
    let _lo = (cpu.mem[sym::BlueType] as u16) + (0xd0 as u16);
    cpu.mem[sym::BlueSpec] = _lo as u8;
    let _hi = (cpu.mem[sym::BlueType + 1] as u16) + (0x02 as u16) + (_lo >> 8);
    cpu.mem[sym::BlueSpec + 1] = _hi as u8;
    cpu.flags.c = (_hi >> 8) != 0;
    cpu.set_a(_hi as u8);
    return;
}

pub fn calcmenu(cpu: &mut Cpu) {
    cpu.mem[sym::BlueType] = 0x0f;
    cpu.mem[sym::BlueType + 1] = 0x96;
    cpu.mem[sym::BlueSpec] = 0x2d;
    cpu.set_a(0x96);
    cpu.mem[sym::BlueSpec + 1] = cpu.reg.a;
    return;
}

#[doc(alias = "zerored")]
pub fn ZERORED(cpu: &mut Cpu) {
    cpu.set_a(0x00);
    cpu.reg.y = 0x1d;
    loop {
        cpu.mem[(sym::redbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::fredbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::floorbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::halfbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::wipebuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::movebuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.mem[(sym::objbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.y = cpu.reg.y.wrapping_sub(0x01);
        if !((cpu.reg.y as i8) >= 0) {
            break;
        }
    }
    cpu.reg.y = 0x09;
    loop {
        cpu.mem[(sym::topbuf + cpu.reg.y as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.y = cpu.reg.y.wrapping_sub(0x01);
        if !((cpu.reg.y as i8) >= 0) {
            break;
        }
    }
    return;
}

pub fn switchzp(cpu: &mut Cpu) {
    cpu.reg.x = 0x1f;
    loop {
        cpu.set_y(cpu.mem[(sym::savezp + cpu.reg.x as usize) & 0xffff]);
        cpu.mem[(sym::savezp + cpu.reg.x as usize) & 0xffff] = cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff];
        cpu.set_a(cpu.reg.y);
        cpu.mem[(0x0000 + cpu.reg.x as usize) & 0xffff] = cpu.reg.a;
        cpu.reg.x = cpu.reg.x.wrapping_sub(0x01);
        if !((cpu.reg.x as i8) >= 0) {
            break;
        }
    }
    return;
}

pub fn CALLMINIT(cpu: &mut Cpu) {
    let tmp0 = cpu.reg.a;
    switchzp(cpu);
    cpu.reg.a = tmp0;
    crate::ext::_minit(cpu);
    switchzp(cpu);
    return;
}

pub fn CALLMPLAY(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::soundon]);
    cpu.set_a(cpu.reg.a & cpu.mem[sym::musicon]);
    if cpu.reg.a == 0x00 {
        cpu.set_a(0x00);
        return;
    }
    switchzp(cpu);
    crate::ext::_mplay(cpu);
    let tmp0 = cpu.reg.a;
    switchzp(cpu);
    cpu.reg.a = tmp0;
    return;
}

#[doc(alias = "musickeys")]
pub fn MUSICKEYS(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[0xc000]);
    cpu.mem[sym::keypress] = cpu.reg.a;
    if !cpu.flags.n {
        cpu.set_a(cpu.mem[0xc061]);
        cpu.set_a(cpu.reg.a | cpu.mem[0xc062]);
        if (cpu.reg.a as i8) >= 0 {
            cpu.set_a(cpu.mem[sym::keypress]);
            return;
        }
        cpu.set_a(0xff);
        return;
    }
    cpu.mem[0xc010] = cpu.reg.a;
    let _o: u8 = 0x9b;
    cpu.flags.c = cpu.reg.a >= _o;
    cpu.flags.z = cpu.reg.a == _o;
    cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
    if cpu.reg.a != 0x9b {
        let _o: u8 = 0x13;
        cpu.flags.c = cpu.reg.a >= _o;
        cpu.flags.z = cpu.reg.a == _o;
        cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
        if cpu.reg.a != 0x13 {
            let _o: u8 = 0x0e;
            cpu.flags.c = cpu.reg.a >= _o;
            cpu.flags.z = cpu.reg.a == _o;
            cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
            if cpu.reg.a != 0x0e {
                cpu.set_a(cpu.mem[0xc061]);
                cpu.set_a(cpu.reg.a | cpu.mem[0xc062]);
                if (cpu.reg.a as i8) >= 0 {
                    cpu.set_a(cpu.mem[sym::keypress]);
                    return;
                }
                cpu.set_a(0xff);
                return;
            }
            cpu.set_a(cpu.mem[sym::musicon]);
            cpu.set_a(cpu.reg.a ^ 0x01);
            cpu.mem[sym::musicon] = cpu.reg.a;
            if cpu.flags.z {
            } else {
                GTONE(cpu);
            }
            cpu.set_a(0x00);
            return;
        }
        cpu.set_a(cpu.mem[sym::soundon]);
        cpu.set_a(cpu.reg.a ^ 0x01);
        cpu.mem[sym::soundon] = cpu.reg.a;
        if cpu.flags.z {
        } else {
            GTONE(cpu);
        }
        cpu.set_a(0x00);
        return;
    }
    loop {
        cpu.set_a(cpu.mem[0xc000]);
        cpu.mem[sym::keypress] = cpu.reg.a;
        if cpu.flags.n {
            break;
        }
    }
    cpu.mem[0xc010] = cpu.reg.a;
    let _o: u8 = 0x9b;
    cpu.flags.c = cpu.reg.a >= _o;
    cpu.flags.z = cpu.reg.a == _o;
    cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
    if cpu.reg.a != 0x9b {
        let _o: u8 = 0x13;
        cpu.flags.c = cpu.reg.a >= _o;
        cpu.flags.z = cpu.reg.a == _o;
        cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
        if cpu.reg.a != 0x13 {
            let _o: u8 = 0x0e;
            cpu.flags.c = cpu.reg.a >= _o;
            cpu.flags.z = cpu.reg.a == _o;
            cpu.flags.n = (cpu.reg.a.wrapping_sub(_o) >> 7) != 0;
            if cpu.reg.a != 0x0e {
                cpu.set_a(cpu.mem[0xc061]);
                cpu.set_a(cpu.reg.a | cpu.mem[0xc062]);
                if (cpu.reg.a as i8) >= 0 {
                    cpu.set_a(cpu.mem[sym::keypress]);
                    return;
                }
                cpu.set_a(0xff);
                return;
            }
            cpu.set_a(cpu.mem[sym::musicon]);
            cpu.set_a(cpu.reg.a ^ 0x01);
            cpu.mem[sym::musicon] = cpu.reg.a;
            if cpu.flags.z {
            } else {
                GTONE(cpu);
            }
            cpu.set_a(0x00);
            return;
        }
        cpu.set_a(cpu.mem[sym::soundon]);
        cpu.set_a(cpu.reg.a ^ 0x01);
        cpu.mem[sym::soundon] = cpu.reg.a;
        if cpu.flags.z {
        } else {
            GTONE(cpu);
        }
        cpu.set_a(0x00);
        return;
    }
    cpu.set_a(cpu.reg.a & 0x7f);
    return;
}

#[doc(alias = ":loop1")]
#[doc(alias = "vblank")]
pub fn VBLANK(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[0xc019]);
    if (cpu.reg.a as i8) >= 0 {
        VBLANK(cpu);
        return;
    }
    loop {
        cpu.set_a(cpu.mem[0xc019]);
        if !((cpu.reg.a as i8) < 0) {
            break;
        }
    }
    return;
}

pub fn VBLANKIIc(cpu: &mut Cpu) {
    cpu.flags.i = false;
    loop {
        let _o: u8 = cpu.mem[sym::vblflag];
        cpu.flags.z = (cpu.reg.a & _o) == 0;
        cpu.flags.n = (_o >> 7) != 0;
        if cpu.flags.n {
            break;
        }
    }
    cpu.flags.c = (cpu.mem[sym::vblflag] & 1) != 0;
    cpu.mem[sym::vblflag] = cpu.mem[sym::vblflag].wrapping_shr(1);
    cpu.set_nz(cpu.mem[sym::vblflag]);
    loop {
        let _o: u8 = cpu.mem[sym::vblflag];
        cpu.flags.z = (cpu.reg.a & _o) == 0;
        cpu.flags.n = (_o >> 7) != 0;
        if cpu.flags.n {
            break;
        }
    }
    cpu.flags.c = (cpu.mem[sym::vblflag] & 1) != 0;
    cpu.mem[sym::vblflag] = cpu.mem[sym::vblflag].wrapping_shr(1);
    cpu.set_nz(cpu.mem[sym::vblflag]);
    cpu.flags.i = true;
    return;
}

#[doc(alias = "vbli")]
pub fn VBLI(cpu: &mut Cpu) {
    let _o: u8 = cpu.mem[0xc019];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    cpu.mem[0xc079] = cpu.reg.a;
    cpu.mem[0xc05b] = cpu.reg.a;
    cpu.mem[0xc078] = cpu.reg.a;
    cpu.flags.c = true;
    let _c = cpu.mem[sym::vblflag] & 1;
    cpu.mem[sym::vblflag] = cpu.mem[sym::vblflag].wrapping_shr(1) | ((cpu.flags.c as u8) << 7);
    cpu.flags.c = _c != 0;
    cpu.set_nz(cpu.mem[sym::vblflag]);
    return;
}

pub fn InitVBLANK(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[0xfbc0]);
    if cpu.reg.a != 0x00 {
        return;
    }
    cpu.mem[sym::RAMWRTaux] = cpu.reg.a;
    cpu.mem[sym::VBLvect + 1] = 0xfc;
    cpu.set_a(0x01);
    cpu.mem[sym::VBLvect + 2] = cpu.reg.a;
    cpu.flags.i = true;
    cpu.mem[0xc079] = cpu.reg.a;
    cpu.mem[0xc05b] = cpu.reg.a;
    cpu.mem[0xc078] = cpu.reg.a;
    return;
}

#[doc(alias = "fastspeed")]
pub fn FASTSPEED(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::IIGS]);
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.set_a(0x80);
    cpu.flags.z = (cpu.reg.a & cpu.mem[0xc036]) == 0;
    cpu.mem[0xc036] |= cpu.reg.a;
    return;
}

#[doc(alias = "normspeed")]
pub fn NORMSPEED(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::IIGS]);
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.set_a(cpu.mem[0xc034]);
    cpu.set_a(cpu.reg.a & 0xf0);
    cpu.mem[0xc034] = cpu.reg.a;
    cpu.mem[0xc022] = 0xf0;
    cpu.set_a(0x80);
    cpu.flags.z = (cpu.reg.a & cpu.mem[0xc036]) == 0;
    cpu.mem[0xc036] &= !cpu.reg.a;
    return;
}

pub fn getparam(cpu: &mut Cpu) {
    cpu.set_a(cpu.mem[sym::IIGS]);
    if cpu.reg.a == 0x00 {
        return;
    }
    cpu.flags.c = false;
    // 65816 (IIgs-only, not modeled): xce  ; GRAFIX.S:2093
    // 65816 (IIgs-only, not modeled): rep $30  ; GRAFIX.S:2094
    cpu.stack.push(cpu.reg.a);
    cpu.stack.push(cpu.reg.y);
    cpu.set_x(0x03);
    // 65816 (IIgs-only, not modeled): jsl $e10000  ; GRAFIX.S:2098
    let _v = cpu.stack.pop().expect("pla on empty stack");
    cpu.set_a(_v);
    cpu.flags.c = true;
    // 65816 (IIgs-only, not modeled): xce  ; GRAFIX.S:2101
    cpu.set_y(cpu.reg.a);
    return;
}

pub fn setparam(cpu: &mut Cpu) {
    cpu.flags.c = false;
    // 65816 (IIgs-only, not modeled): xce  ; GRAFIX.S:2114
    // 65816 (IIgs-only, not modeled): rep $30  ; GRAFIX.S:2115
    cpu.set_a(cpu.reg.a & 0xff);
    cpu.stack.push(cpu.reg.a);
    cpu.stack.push(cpu.reg.y);
    cpu.set_x(0x03);
    // 65816 (IIgs-only, not modeled): jsl $e10000  ; GRAFIX.S:2120
    cpu.flags.c = true;
    // 65816 (IIgs-only, not modeled): xce  ; GRAFIX.S:2122
    return;
}

pub fn _3asetaddl(cpu: &mut Cpu) {
    cpu.mem[sym::OFFSET] = cpu.mem[(sym::midOFF + cpu.reg.x as usize) & 0xffff];
    cpu.mem[sym::LEFTCUT] = cpu.mem[(sym::midCL + cpu.reg.x as usize) & 0xffff];
    cpu.mem[sym::RIGHTCUT] = cpu.mem[(sym::midCR + cpu.reg.x as usize) & 0xffff];
    cpu.mem[sym::TOPCUT] = cpu.mem[(sym::midCU + cpu.reg.x as usize) & 0xffff];
    cpu.set_a(cpu.mem[(sym::midCD + cpu.reg.x as usize) & 0xffff]);
    cpu.mem[sym::BOTCUT] = cpu.reg.a;
    return;
}

pub fn _5dbank1in(cpu: &mut Cpu) {
    let _o: u8 = cpu.mem[sym::RWBANK1];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    let _o: u8 = cpu.mem[sym::RWBANK1];
    cpu.flags.z = (cpu.reg.a & _o) == 0;
    cpu.flags.n = (_o >> 7) != 0;
    return;
}
