// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4: module + routine scaffolding with leaf-expression,
// control-flow, data-movement, carry-arithmetic, `(ptr),y` indirect,
// cmp/bit flag, 16-bit (`Wide16`), dispatch-fallback, stack, and SMC
// operand-patch lowering.
//
// State is decomposed into `Cpu { reg, flags, mem, stack, smc }`:
// registers `self.reg.{a,x,y}: u8`, flags `self.flags.{c,z,n,i,d}:
// bool`, memory `self.mem[addr]` (64 KiB), the `pha`/`pla` value
// stack `self.stack: Vec<u8>`, and recognised SMC operand variables
// `self.smc.<name>` (immediate) / `self.smc.<name>_lo`/`_hi`
// (address). RAM addresses keep their source symbol names via the
// `sym` constants below. Cross-module routine calls resolve once the
// modules are compiled together; opcode / branch-target SMC stays
// deferred as `// raw: …` comments.
//
// source: 01 POP Source/Source/AUTO.S

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
        }
    }
}

#[allow(non_upper_case_globals)]
mod sym {
    pub const Char: usize = 0x0040;
    pub const CharID: usize = 0x004d;
    pub const PlayCount: usize = 0x00a0;
    pub const ztemp: usize = 0x00f0;
}

impl Cpu {
    fn chgshadposn(&mut self) {
        self.mem[sym::ztemp] = self.reg.a;
        self.mem[sym::ztemp + 1] = self.reg.x;
        self.reg.y = 0x06;
        loop {
            self.mem[sym::Char + self.reg.y as usize] = self.mem[(self.mem[sym::ztemp] as usize | (self.mem[sym::ztemp + 1] as usize) << 8) + self.reg.y as usize];
            self.reg.y = self.reg.y.wrapping_sub(0x01);
            if !((self.reg.y as i8) >= 0) {
                break;
            }
        }
        self.reg.y = 0x07;
        self.reg.a = self.mem[(self.mem[sym::ztemp] as usize | (self.mem[sym::ztemp + 1] as usize) << 8) + self.reg.y as usize];
        self.jumpseq();
        self.mem[sym::CharID] = 0x01;
        self.reg.a = 0x00;
        self.mem[sym::PlayCount] = self.reg.a;
        return;
    }
}
