// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4 skeleton slice: module + routine scaffolding with leaf-
// expression, control-flow, data-movement, carry-arithmetic, and
// `(ptr),y` indirect lowering. Carry is `self.c: u8` (provisional).
// Z/N-only atoms (`Cmp*`, `Bit`), SMC, the stack, `Wide16Stmt`,
// `RawIfStmt`, and `GotoStmt`/`LabelStmt` are deferred; they appear
// as `// raw: …` or `// TODO(pass4): …` comments.
// The `Cpu` receiver and `self.ram`/`self.c` are provisional,
// pending the state/trait design slice. RAM addresses keep their
// source symbol names via the `sym` constants below.
//
// source: 01 POP Source/Source/AUTO.S

#[allow(non_upper_case_globals)]
mod sym {
    pub const CharBlockY: usize = 0x0045;
    pub const CharScrn: usize = 0x004b;
    pub const CharY: usize = 0x0042;
}

impl Cpu {
    fn Cup(&mut self) {
        self.a = self.ram[sym::CharScrn];
        self.getup();
        self.ram[sym::CharScrn] = self.a;
        self.ram[sym::CharBlockY] = (self.ram[sym::CharBlockY]).wrapping_add(0x03);
        self.a = self.ram[sym::CharY];
        self.c = 0;
        let _r = (self.a as u16) + (0xbd) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::CharY] = self.a;
        self.x = 0x03;
        return;
    }
}
