// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4 skeleton slice: module + routine scaffolding with leaf-
// expression, control-flow, data-movement, carry-arithmetic,
// `(ptr),y` indirect, cmp/bit flag, and 16-bit (`Wide16`) lowering.
// Flags are `self.c`/`self.z`/`self.n: u8` (provisional). Unstructured
// routines emit a `loop { match pc { ... } }` dispatch fallback; the
// stack rides `self.stack: Vec<u8>` and recognised SMC immediate
// patches ride `self.<opvar>` fields. Opaque address-patch SMC stays
// deferred as `// raw: …` / `// TODO(pass4): …` comments.
// The `Cpu` receiver and `self.ram`/`self.c`/`self.z`/`self.n` are
// provisional, pending the state/trait design slice. RAM addresses
// keep their source symbol names via the `sym` constants below.
//
// source: 01 POP Source/Source/GRAFIX.S

#[allow(non_upper_case_globals)]
mod sym {
    pub const ALTZPoff: usize = 0xc008;
    pub const ALTZPon: usize = 0xc009;
    pub const BANK: usize = 0x0012;
    pub const BGset1: usize = 0x0303;
    pub const BOTCUT: usize = 0x0013;
    pub const BTN0: usize = 0x001a;
    pub const BTN1: usize = 0x001b;
    pub const BlueSpec: usize = 0x0026;
    pub const BlueType: usize = 0x0024;
    pub const ByteTable: usize = 0x0e00;
    pub const FCharCD: usize = 0x0077;
    pub const FCharCL: usize = 0x0078;
    pub const FCharCR: usize = 0x0079;
    pub const FCharCU: usize = 0x0076;
    pub const FCharFace: usize = 0x0074;
    pub const IIGS: usize = 0x0211;
    pub const IMAGE: usize = 0x0004;
    pub const JSTKX: usize = 0x0018;
    pub const JSTKY: usize = 0x0019;
    pub const LEFTCUT: usize = 0x0010;
    pub const ManCtrl: usize = 0x00de;
    pub const Mult30: usize = 0x1220;
    pub const OFFSET: usize = 0x0003;
    pub const OPACITY: usize = 0x0006;
    pub const OffsetTable: usize = 0x0f00;
    pub const PAGE: usize = 0x0000;
    pub const PEELBUF: usize = 0x0009;
    pub const PEELIMG: usize = 0x000b;
    pub const PEELXCO: usize = 0x000d;
    pub const PEELYCO: usize = 0x000e;
    pub const RAMWRTaux: usize = 0xc005;
    pub const RIGHTCUT: usize = 0x0011;
    pub const RNDseed: usize = 0x009e;
    pub const RWBANK1: usize = 0xc08b;
    pub const RWBANK2: usize = 0xc083;
    pub const TABLE: usize = 0x0007;
    pub const TOPCUT: usize = 0x000f;
    pub const VBLvect: usize = 0x019a;
    pub const XCO: usize = 0x0001;
    pub const YCO: usize = 0x0002;
    pub const bgIMG: usize = 0xad91;
    pub const bgOP: usize = 0xae59;
    pub const bgX: usize = 0xac01;
    pub const bgY: usize = 0xacc9;
    pub const blackflag: usize = 0x0022;
    pub const btn: usize = 0x003d;
    pub const chtabbank: usize = 0x019b;
    pub const chtablist: usize = 0x019c;
    pub const dummy: usize = 0x019d;
    pub const fgIMG: usize = 0xafe9;
    pub const fgOP: usize = 0xb04d;
    pub const fgX: usize = 0xaf21;
    pub const fgY: usize = 0xaf85;
    pub const floorbuf: usize = 0x5e96;
    pub const fredbuf: usize = 0x5e78;
    pub const genCLS: usize = 0xac00;
    pub const halfbuf: usize = 0x5e3c;
    pub const height: usize = 0x0004;
    pub const index: usize = 0x00ee;
    pub const jbtns: usize = 0x020c;
    pub const jhoriz: usize = 0x020b;
    pub const joyX: usize = 0x003b;
    pub const joyY: usize = 0x003c;
    pub const joyon: usize = 0x020d;
    pub const jthres1x: usize = 0x0206;
    pub const jthres1y: usize = 0x0207;
    pub const jthres2x: usize = 0x0208;
    pub const jthres2y: usize = 0x0209;
    pub const jvert: usize = 0x020a;
    pub const kbdX: usize = 0x0039;
    pub const kbdY: usize = 0x003a;
    pub const keypress: usize = 0x020f;
    pub const midCD: usize = 0xb3c7;
    pub const midCL: usize = 0xb3f5;
    pub const midCR: usize = 0xb423;
    pub const midCU: usize = 0xb399;
    pub const midIMG: usize = 0xb30f;
    pub const midOFF: usize = 0xb2b3;
    pub const midOP: usize = 0xb33d;
    pub const midTAB: usize = 0xb451;
    pub const midTYP: usize = 0xb36b;
    pub const midX: usize = 0xb285;
    pub const midY: usize = 0xb2e1;
    pub const movebuf: usize = 0x5ed2;
    pub const msgIMG: usize = 0xb5cf;
    pub const msgOFF: usize = 0xb58f;
    pub const msgOP: usize = 0xb5ef;
    pub const msgX: usize = 0xb56f;
    pub const msgY: usize = 0xb5af;
    pub const musicon: usize = 0x031a;
    pub const objX: usize = 0xb493;
    pub const objbuf: usize = 0x5ef0;
    pub const peelIMGH: usize = 0xb229;
    pub const peelIMGL: usize = 0xb1cd;
    pub const peelX: usize = 0xb115;
    pub const peelY: usize = 0xb171;
    pub const purpleflag: usize = 0x00da;
    pub const redbuf: usize = 0x5e5a;
    pub const savezp: usize = 0x0219;
    pub const scrncolor: usize = 0x031d;
    pub const soundon: usize = 0x0203;
    pub const topbuf: usize = 0x5f2c;
    pub const vblflag: usize = 0x01fb;
    pub const width: usize = 0x0005;
    pub const wipeCOL: usize = 0xb101;
    pub const wipeH: usize = 0xb0d9;
    pub const wipeW: usize = 0xb0ed;
    pub const wipeX: usize = 0xb0b1;
    pub const wipeY: usize = 0xb0c5;
    pub const wipebuf: usize = 0x5eb4;
}

impl Cpu {
    fn VBLvect(&mut self) {
        self.VBLANK();
        return;
    }

    fn ADDBACK(&mut self) {
        self.x = self.ram[sym::bgX];
        self.x = self.x.wrapping_add(1);
        if self.x < 0xc8 {
            self.ram[sym::bgX + self.x as usize] = self.ram[sym::XCO];
            self.a = self.ram[sym::YCO];
            if self.a < 0xc0 {
                self.ram[sym::bgY + self.x as usize] = self.a;
                self.ram[sym::bgIMG + self.x as usize] = self.ram[sym::IMAGE];
                self.a = self.ram[sym::OPACITY];
                self.ram[sym::bgOP + self.x as usize] = self.a;
                self.ram[sym::bgX] = self.x;
            }
        }
        return;
    }

    fn ADDFORE(&mut self) {
        self.x = self.ram[sym::fgX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x64 {
            return;
        }
        self.ram[sym::fgX + self.x as usize] = self.ram[sym::XCO];
        self.a = self.ram[sym::YCO];
        if self.a >= 0xc0 {
            return;
        }
        self.ram[sym::fgY + self.x as usize] = self.a;
        self.ram[sym::fgIMG + self.x as usize] = self.ram[sym::IMAGE];
        self.a = self.ram[sym::OPACITY];
        self.ram[sym::fgOP + self.x as usize] = self.a;
        self.ram[sym::fgX] = self.x;
        return;
    }

    fn ADDMSG(&mut self) {
        self.x = self.ram[sym::msgX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x20 {
            return;
        }
        self.ram[sym::msgX + self.x as usize] = self.ram[sym::XCO];
        self.ram[sym::msgOFF + self.x as usize] = self.ram[sym::OFFSET];
        self.ram[sym::msgY + self.x as usize] = self.ram[sym::YCO];
        self.ram[sym::msgIMG + self.x as usize] = self.ram[sym::IMAGE];
        self.a = self.ram[sym::OPACITY];
        self.ram[sym::msgOP + self.x as usize] = self.a;
        self.ram[sym::msgX] = self.x;
        return;
    }

    fn ADDWIPE(&mut self) {
        self.x = self.ram[sym::wipeX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x14 {
            return;
        }
        self.ram[sym::wipeCOL + self.x as usize] = self.a;
        self.a = self.ram[sym::blackflag];
        if self.a != 0x00 {
            self.a = 0xff;
            self.ram[sym::wipeCOL + self.x as usize] = self.a;
        }
        self.ram[sym::wipeX + self.x as usize] = self.ram[sym::XCO];
        self.ram[sym::wipeY + self.x as usize] = self.ram[sym::YCO];
        self.ram[sym::wipeH + self.x as usize] = self.ram[sym::height];
        self.a = self.ram[sym::width];
        self.ram[sym::wipeW + self.x as usize] = self.a;
        self.ram[sym::wipeX] = self.x;
        return;
    }

    fn ADDMID(&mut self) {
        self.x = self.ram[sym::midX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x2e {
            return;
        }
        self.ram[sym::midTYP + self.x as usize] = self.a;
        self.ram[sym::midX + self.x as usize] = self.ram[sym::XCO];
        self.ram[sym::midOFF + self.x as usize] = self.ram[sym::OFFSET];
        self.ram[sym::midY + self.x as usize] = self.ram[sym::YCO];
        self.ram[sym::midIMG + self.x as usize] = self.ram[sym::IMAGE];
        self.ram[sym::midTAB + self.x as usize] = self.ram[sym::TABLE];
        self.a = self.ram[sym::FCharFace];
        self.a ^= 0xff;
        self.a &= 0x80;
        self.a |= self.ram[sym::OPACITY];
        self.ram[sym::midOP + self.x as usize] = self.a;
        self.ram[sym::midCU + self.x as usize] = self.ram[sym::FCharCU];
        self.ram[sym::midCD + self.x as usize] = self.ram[sym::FCharCD];
        self.ram[sym::midCL + self.x as usize] = self.ram[sym::FCharCL];
        self.a = self.ram[sym::FCharCR];
        self.ram[sym::midCR + self.x as usize] = self.a;
        self.ram[sym::midX] = self.x;
        return;
    }

    fn ADDMIDEZ(&mut self) {
        self.a = 0x00;
        self.ram[sym::OFFSET] = self.a;
        self.x = self.ram[sym::midX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x2e {
            return;
        }
        self.ram[sym::midTYP + self.x as usize] = self.a;
        self.ram[sym::midX + self.x as usize] = self.ram[sym::XCO];
        self.ram[sym::midOFF + self.x as usize] = self.ram[sym::OFFSET];
        self.ram[sym::midY + self.x as usize] = self.ram[sym::YCO];
        self.ram[sym::midIMG + self.x as usize] = self.ram[sym::IMAGE];
        self.ram[sym::midTAB + self.x as usize] = self.ram[sym::TABLE];
        self.ram[sym::midOP + self.x as usize] = self.ram[sym::OPACITY];
        self.ram[sym::midCU + self.x as usize] = 0x00;
        self.ram[sym::midCL + self.x as usize] = 0x00;
        self.ram[sym::midCR + self.x as usize] = 0x28;
        self.a = 0xc0;
        self.ram[sym::midCD + self.x as usize] = self.a;
        self.ram[sym::midX] = self.x;
        return;
    }

    fn ADDMIDEZO(&mut self) {
        self.x = self.ram[sym::midX];
        self.x = self.x.wrapping_add(1);
        if self.x >= 0x2e {
            return;
        }
        self.ram[sym::midTYP + self.x as usize] = self.a;
        self.ram[sym::midX + self.x as usize] = self.ram[sym::XCO];
        self.ram[sym::midOFF + self.x as usize] = self.ram[sym::OFFSET];
        self.ram[sym::midY + self.x as usize] = self.ram[sym::YCO];
        self.ram[sym::midIMG + self.x as usize] = self.ram[sym::IMAGE];
        self.ram[sym::midTAB + self.x as usize] = self.ram[sym::TABLE];
        self.ram[sym::midOP + self.x as usize] = self.ram[sym::OPACITY];
        self.ram[sym::midCU + self.x as usize] = 0x00;
        self.ram[sym::midCL + self.x as usize] = 0x00;
        self.ram[sym::midCR + self.x as usize] = 0x28;
        self.a = 0xc0;
        self.ram[sym::midCD + self.x as usize] = self.a;
        self.ram[sym::midX] = self.x;
        return;
    }

    fn ADDPEEL(&mut self) {
        self.a = self.ram[sym::PEELIMG + 1];
        if self.a == 0x00 {
            return;
        }
        self.a = self.ram[sym::PAGE];
        if self.a != 0x00 {
            self.x = self.ram[sym::purpleflag];
            self.a = self.ram[sym::dummy + self.x as usize];
            self.a = 0x2e;
        }
        self.sm = self.a;
        self.x = self.a;
        self.a = self.ram[sym::peelX + self.x as usize];
        self.c = 0;
        let _r = (self.a as u16) + (0x01) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        if self.a >= 0x2e {
            return;
        }
        self.ram[sym::peelX + self.x as usize] = self.a;
        self.c = 0;
        let _r = (self.a as u16) + (self.sm) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.x = self.a;
        self.ram[sym::peelX + self.x as usize] = self.ram[sym::PEELXCO];
        self.ram[sym::peelY + self.x as usize] = self.ram[sym::PEELYCO];
        self.ram[sym::peelIMGL + self.x as usize] = self.ram[sym::PEELIMG];
        self.a = self.ram[sym::PEELIMG + 1];
        self.ram[sym::peelIMGH + self.x as usize] = self.a;
        return;
    }

    fn DRAWALL(&mut self) {
        self.DOGEN();
        self.a = self.ram[sym::blackflag];
        if self.a == 0x00 {
            self.SNGPEEL();
        }
        self.ZEROPEEL();
        self.DRAWWIPE();
        self.DRAWBACK();
        self.DRAWMID();
        self.DRAWFORE();
        self.DRAWMSG();
        return;
    }

    fn DOGEN(&mut self) {
        self.a = self.ram[sym::genCLS];
        if self.a != 0x00 {
            self.cls();
        }
        self.x = self.ram[sym::BGset1];
        if self.x != 0x01 {
            return;
        }
        self.a = 0x00;
        self.ram[sym::dummy - 1 + self.x as usize] = self.a;
        return;
    }

    fn DRAWWIPE(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = self.ram[sym::wipeX];
                    if self.a == 0x00 {
                        pc = 4;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.a = 0x01;
                    pc = 2;
                }
                2 => {
                    self.stack.push(self.a);
                    self.x = self.a;
                    self.a = self.ram[sym::wipeH + self.x as usize];
                    self.ram[sym::IMAGE] = self.a;
                    self.a = self.ram[sym::wipeW + self.x as usize];
                    self.ram[sym::IMAGE + 1] = self.a;
                    self.a = self.ram[sym::wipeX + self.x as usize];
                    self.ram[sym::XCO] = self.a;
                    self.a = self.ram[sym::wipeY + self.x as usize];
                    self.ram[sym::YCO] = self.a;
                    self.a = self.ram[sym::wipeCOL + self.x as usize];
                    self.ram[sym::OPACITY] = self.a;
                    self.fastblack();
                    self.a = self.stack.pop().expect("pla on empty stack");
                    self.z = (self.a == 0) as u8;
                    self.n = self.a >> 7;
                    self.c = 0;
                    let _r = (self.a as u16) + (0x01) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    let _o: u8 = self.ram[sym::wipeX];
                    self.c = (self.a >= _o) as u8;
                    self.z = (self.a == _o) as u8;
                    self.n = self.a.wrapping_sub(_o) >> 7;
                    if self.a < self.ram[sym::wipeX] {
                        pc = 2;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    if self.z != 0 {
                        pc = 2;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn DRAWBACK(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = self.ram[sym::bgX];
                    if self.a == 0x00 {
                        pc = 4;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.x = 0x01;
                    pc = 2;
                }
                2 => {
                    self.ram[sym::index] = self.x;
                    self.a = self.ram[sym::bgIMG + self.x as usize];
                    self.ram[sym::IMAGE] = self.a;
                    self.setbgimg();
                    self.a = self.ram[sym::bgX + self.x as usize];
                    self.ram[sym::XCO] = self.a;
                    self.a = self.ram[sym::bgY + self.x as usize];
                    self.ram[sym::YCO] = self.a;
                    self.a = self.ram[sym::bgOP + self.x as usize];
                    self.ram[sym::OPACITY] = self.a;
                    self.fastlay();
                    self.x = self.ram[sym::index];
                    self.x = self.x.wrapping_add(1);
                    let _o: u8 = self.ram[sym::bgX];
                    self.c = (self.x >= _o) as u8;
                    self.z = (self.x == _o) as u8;
                    self.n = self.x.wrapping_sub(_o) >> 7;
                    if self.x < self.ram[sym::bgX] {
                        pc = 2;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    if self.z != 0 {
                        pc = 2;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn DRAWFORE(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = self.ram[sym::fgX];
                    if self.a == 0x00 {
                        pc = 7;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.x = 0x01;
                    pc = 2;
                }
                2 => {
                    self.ram[sym::index] = self.x;
                    self.a = self.ram[sym::fgIMG + self.x as usize];
                    self.ram[sym::IMAGE] = self.a;
                    self.setbgimg();
                    self.a = self.ram[sym::fgX + self.x as usize];
                    self.ram[sym::XCO] = self.a;
                    self.a = self.ram[sym::fgY + self.x as usize];
                    self.ram[sym::YCO] = self.a;
                    self.a = self.ram[sym::fgOP + self.x as usize];
                    let _o: u8 = 0x04;
                    self.c = (self.a >= _o) as u8;
                    self.z = (self.a == _o) as u8;
                    self.n = self.a.wrapping_sub(_o) >> 7;
                    if self.a != 0x04 {
                        pc = 4;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.fastmask();
                    pc = 5;
                }
                4 => {
                    self.ram[sym::OPACITY] = self.a;
                    self.fastlay();
                    pc = 5;
                }
                5 => {
                    self.x = self.ram[sym::index];
                    self.x = self.x.wrapping_add(1);
                    let _o: u8 = self.ram[sym::fgX];
                    self.c = (self.x >= _o) as u8;
                    self.z = (self.x == _o) as u8;
                    self.n = self.x.wrapping_sub(_o) >> 7;
                    if self.x < self.ram[sym::fgX] {
                        pc = 2;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    if self.z != 0 {
                        pc = 2;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn SNGPEEL(&mut self) {
        self.x = self.ram[sym::PAGE];
        if self.x == 0x00 {
        } else {
            self.x = 0x2e;
        }
        self.sm = self.x;
        self.a = self.ram[sym::peelX + self.x as usize];
        if self.a == 0x00 {
        } else {
            loop {
                let tmp0 = self.a;
                self.c = 0;
                let _r = (self.a as u16) + (self.sm) as u16 + (self.c as u16);
                self.a = _r as u8;
                self.c = (_r >> 8) as u8;
                self.x = self.a;
                self.ram[sym::IMAGE] = self.ram[sym::peelIMGL + self.x as usize];
                self.ram[sym::IMAGE + 1] = self.ram[sym::peelIMGH + self.x as usize];
                self.ram[sym::XCO] = self.ram[sym::peelX + self.x as usize];
                self.ram[sym::YCO] = self.ram[sym::peelY + self.x as usize];
                self.a = 0x02;
                self.ram[sym::OPACITY] = self.a;
                self.peel();
                self.a = tmp0;
                self.c = 1;
                let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
                self.a = _r as u8;
                self.c = (_r >> 8) as u8;
                if !(self.a != 0x00) {
                    break;
                }
            }
        }
        return;
    }

    fn DRAWMID(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = self.ram[sym::midX];
                    if self.a == 0x00 {
                        pc = 10;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.x = 0x01;
                    pc = 2;
                }
                2 => {
                    self.ram[sym::index] = self.x;
                    self.a = self.ram[sym::midIMG + self.x as usize];
                    self.ram[sym::IMAGE] = self.a;
                    self.a = self.ram[sym::midTAB + self.x as usize];
                    self.ram[sym::TABLE] = self.a;
                    self.a = self.ram[sym::midX + self.x as usize];
                    self.ram[sym::XCO] = self.a;
                    self.a = self.ram[sym::midY + self.x as usize];
                    self.ram[sym::YCO] = self.a;
                    self.a = self.ram[sym::midOP + self.x as usize];
                    self.ram[sym::OPACITY] = self.a;
                    self.a = self.ram[sym::midTYP + self.x as usize];
                    if (self.a as i8) < 0 {
                        pc = 4;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.setbgimg();
                    pc = 5;
                }
                4 => {
                    self.setcharimg();
                    pc = 5;
                }
                5 => {
                    self.a &= 0x7f;
                    if self.a == 0x00 {
                        pc = 11;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    let _o: u8 = 0x01;
                    self.c = (self.a >= _o) as u8;
                    self.z = (self.a == _o) as u8;
                    self.n = self.a.wrapping_sub(_o) >> 7;
                    if self.a == 0x01 {
                        pc = 13;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    let _o: u8 = 0x02;
                    self.c = (self.a >= _o) as u8;
                    self.z = (self.a == _o) as u8;
                    self.n = self.a.wrapping_sub(_o) >> 7;
                    if self.a == 0x02 {
                        pc = 12;
                    } else {
                        pc = 8;
                    }
                }
                8 => {
                    self.x = self.ram[sym::index];
                    self.x = self.x.wrapping_add(1);
                    let _o: u8 = self.ram[sym::midX];
                    self.c = (self.x >= _o) as u8;
                    self.z = (self.x == _o) as u8;
                    self.n = self.x.wrapping_sub(_o) >> 7;
                    if self.x < self.ram[sym::midX] {
                        pc = 2;
                    } else {
                        pc = 9;
                    }
                }
                9 => {
                    if self.z != 0 {
                        pc = 2;
                    } else {
                        pc = 10;
                    }
                }
                10 => {
                    return;
                }
                11 => {
                    self.fastlay();
                    pc = 8;
                }
                12 => {
                    self._3asetaddl();
                    self.layrsave();
                    self.ADDPEEL();
                    self.lay();
                    pc = 8;
                }
                13 => {
                    self._3asetaddl();
                    self.lay();
                    pc = 8;
                }
                14 => {
                    self.a = self.ram[sym::midOFF + self.x as usize];
                    self.ram[sym::OFFSET] = self.a;
                    self.a = self.ram[sym::midCL + self.x as usize];
                    self.ram[sym::LEFTCUT] = self.a;
                    self.a = self.ram[sym::midCR + self.x as usize];
                    self.ram[sym::RIGHTCUT] = self.a;
                    self.a = self.ram[sym::midCU + self.x as usize];
                    self.ram[sym::TOPCUT] = self.a;
                    self.a = self.ram[sym::midCD + self.x as usize];
                    self.ram[sym::BOTCUT] = self.a;
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn DRAWMSG(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = self.ram[sym::msgX];
                    if self.a == 0x00 {
                        pc = 6;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.x = 0x01;
                    pc = 2;
                }
                2 => {
                    self.ram[sym::index] = self.x;
                    self.a = self.ram[sym::msgIMG + self.x as usize];
                    self.ram[sym::IMAGE] = self.a;
                    self.setbgimg();
                    self.a = self.ram[sym::msgX + self.x as usize];
                    self.ram[sym::XCO] = self.a;
                    self.a = self.ram[sym::msgOFF + self.x as usize];
                    self.ram[sym::OFFSET] = self.a;
                    self.a = self.ram[sym::msgY + self.x as usize];
                    self.ram[sym::YCO] = self.a;
                    self.a = 0x00;
                    self.ram[sym::LEFTCUT] = self.a;
                    self.ram[sym::TOPCUT] = self.a;
                    self.a = 0x28;
                    self.ram[sym::RIGHTCUT] = self.a;
                    self.a = 0xc0;
                    self.ram[sym::BOTCUT] = self.a;
                    self.a = self.ram[sym::msgOP + self.x as usize];
                    self.ram[sym::OPACITY] = self.a;
                    self.a &= 0x40;
                    if self.a == 0x00 {
                        pc = 4;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.a = self.ram[sym::OPACITY];
                    self.a &= 0xbf;
                    self.ram[sym::OPACITY] = self.a;
                    self.layrsave();
                    self.ADDPEEL();
                    pc = 4;
                }
                4 => {
                    self.lay();
                    self.x = self.ram[sym::index];
                    self.x = self.x.wrapping_add(1);
                    let _o: u8 = self.ram[sym::msgX];
                    self.c = (self.x >= _o) as u8;
                    self.z = (self.x == _o) as u8;
                    self.n = self.x.wrapping_sub(_o) >> 7;
                    if self.x < self.ram[sym::msgX] {
                        pc = 2;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    if self.z != 0 {
                        pc = 2;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn setbgimg(&mut self) {
        'b3: {
            self.y = self.a;
            self.a = 0x03;
            self.ram[sym::BANK] = self.a;
            self.a = 0x00;
            self.ram[sym::TABLE] = self.a;
            self.a = self.ram[sym::IMAGE];
            if (self.a as i8) < 0 {
                self.a &= 0x7f;
                self.ram[sym::IMAGE] = self.a;
                self.a = 0x84;
                if self.a != 0x00 {
                    break 'b3;
                }
            }
            self.a = 0x60;
        }
        self.ram[sym::TABLE + 1] = self.a;
        self.a = self.y;
        return;
    }

    fn setcharimg(&mut self) {
        let tmp0 = self.a;
        self.y = self.ram[sym::TABLE];
        self.ram[sym::BANK] = self.ram[sym::chtabbank + self.y as usize];
        self.ram[sym::TABLE] = 0x00;
        self.ram[sym::TABLE + 1] = self.ram[sym::chtablist + self.y as usize];
        self.a = tmp0;
        return;
    }

    fn DIMCHAR(&mut self) {
        self.ram[sym::IMAGE] = self.a;
        self.ram[sym::TABLE] = self.x;
        self.setcharimg();
        self.getwidth();
        return;
    }

    fn CVTX(&mut self) {
        self.ram[0x00f0] = 0x00;
        self.a = self.ram[0x0003];
        if (self.a as i8) < 0 {
            loop {
                self.ram[0x00f0] = (self.ram[0x00f0]).wrapping_sub(0x24);
                let _lo = (self.ram[0x0001] as u16) + (0xfc as u16);
                self.ram[0x0001] = _lo as u8;
                let _hi = (self.ram[0x0003] as u16) + (0x00 as u16) + (_lo >> 8);
                self.ram[0x0003] = _hi as u8;
                self.a = _hi as u8;
                self.c = (_hi >> 8) as u8;
                if self.z != 0 {
                    break;
                }
            }
            if self.z != 0 {
                self.y = self.ram[0x0001];
                self.a = self.ram[sym::ByteTable + self.y as usize];
                self.c = 0;
                let _r = (self.a as u16) + self.ram[0x00f0] as u16 + (self.c as u16);
                self.a = _r as u8;
                self.c = (_r >> 8) as u8;
                self.ram[sym::XCO] = self.a;
                self.a = self.ram[sym::OffsetTable + self.y as usize];
                self.ram[sym::OFFSET] = self.a;
                return;
            }
            return;
        }
        if self.z != 0 {
        } else {
            loop {
                self.ram[0x00f0] = (self.ram[0x00f0]).wrapping_add(0x24);
                let _lo = (self.ram[0x0001] as u16) + (!0xfc_u8 as u16) + 1;
                self.ram[0x0001] = _lo as u8;
                let _hi = (self.ram[0x0003] as u16) + (!0x00_u8 as u16) + (_lo >> 8);
                self.ram[0x0003] = _hi as u8;
                self.a = _hi as u8;
                self.c = (_hi >> 8) as u8;
                if self.z != 0 {
                    break;
                }
            }
        }
        self.y = self.ram[0x0001];
        self.a = self.ram[sym::ByteTable + self.y as usize];
        self.c = 0;
        let _r = (self.a as u16) + self.ram[0x00f0] as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::XCO] = self.a;
        self.a = self.ram[sym::OffsetTable + self.y as usize];
        self.ram[sym::OFFSET] = self.a;
        return;
    }

    fn ZEROLSTS(&mut self) {
        self.a = 0x00;
        self.ram[sym::genCLS] = self.a;
        self.ram[sym::wipeX] = self.a;
        self.ram[sym::bgX] = self.a;
        self.ram[sym::midX] = self.a;
        self.ram[sym::objX] = self.a;
        self.ram[sym::fgX] = self.a;
        self.ram[sym::msgX] = self.a;
        return;
    }

    fn ZEROPEELS(&mut self) {
        self.a = 0x00;
        self.ram[sym::peelX] = self.a;
        self.ram[0xb143] = self.a;
        return;
    }

    fn ZEROPEEL(&mut self) {
        self.a = 0x00;
        self.x = self.ram[sym::PAGE];
        if self.x == 0x00 {
            self.ram[sym::peelX] = self.a;
            self.ram[sym::PEELBUF] = 0x00;
            self.a = 0xd0;
            self.ram[sym::PEELBUF + 1] = self.a;
            return;
        }
        self.ram[0xb143] = self.a;
        self.ram[sym::PEELBUF] = 0x00;
        self.a = 0xd6;
        self.ram[sym::PEELBUF + 1] = self.a;
        return;
    }

    fn GETSELECT(&mut self) {
        self.a = self.ram[sym::joyon];
        if self.a == 0x00 {
            if self.z != 0 {
                self.getkbd();
                return;
            }
            self.a = self.ram[sym::joyon];
            if self.a != 0x00 {
                self.getkbd();
                return;
            }
            if self.z != 0 {
            }
        }
        self.ram[sym::JSTKX] = self.ram[sym::joyX];
        self.ram[sym::JSTKY] = self.ram[sym::joyY];
        self.a = self.ram[sym::BTN1];
        self.x = self.ram[sym::ManCtrl];
        if (self.x as i8) >= 0 {
            self.a |= self.ram[sym::BTN0];
        }
        self.ram[sym::btn] = self.a;
        return;
    }

    fn GETDESEL(&mut self) {
        self.a = self.ram[sym::joyon];
        if self.a != 0x00 {
            self.getkbd();
            return;
        }
        if self.z != 0 {
        }
        self.ram[sym::JSTKX] = self.ram[sym::joyX];
        self.ram[sym::JSTKY] = self.ram[sym::joyY];
        self.a = self.ram[sym::BTN1];
        self.x = self.ram[sym::ManCtrl];
        if (self.x as i8) >= 0 {
            self.a |= self.ram[sym::BTN0];
        }
        self.ram[sym::btn] = self.a;
        return;
    }

    fn getjoy(&mut self) {
        self.ram[sym::JSTKX] = self.ram[sym::joyX];
        self.ram[sym::JSTKY] = self.ram[sym::joyY];
        self.a = self.ram[sym::BTN1];
        self.x = self.ram[sym::ManCtrl];
        if (self.x as i8) >= 0 {
            self.a |= self.ram[sym::BTN0];
        }
        self.ram[sym::btn] = self.a;
        return;
    }

    fn getkbd(&mut self) {
        self.ram[sym::JSTKX] = self.ram[sym::kbdX];
        self.ram[sym::JSTKY] = self.ram[sym::kbdY];
        self.a = self.ram[sym::BTN0];
        self.x = self.ram[sym::ManCtrl];
        if (self.x as i8) >= 0 {
            self.a |= self.ram[sym::BTN1];
        }
        self.ram[sym::btn] = self.a;
        return;
    }

    fn CONTROLLER(&mut self) {
        self.JREAD();
        self.BREAD();
        return;
    }

    fn JREAD(&mut self) {
        self.a = self.ram[sym::joyon];
        if self.a == 0x00 {
            return;
        }
        self.PREAD();
        self.x = 0x00;
        self.cvtpdl();
        self.x = self.x.wrapping_add(1);
        self.cvtpdl();
        self.a = self.ram[sym::jvert];
        if self.a != 0x00 {
            self.a = 0x00;
            self.c = 1;
            let _r = (self.a as u16) + (!self.ram[sym::joyY]) as u16 + (self.c as u16);
            self.a = _r as u8;
            self.c = (_r >> 8) as u8;
            self.ram[sym::joyY] = self.a;
        }
        self.a = self.ram[sym::jhoriz];
        if self.a == 0x00 {
            return;
        }
        self.a = 0x00;
        self.c = 1;
        let _r = (self.a as u16) + (!self.ram[sym::joyX]) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::joyX] = self.a;
        return;
    }

    fn BREAD(&mut self) {
        self.a = self.ram[sym::jbtns];
        if self.a != 0x00 {
            self.x = self.ram[0xc062];
            self.a = self.ram[0xc061];
        } else {
            self.a = self.ram[0xc061];
            self.x = self.ram[0xc062];
        }
        self.ram[sym::BTN0] = self.a;
        self.ram[sym::BTN1] = self.x;
        return;
    }

    fn cvtpdl(&mut self) {
        'b5: {
            self.a = self.ram[sym::joyX + self.x as usize];
            let _o: u8 = self.ram[sym::jthres1x + self.x as usize];
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if self.a < self.ram[sym::jthres1x + self.x as usize] {
                self.a = 0xff;
                if self.a != 0x00 {
                    break 'b5;
                }
            }
            let _o: u8 = self.ram[sym::jthres2x + self.x as usize];
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if self.a < self.ram[sym::jthres2x + self.x as usize] {
                self.a = 0x00;
                if self.a == 0x00 {
                    break 'b5;
                }
            }
            self.a = 0x01;
        }
        self.ram[sym::joyX + self.x as usize] = self.a;
        return;
    }

    fn PREAD(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.a = 0x00;
                    self.ram[sym::joyX] = self.a;
                    self.ram[sym::joyY] = self.a;
                    self.a = self.ram[0xc070];
                    pc = 1;
                }
                1 => {
                    self.x = 0x01;
                    pc = 2;
                }
                2 => {
                    self.a = self.ram[0xc064 + self.x as usize];
                    if (self.a as i8) >= 0 {
                        pc = 8;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    // raw: ??? inc joyX,x            ; GRAFIX.S:1209
                    pc = 4;
                }
                4 => {
                    self.x = self.x.wrapping_sub(1);
                    if (self.x as i8) >= 0 {
                        pc = 2;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.a = self.ram[0xc064];
                    self.a |= self.ram[0xc065];
                    if (self.a as i8) >= 0 {
                        pc = 12;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    self.a = self.ram[sym::joyX];
                    self.a |= self.ram[sym::joyY];
                    if (self.a as i8) >= 0 {
                        pc = 1;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    return;
                }
                8 => {
                    // raw: nop                              ; GRAFIX.S:1222
                    if self.n == 0 {
                        pc = 4;
                    } else {
                        pc = 9;
                    }
                }
                9 => {
                    self.normspeed();
                    self.a = 0xff;
                    self.ram[sym::joyon] = self.a;
                    self.a = 0x00;
                    self.ram[sym::jvert] = self.a;
                    self.ram[sym::jhoriz] = self.a;
                    self.ram[sym::jbtns] = self.a;
                    self.PREAD();
                    self.a = self.ram[sym::joyX];
                    self.a |= self.ram[sym::joyY];
                    if (self.a as i8) < 0 {
                        pc = 11;
                    } else {
                        pc = 10;
                    }
                }
                10 => {
                    self.a = self.ram[sym::joyX];
                    self.c = 1;
                    let _r = (self.a as u16) + (!0x0a_u8) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    self.ram[sym::jthres1x] = self.a;
                    self.a = self.ram[sym::joyX];
                    self.c = 0;
                    let _r = (self.a as u16) + (0x0a) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    self.ram[sym::jthres2x] = self.a;
                    self.a = self.ram[sym::joyY];
                    self.c = 1;
                    let _r = (self.a as u16) + (!0x0f_u8) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    self.ram[sym::jthres1y] = self.a;
                    self.a = self.ram[sym::joyY];
                    self.c = 0;
                    let _r = (self.a as u16) + (0x0f) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    self.ram[sym::jthres2y] = self.a;
                    return;
                }
                11 => {
                    self.a = 0x00;
                    self.ram[sym::joyon] = self.a;
                    pc = 12;
                }
                12 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn SETCENTER(&mut self) {
        self.normspeed();
        self.ram[sym::joyon] = 0xff;
        self.a = 0x00;
        self.ram[sym::jvert] = self.a;
        self.ram[sym::jhoriz] = self.a;
        self.ram[sym::jbtns] = self.a;
        self.PREAD();
        self.a = self.ram[sym::joyX];
        self.a |= self.ram[sym::joyY];
        if (self.a as i8) < 0 {
            self.a = 0x00;
            self.ram[sym::joyon] = self.a;
            return;
        }
        self.ram[sym::jthres1x] = (self.ram[sym::joyX]).wrapping_sub(0x0a);
        self.ram[sym::jthres2x] = (self.ram[sym::joyX]).wrapping_add(0x0a);
        self.ram[sym::jthres1y] = (self.ram[sym::joyY]).wrapping_sub(0x0f);
        self.a = self.ram[sym::joyY];
        self.c = 0;
        let _r = (self.a as u16) + (0x0f) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::jthres2y] = self.a;
        return;
    }

    fn MOVEMEM(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.ram[0x00f1] = self.a;
                    self.ram[0x00f3] = self.x;
                    self.ram[0x00f5] = self.y;
                    self.y = 0x00;
                    self.ram[0x00f0] = self.y;
                    self.ram[0x00f2] = self.y;
                    self.ram[0x00f4] = self.y;
                    pc = 1;
                }
                1 => {
                    self.a = self.ram[(self.ram[0x00f2] as usize | (self.ram[0x00f3] as usize) << 8) + self.y as usize];
                    self.ram[(self.ram[0x00f0] as usize | (self.ram[0x00f1] as usize) << 8) + self.y as usize] = self.a;
                    self.y = self.y.wrapping_add(1);
                    if self.y != 0x00 {
                        pc = 1;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.ram[0x00f3] = self.ram[0x00f3].wrapping_add(1);
                    self.ram[0x00f1] = self.ram[0x00f1].wrapping_add(1);
                    self.a = self.ram[0x00f3];
                    let _o: u8 = self.ram[0x00f5];
                    self.c = (self.a >= _o) as u8;
                    self.z = (self.a == _o) as u8;
                    self.n = self.a.wrapping_sub(_o) >> 7;
                    if self.a != self.ram[0x00f5] {
                        pc = 1;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn GTONE(&mut self) {
        self.y = 0x0f;
        self.x = 0x00;
        self.a = 0x32;
        self.tone();
        return;
    }

    fn WHOOP(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.y = 0x00;
                    pc = 1;
                }
                1 => {
                    self.a = self.y;
                    let _o: u8 = self.ram[0xc030];
                    self.z = ((self.a & _o) == 0) as u8;
                    self.n = _o >> 7;
                    pc = 2;
                }
                2 => {
                    self.c = 1;
                    let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    if self.a != 0x00 {
                        pc = 2;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.y = self.y.wrapping_sub(1);
                    if self.y != 0x00 {
                        pc = 1;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn tone(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    // raw: patch *:pitch = y            ; GRAFIX.S:1344
                    // raw: patch *:pitch+1 = x            ; GRAFIX.S:1345
                    pc = 1;
                }
                1 => {
                    let _o: u8 = self.ram[0xc030];
                    self.z = ((self.a & _o) == 0) as u8;
                    self.n = _o >> 7;
                    self.x = 0x00;
                    pc = 2;
                }
                2 => {
                    self.y = 0x00;
                    pc = 3;
                }
                3 => {
                    self.y = self.y.wrapping_add(1);
                    // raw: ??? cpy :pitch            ; GRAFIX.S:1350
                    if self.c == 0 {
                        pc = 3;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.x = self.x.wrapping_add(1);
                    // raw: ??? cpx :pitch+1            ; GRAFIX.S:1353
                    if self.c == 0 {
                        pc = 2;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.c = 1;
                    let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    if self.a != 0x00 {
                        pc = 1;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    return;
                }
                7 => {
                    self.a = self.ram[sym::PAGE];
                    self.c = 0;
                    let _r = (self.a as u16) + (0x20) as u16 + (self.c as u16);
                    self.a = _r as u8;
                    self.c = (_r >> 8) as u8;
                    self.ram[sym::IMAGE + 1] = self.a;
                    self.a ^= 0x60;
                    self.ram[sym::IMAGE] = self.a;
                    self.copy2000();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn COPYSCRN(&mut self) {
        self.a = self.ram[sym::PAGE];
        self.c = 0;
        let _r = (self.a as u16) + (0x20) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::IMAGE + 1] = self.a;
        self.a ^= 0x60;
        self.ram[sym::IMAGE] = self.a;
        self.copy2000();
        return;
    }

    fn RND(&mut self) {
        self.a = self.ram[sym::RNDseed];
        self.c = self.a >> 7;
        self.a = self.a.wrapping_shl(1);
        self.c = self.a >> 7;
        self.a = self.a.wrapping_shl(1);
        self.c = 0;
        let _r = (self.a as u16) + self.ram[sym::RNDseed] as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.c = 0;
        let _r = (self.a as u16) + (0x17) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.ram[sym::RNDseed] = self.a;
        return;
    }

    fn LOADLEVEL(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._loadlevel();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn ATTRACTMODE(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._attractmode();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn CUTPRINCESS(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._cutprincess();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn RELOAD(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._reload();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn LOADSTAGE2(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._loadstage2();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn SAVEGAME(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._savegame();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn LOADGAME(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._loadgame();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn DOSTARTGAME(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._dostartgame();
        return;
    }

    fn EPILOG(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._epilog();
        return;
    }

    fn LOADALTSET(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._loadaltset();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn SCREENDUMP(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._screendump();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    // aliases: SAVELEVELG, READDIR, WRITEDIR, GOBUILD, GOGAME, EDREBOOT
    fn SAVELEVEL(&mut self) {
        return;
    }

    fn CLS(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._cls();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn LAY(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._lay();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn FASTLAY(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._fastlay();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn LAYRSAVE(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._layrsave();
        self.ram[sym::ALTZPon] = self.a;
        self.posthr();
        return;
    }

    fn LRCLS(&mut self) {
        self.ram[sym::scrncolor] = self.a;
        self.ram[sym::ALTZPoff] = self.a;
        self._lrcls();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn FASTMASK(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._fastmask();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn FASTBLACK(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._fastblack();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn PEEL(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._peel();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn GETWIDTH(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._getwidth();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn COPY2000(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._copy2000();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn COPY2000AM(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._copy2000am();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn COPY2000MA(&mut self) {
        self.prehr();
        self.ram[sym::ALTZPoff] = self.a;
        self._copy2000ma();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn SETFASTAUX(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._setfastaux();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn SETFASTMAIN(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._setfastmain();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn INVERTY(&mut self) {
        self.ram[sym::ALTZPoff] = self.a;
        self._inverty();
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn MINIT(&mut self) {
        self._5dbank1in();
        self.CALLMINIT();
        let _o: u8 = self.ram[sym::RWBANK2];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        let _o: u8 = self.ram[sym::RWBANK2];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        return;
    }

    fn MPLAY(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self._5dbank1in();
                    self.CALLMPLAY();
                    self._5dbank2in();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn XMINIT(&mut self) {
        self.ram[sym::ALTZPon] = self.a;
        self.MINIT();
        self.ram[sym::ALTZPoff] = self.a;
        return;
    }

    fn XMPLAY(&mut self) {
        self.ram[sym::ALTZPon] = self.a;
        self.MPLAY();
        self.ram[sym::ALTZPoff] = self.a;
        return;
    }

    fn XTITLE(&mut self) {
        self.ram[sym::ALTZPon] = self.a;
        self.titlescreen();
        self.ram[sym::ALTZPoff] = self.a;
        return;
    }

    fn XPLAYCUT(&mut self) {
        self.ram[sym::ALTZPon] = self.a;
        self.playcut();
        self.ram[sym::ALTZPoff] = self.a;
        return;
    }

    fn XMOVEMUSIC(&mut self) {
        self.ram[sym::ALTZPon] = self.a;
        self.movemusic();
        self.ram[sym::ALTZPoff] = self.a;
        return;
    }

    fn prehr(&mut self) {
        self.x = 0x17;
        loop {
            self.ram[sym::ALTZPon] = self.a;
            self.a = self.ram[0x0000 + self.x as usize];
            self.ram[sym::ALTZPoff] = self.a;
            self.ram[0x0000 + self.x as usize] = self.a;
            self.x = self.x.wrapping_sub(0x01);
            if !((self.x as i8) >= 0) {
                break;
            }
        }
        self.ram[sym::ALTZPon] = self.a;
        return;
    }

    fn posthr(&mut self) {
        self.x = 0x17;
        loop {
            self.ram[sym::ALTZPoff] = self.a;
            self.a = self.ram[0x0000 + self.x as usize];
            self.ram[sym::ALTZPon] = self.a;
            self.ram[0x0000 + self.x as usize] = self.a;
            self.x = self.x.wrapping_sub(0x01);
            if !((self.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn SAVEBLUE(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self._5dbank1in();
                    self.a = 0xd7;
                    self.x = 0xb7;
                    self.y = 0xc0;
                    self.movemem();
                    self._5dbank2in();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn SAVEBINFO(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self._5dbank1in();
                    self.a = 0xd0;
                    self.x = 0xa6;
                    self.y = 0xac;
                    self.movemem();
                    self._5dbank2in();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn RELOADBLUE(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self._5dbank1in();
                    self.a = 0xb7;
                    self.x = 0xd7;
                    self.y = 0xe0;
                    self.movemem();
                    self._5dbank2in();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn RELOADBINFO(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self._5dbank1in();
                    self.a = 0xa6;
                    self.x = 0xd0;
                    self.y = 0xd6;
                    self.movemem();
                    self._5dbank2in();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn GR(&mut self) {
        self.gtone();
        return;
    }

    fn CALCBLUE(&mut self) {
        if self.a == 0x00 {
            self.calcmenu();
            return;
        }
        self.c = 1;
        let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        self.c = self.a >> 7;
        self.a = self.a.wrapping_shl(1);
        self.x = self.a;
        let _lo = (self.ram[sym::Mult30 + self.x as usize] as u16) + (0x00 as u16);
        self.ram[sym::BlueType] = _lo as u8;
        let _hi = (self.ram[sym::Mult30 + 1 + self.x as usize] as u16) + (0xb7 as u16) + (_lo >> 8);
        self.ram[sym::BlueType + 1] = _hi as u8;
        self.a = _hi as u8;
        self.c = (_hi >> 8) as u8;
        let _lo = (self.ram[sym::BlueType] as u16) + (0xd0 as u16);
        self.ram[sym::BlueSpec] = _lo as u8;
        let _hi = (self.ram[sym::BlueType + 1] as u16) + (0x02 as u16) + (_lo >> 8);
        self.ram[sym::BlueSpec + 1] = _hi as u8;
        self.a = _hi as u8;
        self.c = (_hi >> 8) as u8;
        return;
    }

    fn calcmenu(&mut self) {
        self.ram[sym::BlueType] = 0x0f;
        self.ram[sym::BlueType + 1] = 0x96;
        self.ram[sym::BlueSpec] = 0x2d;
        self.a = 0x96;
        self.ram[sym::BlueSpec + 1] = self.a;
        return;
    }

    fn ZERORED(&mut self) {
        self.a = 0x00;
        self.y = 0x1d;
        loop {
            self.ram[sym::redbuf + self.y as usize] = self.a;
            self.ram[sym::fredbuf + self.y as usize] = self.a;
            self.ram[sym::floorbuf + self.y as usize] = self.a;
            self.ram[sym::halfbuf + self.y as usize] = self.a;
            self.ram[sym::wipebuf + self.y as usize] = self.a;
            self.ram[sym::movebuf + self.y as usize] = self.a;
            self.ram[sym::objbuf + self.y as usize] = self.a;
            self.y = self.y.wrapping_sub(0x01);
            if !((self.y as i8) >= 0) {
                break;
            }
        }
        self.y = 0x09;
        loop {
            self.ram[sym::topbuf + self.y as usize] = self.a;
            self.y = self.y.wrapping_sub(0x01);
            if !((self.y as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn switchzp(&mut self) {
        self.x = 0x1f;
        loop {
            self.y = self.ram[sym::savezp + self.x as usize];
            self.ram[sym::savezp + self.x as usize] = self.ram[0x0000 + self.x as usize];
            self.a = self.y;
            self.ram[0x0000 + self.x as usize] = self.a;
            self.x = self.x.wrapping_sub(0x01);
            if !((self.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn CALLMINIT(&mut self) {
        let tmp0 = self.a;
        self.switchzp();
        self.a = tmp0;
        self._minit();
        self.switchzp();
        return;
    }

    fn CALLMPLAY(&mut self) {
        self.a = self.ram[sym::soundon];
        self.a &= self.ram[sym::musicon];
        if self.a == 0x00 {
            self.a = 0x00;
            return;
        }
        self.switchzp();
        self._mplay();
        let tmp0 = self.a;
        self.switchzp();
        self.a = tmp0;
        return;
    }

    fn MUSICKEYS(&mut self) {
        self.a = self.ram[0xc000];
        self.ram[sym::keypress] = self.a;
        if self.n == 0 {
            self.a = self.ram[0xc061];
            self.a |= self.ram[0xc062];
            if (self.a as i8) >= 0 {
                self.a = self.ram[sym::keypress];
                return;
            }
            self.a = 0xff;
            return;
        }
        self.ram[0xc010] = self.a;
        let _o: u8 = 0x9b;
        self.c = (self.a >= _o) as u8;
        self.z = (self.a == _o) as u8;
        self.n = self.a.wrapping_sub(_o) >> 7;
        if self.a != 0x9b {
            let _o: u8 = 0x13;
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if self.a != 0x13 {
                let _o: u8 = 0x0e;
                self.c = (self.a >= _o) as u8;
                self.z = (self.a == _o) as u8;
                self.n = self.a.wrapping_sub(_o) >> 7;
                if self.a != 0x0e {
                    self.a = self.ram[0xc061];
                    self.a |= self.ram[0xc062];
                    if (self.a as i8) >= 0 {
                        self.a = self.ram[sym::keypress];
                        return;
                    }
                    self.a = 0xff;
                    return;
                }
                self.a = self.ram[sym::musicon];
                self.a ^= 0x01;
                self.ram[sym::musicon] = self.a;
                if self.z != 0 {
                } else {
                    self.gtone();
                }
                self.a = 0x00;
                return;
            }
            self.a = self.ram[sym::soundon];
            self.a ^= 0x01;
            self.ram[sym::soundon] = self.a;
            if self.z != 0 {
            } else {
                self.gtone();
            }
            self.a = 0x00;
            return;
        }
        loop {
            self.a = self.ram[0xc000];
            self.ram[sym::keypress] = self.a;
            if self.n != 0 {
                break;
            }
        }
        self.ram[0xc010] = self.a;
        let _o: u8 = 0x9b;
        self.c = (self.a >= _o) as u8;
        self.z = (self.a == _o) as u8;
        self.n = self.a.wrapping_sub(_o) >> 7;
        if self.a != 0x9b {
            let _o: u8 = 0x13;
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if self.a != 0x13 {
                let _o: u8 = 0x0e;
                self.c = (self.a >= _o) as u8;
                self.z = (self.a == _o) as u8;
                self.n = self.a.wrapping_sub(_o) >> 7;
                if self.a != 0x0e {
                    self.a = self.ram[0xc061];
                    self.a |= self.ram[0xc062];
                    if (self.a as i8) >= 0 {
                        self.a = self.ram[sym::keypress];
                        return;
                    }
                    self.a = 0xff;
                    return;
                }
                self.a = self.ram[sym::musicon];
                self.a ^= 0x01;
                self.ram[sym::musicon] = self.a;
                if self.z != 0 {
                } else {
                    self.gtone();
                }
                self.a = 0x00;
                return;
            }
            self.a = self.ram[sym::soundon];
            self.a ^= 0x01;
            self.ram[sym::soundon] = self.a;
            if self.z != 0 {
            } else {
                self.gtone();
            }
            self.a = 0x00;
            return;
        }
        self.a &= 0x7f;
        return;
    }

    // aliases: :loop1
    fn VBLANK(&mut self) {
        self.a = self.ram[0xc019];
        if (self.a as i8) >= 0 {
            self.VBLANK();
            return;
        }
        loop {
            self.a = self.ram[0xc019];
            if !((self.a as i8) < 0) {
                break;
            }
        }
        return;
    }

    fn VBLANKIIc(&mut self) {
        self.i = 0;
        loop {
            let _o: u8 = self.ram[sym::vblflag];
            self.z = ((self.a & _o) == 0) as u8;
            self.n = _o >> 7;
            if self.n != 0 {
                break;
            }
        }
        self.c = self.ram[sym::vblflag] & 1;
        self.ram[sym::vblflag] = self.ram[sym::vblflag].wrapping_shr(1);
        loop {
            let _o: u8 = self.ram[sym::vblflag];
            self.z = ((self.a & _o) == 0) as u8;
            self.n = _o >> 7;
            if self.n != 0 {
                break;
            }
        }
        self.c = self.ram[sym::vblflag] & 1;
        self.ram[sym::vblflag] = self.ram[sym::vblflag].wrapping_shr(1);
        self.i = 1;
        return;
    }

    fn VBLI(&mut self) {
        let _o: u8 = self.ram[0xc019];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        self.ram[0xc079] = self.a;
        self.ram[0xc05b] = self.a;
        self.ram[0xc078] = self.a;
        self.c = 1;
        let _c = self.ram[sym::vblflag] & 1;
        self.ram[sym::vblflag] = self.ram[sym::vblflag].wrapping_shr(1) | (self.c << 7);
        self.c = _c;
        // raw: ??? rti             ; GRAFIX.S:1978
        return;
    }

    fn InitVBLANK(&mut self) {
        self.a = self.ram[0xfbc0];
        if self.a != 0x00 {
            return;
        }
        self.ram[sym::RAMWRTaux] = self.a;
        self.ram[sym::VBLvect + 1] = 0xfd;
        self.a = 0x01;
        self.ram[sym::VBLvect + 2] = self.a;
        self.i = 1;
        self.ram[0xc079] = self.a;
        self.ram[0xc05b] = self.a;
        self.ram[0xc078] = self.a;
        return;
    }

    fn FASTSPEED(&mut self) {
        self.a = self.ram[sym::IIGS];
        if self.a == 0x00 {
            return;
        }
        self.a = 0x80;
        // raw: ??? tsb $C036            ; GRAFIX.S:2052
        return;
    }

    fn NORMSPEED(&mut self) {
        self.a = self.ram[sym::IIGS];
        if self.a == 0x00 {
            return;
        }
        self.a = self.ram[0xc034];
        self.a &= 0xf0;
        self.ram[0xc034] = self.a;
        self.ram[0xc022] = 0xf0;
        self.a = 0x80;
        // raw: ??? trb $c036            ; GRAFIX.S:2073
        return;
    }

    fn getparam(&mut self) {
        self.a = self.ram[sym::IIGS];
        if self.a == 0x00 {
            return;
        }
        self.c = 0;
        // raw: ??? xce             ; GRAFIX.S:2093
        // raw: ??? rep $30            ; GRAFIX.S:2094
        self.stack.push(self.a);
        // raw: ??? phy             ; GRAFIX.S:2096
        self.x = 0x03;
        self.a = self.stack.pop().expect("pla on empty stack");
        self.z = (self.a == 0) as u8;
        self.n = self.a >> 7;
        self.c = 1;
        // raw: ??? xce             ; GRAFIX.S:2101
        self.y = self.a;
        return;
    }

    fn setparam(&mut self) {
        self.c = 0;
        // raw: ??? xce             ; GRAFIX.S:2114
        // raw: ??? rep $30            ; GRAFIX.S:2115
        self.a &= 0xff;
        self.stack.push(self.a);
        // raw: ??? phy             ; GRAFIX.S:2118
        self.x = 0x03;
        self.c = 1;
        // raw: ??? xce             ; GRAFIX.S:2122
        return;
    }

    fn _3asetaddl(&mut self) {
        self.ram[sym::OFFSET] = self.ram[sym::midOFF + self.x as usize];
        self.ram[sym::LEFTCUT] = self.ram[sym::midCL + self.x as usize];
        self.ram[sym::RIGHTCUT] = self.ram[sym::midCR + self.x as usize];
        self.ram[sym::TOPCUT] = self.ram[sym::midCU + self.x as usize];
        self.a = self.ram[sym::midCD + self.x as usize];
        self.ram[sym::BOTCUT] = self.a;
        return;
    }

    fn _5dbank1in(&mut self) {
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        return;
    }
}
