// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4: module + routine scaffolding with leaf-expression,
// control-flow, data-movement, carry-arithmetic, `(ptr),y` indirect,
// cmp/bit flag, 16-bit (`Wide16`), dispatch-fallback, stack, and SMC
// operand-patch lowering.
//
// State is decomposed into `Cpu { reg, flags, mem, stack, smc }`:
// registers `self.reg.{a,x,y}: u8`, flags `self.flags.{c,z,n,i,d}:
// bool`, memory `self.mem[addr]` (64 KiB), the `pha`/`pla` value
// stack `self.stack: Vec<u8>`, and recognised SMC operand variables
// `self.smc.<name>` (immediate) / `self.smc.<name>_lo`/`_hi`
// (address). RAM addresses keep their source symbol names via the
// `sym` constants below. Cross-module routine calls resolve once the
// modules are compiled together; opcode / branch-target SMC stays
// deferred as `// raw: …` comments.
//
// source: 01 POP Source/Source/MASTER.S

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
    // Local-label / Merlin-variable byte store, keyed by symbolic
    // `(name, offset)`: StoreLocal writes, LoadLocal/CmpLocal read.
    pub local: std::collections::HashMap<(&'static str, u8), u8>,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
            local: std::collections::HashMap::new(),
        }
    }
}

#[allow(non_upper_case_globals)]
mod sym {
    pub const BBundID: usize = 0x03f5;
    pub const BGset1: usize = 0x0303;
    pub const BGset2: usize = 0x0304;
    pub const CHset: usize = 0x0305;
    pub const IIGS: usize = 0x0211;
    pub const IMAGE: usize = 0x0004;
    pub const MIXEDoff: usize = 0xc052;
    pub const MSset: usize = 0x0239;
    pub const PAGE2off: usize = 0xc054;
    pub const PAGE2on: usize = 0xc055;
    pub const RAMRDaux: usize = 0xc003;
    pub const RAMRDmain: usize = 0xc002;
    pub const RAMWRTaux: usize = 0xc005;
    pub const RAMWRTmain: usize = 0xc004;
    pub const RWBANK1: usize = 0xc08b;
    pub const RWBANK2: usize = 0xc083;
    pub const bg1trk: usize = 0x022b;
    pub const bg2trk: usize = 0x022c;
    pub const bluepREG: usize = 0x03f1;
    pub const bluepTRK: usize = 0x03f0;
    pub const ch4off: usize = 0x022e;
    pub const ch4trk: usize = 0x022d;
    pub const demolevel: usize = 0x021a;
    pub const firstlevel: usize = 0x021b;
    pub const invert: usize = 0x009f;
    pub const keypress: usize = 0x020f;
    pub const musicon: usize = 0x031a;
    pub const newBGset1: usize = 0x00f6;
    pub const newBGset2: usize = 0x00f7;
    pub const newCHset: usize = 0x00f8;
    pub const params: usize = 0x03f0;
    pub const pausetemp: usize = 0x03f7;
    pub const recheck0: usize = 0x03f8;
    pub const savedgame: usize = 0xb6f0;
    pub const soundon: usize = 0x0203;
    pub const track: usize = 0x00fe;
}

impl Cpu {
    fn FIRSTBOOT(&mut self) {
        self.reg.a = self.mem[sym::MIXEDoff];
        self.setaux();
        self.mem[sym::BBundID] = 0xa9;
        self.mem[sym::RAMWRTmain] = 0xa9;
        self.reg.a = 0x02;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.loadperm();
        self.driveoff();
        self.checkIIGS();
        self.initsystem();
        self.mem[sym::invert] = 0x00;
        self.mem[sym::soundon] = 0x01;
        self.ATTRACTMODE();
        return;
    }

    fn loadmusic1(&mut self) {
        self.setmain();
        self.reg.a = 0x22;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.setaux();
        self.xmovemusic();
        return;
    }

    fn loadmusic2(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.setmain();
                    self.reg.a = 0x14;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    self._5dmm();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn loadmusic3(&mut self) {
        self.loadmusic1();
        return;
    }

    fn setaux(&mut self) {
        self.mem[sym::RAMRDaux] = self.reg.a;
        self.mem[sym::RAMWRTaux] = self.reg.a;
        return;
    }

    fn setmain(&mut self) {
        self.mem[sym::RAMRDmain] = self.reg.a;
        self.mem[sym::RAMWRTmain] = self.reg.a;
        return;
    }

    fn driveon(&mut self) {
        self.reg.a = 0x00;
        self.local.insert((":delay", 0), self.reg.a);
        self.setaux();
        let _o: u8 = self.mem[sym::RWBANK1];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        let _o: u8 = self.mem[sym::RWBANK1];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        self.reg.a = self.mem[sym::BBundID];
        self.local.insert((":IDbyte", 0), self.reg.a);
        self.rw18();
        self.rw18();
        return;
    }

    fn driveon1(&mut self) {
        self.local.insert((":delay", 0), self.reg.a);
        self.setaux();
        let _o: u8 = self.mem[sym::RWBANK1];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        let _o: u8 = self.mem[sym::RWBANK1];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        self.reg.a = self.mem[sym::BBundID];
        self.local.insert((":IDbyte", 0), self.reg.a);
        self.rw18();
        self.rw18();
        return;
    }

    fn driveoff(&mut self) {
        self.rw18();
        let _o: u8 = self.mem[sym::RWBANK2];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        let _o: u8 = self.mem[sym::RWBANK2];
        self.flags.z = (self.reg.a & _o) == 0;
        self.flags.n = (_o >> 7) != 0;
        self.mem[0xc010] = self.reg.a;
        self.setaux();
        return;
    }

    fn set1stlevel(&mut self) {
        self.reg.a = self.mem[sym::firstlevel];
        self.reg.x = self.mem[sym::firstlevel + 1];
        self.mem[sym::params] = self.reg.a;
        self.mem[sym::params + 1] = self.reg.x;
        return;
    }

    fn SetLevel(&mut self) {
        self.mem[sym::params] = self.reg.a;
        self.mem[sym::params + 1] = self.reg.x;
        return;
    }

    fn setdemolevel(&mut self) {
        self.reg.a = self.mem[sym::demolevel];
        self.reg.x = self.mem[sym::demolevel + 1];
        self.SetLevel();
        return;
    }

    fn checkdisk(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.setaux();
                    self.reg.x = 0xad;
                    self.mem[sym::BBundID] = self.reg.x;
                    self.driveon();
                    pc = 1;
                }
                1 => {
                    self.setmain();
                    self.reg.a = 0x16;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn SAVEGAME(&mut self) {
        self.checkdisk();
        self.mem[sym::RAMRDaux] = self.reg.a;
        self.reg.x = 0x0f;
        loop {
            self.reg.a = self.mem[sym::savedgame + self.reg.x as usize];
            self.mem[0x0200 + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        self.mem[sym::RAMRDmain] = self.reg.a;
        self.reg.a = 0x17;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        if !self.flags.c {
        } else {
            self.whoop();
        }
        self.driveoff();
        return;
    }

    fn LOADGAME(&mut self) {
        self.checkdisk();
        self.reg.a = 0x17;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.mem[sym::RAMWRTaux] = self.reg.a;
        self.reg.x = 0x0f;
        loop {
            self.reg.a = self.mem[0x0200 + self.reg.x as usize];
            self.mem[sym::savedgame + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        self.driveoff();
        return;
    }

    fn LOADALTSET(&mut self) {
        self.mem[sym::newCHset] = self.reg.y;
        self.driveon();
        self.rdch4();
        self.driveoff();
        return;
    }

    fn LOADLEVEL(&mut self) {
        self.mem[sym::newBGset1] = self.reg.a;
        self.mem[sym::newBGset2] = self.reg.x;
        self.mem[sym::newCHset] = self.reg.y;
        self.driveon();
        self.rdbluep();
        self.rdbg1();
        self.rdbg2();
        self.rdch4();
        self.vidstuff();
        self.driveoff();
        return;
    }

    fn setbluep(&mut self) {
        self.mem[sym::track] = self.mem[sym::bluepTRK];
        self.reg.a = self.mem[sym::bluepREG];
        return;
    }

    fn vidstuff(&mut self) {
        self.reg.a = self.mem[sym::BBundID];
        let _o: u8 = 0xad;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0xad {
            return;
        }
        self.reg.a = self.mem[0xc000];
        let _o: u8 = 0x5e;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0x5e {
            return;
        }
        self.setmain();
        self.reg.a = 0x0c;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        loop {
            self.rw18();
            self.reg.a = self.local.get(&(":sm", 0)).copied().unwrap_or(0);
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.flags.c = false;
            let _r = (self.reg.a as u16) + (0x12) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
            self.local.insert((":sm", 0), self.reg.a);
            let _o: u8 = 0x6c;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if !(self.reg.a < 0x6c) {
                break;
            }
        }
        self.driveoff();
        self.setmain();
        self._24c00();
        return;
    }

    fn rdbg1(&mut self) {
        self.reg.x = self.mem[sym::newBGset1];
        if self.reg.x == self.mem[sym::BGset1] {
            return;
        }
        self.mem[sym::BGset1] = self.reg.x;
        self.reg.a = self.mem[sym::bg1trk + self.reg.x as usize];
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.rw18();
        return;
    }

    fn rdbg2(&mut self) {
        self.reg.x = self.mem[sym::newBGset2];
        if self.reg.x == self.mem[sym::BGset2] {
            return;
        }
        self.mem[sym::BGset2] = self.reg.x;
        self.reg.a = self.mem[sym::bg2trk + self.reg.x as usize];
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        return;
    }

    fn rdch4(&mut self) {
        self.reg.x = self.mem[sym::newCHset];
        if self.reg.x == self.mem[sym::CHset] {
            return;
        }
        self.mem[sym::CHset] = self.reg.x;
        self.mem[sym::track] = self.mem[sym::ch4trk + self.reg.x as usize];
        self.reg.a = self.mem[sym::ch4off + self.reg.x as usize];
        match self.reg.a {
            0x00 => {
                self.rw18();
                self.rw18();
                return;
            }
            0x06 => {
                self.rw18();
                self.rw18();
                return;
            }
            0x0c => {
                self.rw18();
                self.rw18();
                return;
            }
            _ => {}
        }
        return;
    }

    fn rdbluep(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.setbluep();
                    if !self.flags.z {
                        pc = 3;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 5;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 5;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.error();
                    pc = 3;
                }
                5 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn copy1to2(&mut self) {
        self.reg.a = 0x40;  // dest
        self.reg.x = 0x20;  // org
        if self.reg.x == 0x00 {
            self.reg.a = 0x20;
            self.reg.x = 0x40;
        }
        self.mem[sym::IMAGE + 1] = self.reg.a;
        self.mem[sym::IMAGE] = self.reg.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn copy2to1(&mut self) {
        self.reg.a = 0x20;
        self.reg.x = 0x40;
        self.mem[sym::IMAGE + 1] = self.reg.a;
        self.mem[sym::IMAGE] = self.reg.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn copydhires(&mut self) {
        self.mem[sym::IMAGE + 1] = self.reg.a;
        self.mem[sym::IMAGE] = self.reg.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn CUTPRINCESS(&mut self) {
        self.blackout();
        self.reg.a = 0x01;  // seek track 0
        self.LoadStage2();
        self.reg.a = 0x84;
        self.SngExpand();
        self.mem[sym::IMAGE + 1] = 0x40;
        self.reg.a = 0x20;
        self.mem[sym::IMAGE] = self.reg.a;
        self._copy2000();
        return;
    }

    fn cutprincess1(&mut self) {
        self.LoadStage2();
        self.reg.a = 0x84;
        self.SngExpand();
        self.mem[sym::IMAGE + 1] = 0x40;
        self.reg.a = 0x20;
        self.mem[sym::IMAGE] = self.reg.a;
        self._copy2000();
        return;
    }

    fn EPILOG(&mut self) {
        self.reg.a = 0x01;
        self.mem[sym::soundon] = self.reg.a;
        self.mem[sym::musicon] = self.reg.a;
        self.blackout();
        self.LoadStage1B();
        self.Epilog();
        self.reg.a = 0xa9;
        self.mem[sym::BBundID] = self.reg.a;
        self.mem[0xc010] = self.reg.a;
        loop {
            self.reg.a = self.mem[0xc000];
            if !((self.reg.a as i8) >= 0) {
                break;
            }
        }
        self.reg.a = 0x01;
        self.mem[sym::musicon] = self.reg.a;
        self.SetupDHires();
        self.PubCredit();
        self.AuthorCredit();
        self.TitleScreen();
        self.Prolog1();
        self.PrincessScene();
        self.SetupDHires();
        self.Prolog2();
        self.SilentTitle();
        self.Demo();
        return;
    }

    // aliases: AttractLoop
    fn ATTRACTMODE(&mut self) {
        self.reg.a = 0x01;
        self.mem[sym::musicon] = self.reg.a;
        self.SetupDHires();
        self.PubCredit();
        self.AuthorCredit();
        self.TitleScreen();
        self.Prolog1();
        self.PrincessScene();
        self.SetupDHires();
        self.Prolog2();
        self.SilentTitle();
        self.Demo();
        return;
    }

    fn SetupDHires(&mut self) {
        self.blackout();
        self.LoadStage1A();
        return;
    }

    fn PubCredit(&mut self) {
        self.unpacksplash();
        self.setdhires();
        self.copy1to2();
        self.reg.a = 0x2c;
        self.tpause();
        self.reg.a = 0x70;
        self.DeltaExpPop();
        self.reg.x = 0x50;
        self.reg.a = 0x01;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn CleanScreen(&mut self) {
        self.reg.a = self.mem[sym::PAGE2on];
        self.copy2to1();
        self.reg.a = self.mem[sym::PAGE2off];
        return;
    }

    fn AuthorCredit(&mut self) {
        self.reg.a = 0x2a;
        self.tpause();
        self.reg.a = 0x72;
        self.DeltaExpPop();
        self.reg.x = 0x50;
        self.reg.a = 0x02;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn SilentTitle(&mut self) {
        self.unpacksplash();
        self.copy1to2();
        self.reg.a = 0x14;
        self.tpause();
        self.reg.a = 0x74;
        self.DeltaExpPop();
        self.reg.a = 0xa0;
        self.tpause();
        return;
    }

    fn TitleScreen(&mut self) {
        self.reg.a = 0x26;
        self.tpause();
        self.reg.a = 0x74;
        self.DeltaExpPop();
        self.reg.x = 0x8c;
        self.reg.a = 0x03;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn Prolog1(&mut self) {
        self.reg.a = 0x7c;
        self.mem[sym::RAMRDaux] = self.reg.a;
        self.DblExpand();
        self.reg.x = 0xfa;
        self.reg.a = 0x04;
        self.PlaySongI();
        return;
    }

    fn PrincessScene(&mut self) {
        self.blackout();
        self.ReloadStuff();
        self.reg.a = 0x00;  // don't seek track 0
        self.cutprincess1();
        self.reg.a = 0x00;  // cut #0 (intro)
        self.xplaycut();
        return;
    }

    fn Prolog2(&mut self) {
        self.reg.a = 0x60;
        self.mem[sym::RAMRDmain] = self.reg.a;
        self.DblExpand();
        self.setdhires();
        self.reg.x = 0xfa;
        self.reg.a = 0x05;
        self.PlaySongI();
        return;
    }

    fn Epilog(&mut self) {
        self.reg.a = self.mem[sym::IIGS];
        if self.reg.a != 0x00 {
            self.SuperEpilog();
            return;
        }
        self.reg.a = 0x76;
        self.mem[sym::RAMRDaux] = self.reg.a;
        self.DblExpand();
        self.setdhires();
        self.reg.a = 0x01;
        self.PlaySongNI();
        self.reg.a = 0x0f;
        self.pauseNI();
        self.unpacksplash();
        self.reg.a = 0x4b;
        self.pauseNI();
        self.reg.a = 0x02;
        self.PlaySongNI();
        self.reg.a = 0x3c;
        self.pauseNI();
        self.blackout();
        return;
    }

    fn unpacksplash(&mut self) {
        self.reg.a = 0x40;
        self.mem[sym::RAMRDaux] = self.reg.a;
        self.DblExpand();
        return;
    }

    fn SuperEpilog(&mut self) {
        self.reg.a = 0x01;  // aux
        self.fadein();
        self.setaux();
        self.reg.a = 0x01;
        self.PlaySongNI();
        self.fadeout();
        self.reg.a = 0x00;  // main
        self.fadein();
        self.setaux();
        self.reg.a = 0x50;
        self.pauseNI();
        self.reg.a = 0x02;
        self.PlaySongNI();
        self.reg.a = 0xff;
        self.pauseNI();
        self.fadeout();
        self._2a();
        return;
    }

    fn Demo(&mut self) {
        self.blackout();
        self.LoadStage3();
        self.setdemolevel();
        self.rdbluep();
        self.driveoff();
        self.reg.a = 0x00;
        self.start();
        return;
    }

    // aliases: :loop
    fn pauseNI(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.mem[sym::pausetemp] = self.reg.a;
                    self.reg.y = 0x14;
                    pc = 1;
                }
                1 => {
                    self.reg.x = 0x00;
                    pc = 2;
                }
                2 => {
                    let _v = self.reg.x.wrapping_sub(1);
                    self.reg.x = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.x != 0x00 {
                        pc = 2;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    let _v = self.reg.y.wrapping_sub(1);
                    self.reg.y = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.y != 0x00 {
                        pc = 1;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.reg.a = self.mem[sym::pausetemp];
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    if self.reg.a != 0x00 {
                        self.pauseNI();
                        return;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn StartGame_3f(&mut self) {
        self.musickeys();
        if self.reg.a < 0x80 {
            return;
        }
        if self.reg.a == 0x04 {
            self.Demo();
            return;
        }
        self.LoadStage3();
        self.set1stlevel();
        self.rdbluep();
        self.driveoff();
        self.mem[sym::musicon] = 0x01;
        self.reg.a = self.mem[sym::keypress];
        if self.reg.a != 0x0c {
            self.reg.a = 0x01;
            self.start();
            return;
        }
        self.reg.a = 0x04;  // arbitrary
        self.startresume();
        return;
    }

    // aliases: DOSTARTGAME
    fn _3a3(&mut self) {
        self.blackout();
        self.LoadStage3();
        self.set1stlevel();
        self.rdbluep();
        self.driveoff();
        self.mem[sym::musicon] = 0x01;
        self.reg.a = self.mem[sym::keypress];
        if self.reg.a != 0x0c {
            self.reg.a = 0x01;
            self.start();
            return;
        }
        self.reg.a = 0x04;  // arbitrary
        self.startresume();
        return;
    }

    fn loadperm(&mut self) {
        self.reg.a = 0x03;
        self.mem[sym::track] = self.reg.a;
        self.setaux();
        self.rw18();
        self.rw18();
        self.setmain();
        self.reg.a = 0x09;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.reg.a = 0x13;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.reg.a = 0x22;
        self.mem[sym::track] = self.reg.a;
        self.rw18();
        self.setaux();
        self.reg.a = 0x01;
        self.mem[sym::MSset] = self.reg.a;
        self.setmain();
        self.Tmoveauxlc();
        return;
    }

    fn LoadStage1A(&mut self) {
        self.driveon();
        self.reg.a = 0x16;
        self._5dlsub();
        self.setmain();
        self.rw18();
        self.rw18();
        self.loadmusic1();
        self.setaux();
        self.reg.a = 0xff;
        self.mem[sym::BGset1] = self.reg.a;
        self.mem[sym::BGset2] = self.reg.a;
        self.mem[sym::CHset] = self.reg.a;
        self.driveoff();
        return;
    }

    fn LoadStage1B(&mut self) {
        self.driveon();
        self.loadmusic3();
        self.reg.a = self.mem[sym::IIGS];
        if self.reg.a != 0x00 {
            self.loadsuper();
            self.driveoff();
            return;
        }
        self.reg.a = 0x12;
        self._5dlsub();
        self.driveoff();
        return;
    }

    fn ReloadStuff(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.driveon();
                    pc = 1;
                }
                1 => {
                    self.reg.a = 0x04;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    self.reg.a = 0x0f;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.driveoff();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn LoadStage2(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.reg.x = self.mem[sym::BBundID];
                    let _o: u8 = 0xad;
                    self.flags.c = self.reg.x >= _o;
                    self.flags.z = self.reg.x == _o;
                    self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.x == 0xad {
                        self.LoadStage2B();
                        return;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.driveon();
                    self.reg.a = 0x00;
                    self.loadch7();
                    self.reg.a = 0x1d;
                    pc = 2;
                }
                2 => {
                    self.mem[sym::track] = self.reg.a;
                    pc = 3;
                }
                3 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 5;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.error();
                    pc = 3;
                }
                5 => {
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.reg.a = 0xff;
                    self.mem[sym::BGset1] = self.reg.a;
                    self.mem[sym::BGset2] = self.reg.a;
                    self.mem[sym::CHset] = self.reg.a;
                    self.driveoff();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn LoadStage2A(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.driveon();
                    self.reg.a = 0x00;
                    self.loadch7();
                    self.reg.a = 0x1d;
                    pc = 1;
                }
                1 => {
                    self.mem[sym::track] = self.reg.a;
                    pc = 2;
                }
                2 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 4;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.error();
                    pc = 2;
                }
                4 => {
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.reg.a = 0xff;
                    self.mem[sym::BGset1] = self.reg.a;
                    self.mem[sym::BGset2] = self.reg.a;
                    self.mem[sym::CHset] = self.reg.a;
                    self.driveoff();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn loadch7(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.mem[sym::recheck0] = self.reg.a;
                    pc = 1;
                }
                1 => {
                    self.reg.a = 0x1c;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    pc = 4;
                }
                4 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn LoadStage2B(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.driveon();
                    self.reg.a = 0x18;
                    if self.reg.a != 0x00 {
                        self._5dls2();
                        return;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.driveon();
                    self.reg.a = 0x04;
                    self.mem[sym::track] = self.reg.a;
                    pc = 2;
                }
                2 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 4;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.error();
                    pc = 2;
                }
                4 => {
                    self.rw18();
                    self.rw18();
                    self.setmain();
                    self.rw18();
                    self.rw18();
                    self.setaux();
                    self.reg.a = 0x0d;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.reg.a = 0x00;
                    self.mem[sym::BGset1] = self.reg.a;
                    self.mem[sym::BGset2] = self.reg.a;
                    self.mem[sym::CHset] = self.reg.a;
                    self.loadmusic2();
                    self.setaux();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn LoadStage3(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.driveon();
                    self.reg.a = 0x04;
                    self.mem[sym::track] = self.reg.a;
                    pc = 1;
                }
                1 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    self.rw18();
                    self.rw18();
                    self.setmain();
                    self.rw18();
                    self.rw18();
                    self.setaux();
                    self.reg.a = 0x0d;
                    self.mem[sym::track] = self.reg.a;
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.reg.a = 0x00;
                    self.mem[sym::BGset1] = self.reg.a;
                    self.mem[sym::BGset2] = self.reg.a;
                    self.mem[sym::CHset] = self.reg.a;
                    self.loadmusic2();
                    self.setaux();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn PlaySongNI(&mut self) {
        self.setaux();
        self.xminit();
        loop {
            self.xmplay();
            let _o: u8 = 0x00;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if !(self.reg.a != 0x00) {
                break;
            }
        }
        return;
    }

    fn PlaySongI(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.setaux();
                    if self.flags.z {
                        pc = 12;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.reg.y = self.reg.a;
                    self.reg.a = self.mem[sym::musicon];
                    self.reg.a &= self.mem[sym::soundon];
                    if self.reg.a == 0x00 {
                        pc = 5;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.reg.a = self.reg.y;
                    self.xminit();
                    pc = 7;
                }
                3 => {
                    self.StartGame_3f();
                    self.xmplay();
                    let _o: u8 = 0x00;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x00 {
                        pc = 7;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    return;
                }
                5 => {
                    self.reg.a = self.reg.x;
                    pc = 6;
                }
                6 => {
                    pc = 7;
                }
                7 => {
                    self.mem[sym::pausetemp] = self.reg.a;
                    self.reg.y = 0x02;
                    pc = 8;
                }
                8 => {
                    self.reg.x = 0x00;
                    pc = 9;
                }
                9 => {
                    self.StartGame_3f();
                    let _v = self.reg.x.wrapping_sub(1);
                    self.reg.x = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.x != 0x00 {
                        pc = 9;
                    } else {
                        pc = 10;
                    }
                }
                10 => {
                    let _v = self.reg.y.wrapping_sub(1);
                    self.reg.y = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.y != 0x00 {
                        pc = 8;
                    } else {
                        pc = 11;
                    }
                }
                11 => {
                    self.reg.a = self.mem[sym::pausetemp];
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    if self.reg.a != 0x00 {
                        pc = 7;
                    } else {
                        pc = 12;
                    }
                }
                12 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    // aliases: :loop
    fn tpause(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.mem[sym::pausetemp] = self.reg.a;
                    self.reg.y = 0x02;
                    pc = 1;
                }
                1 => {
                    self.reg.x = 0x00;
                    pc = 2;
                }
                2 => {
                    self.StartGame_3f();
                    let _v = self.reg.x.wrapping_sub(1);
                    self.reg.x = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.x != 0x00 {
                        pc = 2;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    let _v = self.reg.y.wrapping_sub(1);
                    self.reg.y = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.y != 0x00 {
                        pc = 1;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.reg.a = self.mem[sym::pausetemp];
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    if self.reg.a != 0x00 {
                        self.pauseNI();
                        return;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn error(&mut self) {
        self.driveoff();
        self.prompt();
        self.driveon();
        return;
    }

    fn _5dlsub(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.mem[sym::track] = self.reg.a;
                    pc = 1;
                }
                1 => {
                    self.rw18();
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.error();
                    pc = 1;
                }
                3 => {
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    self.rw18();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }
}
