// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4 skeleton slice: module + routine scaffolding with leaf-
// expression, control-flow, data-movement, carry-arithmetic,
// `(ptr),y` indirect, cmp/bit flag, and 16-bit (`Wide16`) lowering.
// Flags are `self.c`/`self.z`/`self.n: u8` (provisional). SMC, the
// stack, `RawIfStmt`, and `GotoStmt`/`LabelStmt` are deferred; they
// appear as `// raw: …` or `// TODO(pass4): …` comments.
// The `Cpu` receiver and `self.ram`/`self.c`/`self.z`/`self.n` are
// provisional, pending the state/trait design slice. RAM addresses
// keep their source symbol names via the `sym` constants below.
//
// source: 01 POP Source/Source/MASTER.S

#[allow(non_upper_case_globals)]
mod sym {
    pub const BBundID: usize = 0x03f5;
    pub const BGset1: usize = 0x0303;
    pub const BGset2: usize = 0x0304;
    pub const CHset: usize = 0x0305;
    pub const IIGS: usize = 0x0211;
    pub const IMAGE: usize = 0x0004;
    pub const MIXEDoff: usize = 0xc052;
    pub const MSset: usize = 0x0239;
    pub const PAGE2off: usize = 0xc054;
    pub const PAGE2on: usize = 0xc055;
    pub const RAMRDaux: usize = 0xc003;
    pub const RAMRDmain: usize = 0xc002;
    pub const RAMWRTaux: usize = 0xc005;
    pub const RAMWRTmain: usize = 0xc004;
    pub const RWBANK1: usize = 0xc08b;
    pub const RWBANK2: usize = 0xc083;
    pub const bg1trk: usize = 0x022b;
    pub const bg2trk: usize = 0x022c;
    pub const bluepREG: usize = 0x03f1;
    pub const bluepTRK: usize = 0x03f0;
    pub const ch4off: usize = 0x022e;
    pub const ch4trk: usize = 0x022d;
    pub const demolevel: usize = 0x021a;
    pub const firstlevel: usize = 0x021b;
    pub const invert: usize = 0x009f;
    pub const keypress: usize = 0x020f;
    pub const musicon: usize = 0x031a;
    pub const newBGset1: usize = 0x00f6;
    pub const newBGset2: usize = 0x00f7;
    pub const newCHset: usize = 0x00f8;
    pub const params: usize = 0x03f0;
    pub const pausetemp: usize = 0x03f7;
    pub const recheck0: usize = 0x03f8;
    pub const savedgame: usize = 0xb6f0;
    pub const soundon: usize = 0x0203;
    pub const track: usize = 0x00fe;
}

impl Cpu {
    fn FIRSTBOOT(&mut self) {
        self.a = self.ram[sym::MIXEDoff];
        self.setaux();
        self.ram[sym::BBundID] = 0xa9;
        self.ram[sym::RAMWRTmain] = 0xa9;
        self.a = 0x02;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.loadperm();
        self.driveoff();
        self.checkIIGS();
        self.initsystem();
        self.ram[sym::invert] = 0x00;
        self.ram[sym::soundon] = 0x01;
        self.AttractLoop();
        return;
    }

    fn loadmusic1(&mut self) {
        self.setmain();
        self.a = 0x22;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.setaux();
        self.xmovemusic();
        return;
    }

    fn loadmusic2(&mut self) {
        self.setmain();
        self.a = 0x14;
        self.ram[sym::track] = self.a;
        self.rw18();
        // TODO(pass4): lower GotoStmt
    }

    fn loadmusic3(&mut self) {
        self.loadmusic1();
        return;
    }

    fn setaux(&mut self) {
        self.ram[sym::RAMRDaux] = self.a;
        self.ram[sym::RAMWRTaux] = self.a;
        return;
    }

    fn setmain(&mut self) {
        self.ram[sym::RAMRDmain] = self.a;
        self.ram[sym::RAMWRTmain] = self.a;
        return;
    }

    fn driveon(&mut self) {
        self.a = 0x00;
        // raw: patch *:delay = a            ; MASTER.S:302
        self.setaux();
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        self.a = self.ram[sym::BBundID];
        // raw: patch *:IDbyte = a            ; MASTER.S:314
        self.rw18();
        self.rw18();
        return;
    }

    fn driveon1(&mut self) {
        // raw: patch *:delay = a            ; MASTER.S:302
        self.setaux();
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        let _o: u8 = self.ram[sym::RWBANK1];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        self.a = self.ram[sym::BBundID];
        // raw: patch *:IDbyte = a            ; MASTER.S:314
        self.rw18();
        self.rw18();
        return;
    }

    fn driveoff(&mut self) {
        self.rw18();
        let _o: u8 = self.ram[sym::RWBANK2];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        let _o: u8 = self.ram[sym::RWBANK2];
        self.z = ((self.a & _o) == 0) as u8;
        self.n = _o >> 7;
        self.ram[0xc010] = self.a;
        self.setaux();
        return;
    }

    fn set1stlevel(&mut self) {
        self.a = self.ram[sym::firstlevel];
        self.x = self.ram[sym::firstlevel + 1];
        self.ram[sym::params] = self.a;
        self.ram[sym::params + 1] = self.x;
        return;
    }

    fn SetLevel(&mut self) {
        self.ram[sym::params] = self.a;
        self.ram[sym::params + 1] = self.x;
        return;
    }

    fn setdemolevel(&mut self) {
        self.a = self.ram[sym::demolevel];
        self.x = self.ram[sym::demolevel + 1];
        self.SetLevel();
        return;
    }

    fn checkdisk(&mut self) {
        self.setaux();
        self.x = 0xad;
        self.ram[sym::BBundID] = self.x;
        self.driveon();
        // TODO(pass4): lower LabelStmt
        self.setmain();
        self.a = 0x16;
        self.ram[sym::track] = self.a;
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        return;
    }

    fn SAVEGAME(&mut self) {
        self.checkdisk();
        self.ram[sym::RAMRDaux] = self.a;
        self.x = 0x0f;
        loop {
            self.a = self.ram[sym::savedgame + self.x as usize];
            self.ram[0x0200 + self.x as usize] = self.a;
            self.x = self.x.wrapping_sub(0x01);
            if !((self.x as i8) >= 0) {
                break;
            }
        }
        self.ram[sym::RAMRDmain] = self.a;
        self.a = 0x17;
        self.ram[sym::track] = self.a;
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.driveoff();
        return;
    }

    fn LOADGAME(&mut self) {
        self.checkdisk();
        self.a = 0x17;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.ram[sym::RAMWRTaux] = self.a;
        self.x = 0x0f;
        loop {
            self.a = self.ram[0x0200 + self.x as usize];
            self.ram[sym::savedgame + self.x as usize] = self.a;
            self.x = self.x.wrapping_sub(0x01);
            if !((self.x as i8) >= 0) {
                break;
            }
        }
        self.driveoff();
        return;
    }

    fn LOADALTSET(&mut self) {
        self.ram[sym::newCHset] = self.y;
        self.driveon();
        self.rdch4();
        self.driveoff();
        return;
    }

    fn LOADLEVEL(&mut self) {
        self.ram[sym::newBGset1] = self.a;
        self.ram[sym::newBGset2] = self.x;
        self.ram[sym::newCHset] = self.y;
        self.driveon();
        self.rdbluep();
        self.rdbg1();
        self.rdbg2();
        self.rdch4();
        self.vidstuff();
        self.driveoff();
        return;
    }

    fn setbluep(&mut self) {
        self.ram[sym::track] = self.ram[sym::bluepTRK];
        self.a = self.ram[sym::bluepREG];
        return;
    }

    fn vidstuff(&mut self) {
        self.a = self.ram[sym::BBundID];
        let _o: u8 = 0xad;
        self.c = (self.a >= _o) as u8;
        self.z = (self.a == _o) as u8;
        self.n = self.a.wrapping_sub(_o) >> 7;
        if self.a != 0xad {
            return;
        }
        self.a = self.ram[0xc000];
        let _o: u8 = 0x5e;
        self.c = (self.a >= _o) as u8;
        self.z = (self.a == _o) as u8;
        self.n = self.a.wrapping_sub(_o) >> 7;
        if self.a != 0x5e {
            return;
        }
        self.setmain();
        self.a = 0x0c;
        self.ram[sym::track] = self.a;
        self.rw18();
        loop {
            self.rw18();
            // raw: ??? lda :sm            ; MASTER.S:509
            self.c = 0;
            let _r = (self.a as u16) + (0x12) as u16 + (self.c as u16);
            self.a = _r as u8;
            self.c = (_r >> 8) as u8;
            // raw: patch *:sm = a            ; MASTER.S:512
            let _o: u8 = 0x6c;
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if !(self.a < 0x6c) {
                break;
            }
        }
        self.driveoff();
        self.setmain();
        self.$c00();
        return;
    }

    fn rdbg1(&mut self) {
        self.x = self.ram[sym::newBGset1];
        if self.x == self.ram[sym::BGset1] {
            return;
        }
        self.ram[sym::BGset1] = self.x;
        self.a = self.ram[sym::bg1trk + self.x as usize];
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        return;
    }

    fn rdbg2(&mut self) {
        self.x = self.ram[sym::newBGset2];
        if self.x == self.ram[sym::BGset2] {
            return;
        }
        self.ram[sym::BGset2] = self.x;
        self.a = self.ram[sym::bg2trk + self.x as usize];
        self.ram[sym::track] = self.a;
        self.rw18();
        return;
    }

    fn rdch4(&mut self) {
        self.x = self.ram[sym::newCHset];
        if self.x == self.ram[sym::CHset] {
            return;
        }
        self.ram[sym::CHset] = self.x;
        self.ram[sym::track] = self.ram[sym::ch4trk + self.x as usize];
        self.a = self.ram[sym::ch4off + self.x as usize];
        match self.a {
            0x00 => {
                self.rw18();
                self.rw18();
                return;
            }
            0x06 => {
                self.rw18();
                self.rw18();
                return;
            }
            0x0c => {
                self.rw18();
                self.rw18();
                return;
            }
            _ => {}
        }
        return;
    }

    fn rdbluep(&mut self) {
        self.setbluep();
        // TODO(pass4): lower RawIfStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        return;
    }

    fn copy1to2(&mut self) {
        self.a = 0x40;
        self.x = 0x20;
        if self.x == 0x00 {
            self.a = 0x20;
            self.x = 0x40;
        }
        self.ram[sym::IMAGE + 1] = self.a;
        self.ram[sym::IMAGE] = self.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn copy2to1(&mut self) {
        self.a = 0x20;
        self.x = 0x40;
        self.ram[sym::IMAGE + 1] = self.a;
        self.ram[sym::IMAGE] = self.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn copydhires(&mut self) {
        self.ram[sym::IMAGE + 1] = self.a;
        self.ram[sym::IMAGE] = self.x;
        self._copy2000aux();
        self._copy2000();
        return;
    }

    fn CUTPRINCESS(&mut self) {
        self.blackout();
        self.a = 0x01;
        self.LoadStage2();
        self.a = 0x84;
        self.SngExpand();
        self.ram[sym::IMAGE + 1] = 0x40;
        self.a = 0x20;
        self.ram[sym::IMAGE] = self.a;
        self._copy2000();
        return;
    }

    fn cutprincess1(&mut self) {
        self.LoadStage2();
        self.a = 0x84;
        self.SngExpand();
        self.ram[sym::IMAGE + 1] = 0x40;
        self.a = 0x20;
        self.ram[sym::IMAGE] = self.a;
        self._copy2000();
        return;
    }

    fn EPILOG(&mut self) {
        self.a = 0x01;
        self.ram[sym::soundon] = self.a;
        self.ram[sym::musicon] = self.a;
        self.blackout();
        self.LoadStage1B();
        self.Epilog();
        self.a = 0xa9;
        self.ram[sym::BBundID] = self.a;
        self.ram[0xc010] = self.a;
        loop {
            self.a = self.ram[0xc000];
            if !((self.a as i8) >= 0) {
                break;
            }
        }
        self.a = 0x01;
        self.ram[sym::musicon] = self.a;
        self.SetupDHires();
        self.PubCredit();
        self.AuthorCredit();
        self.TitleScreen();
        self.Prolog1();
        self.PrincessScene();
        self.SetupDHires();
        self.Prolog2();
        self.SilentTitle();
        self.Demo();
        return;
    }

    // aliases: AttractLoop
    fn ATTRACTMODE(&mut self) {
        self.a = 0x01;
        self.ram[sym::musicon] = self.a;
        self.SetupDHires();
        self.PubCredit();
        self.AuthorCredit();
        self.TitleScreen();
        self.Prolog1();
        self.PrincessScene();
        self.SetupDHires();
        self.Prolog2();
        self.SilentTitle();
        self.Demo();
        return;
    }

    fn SetupDHires(&mut self) {
        self.blackout();
        self.LoadStage1A();
        return;
    }

    fn PubCredit(&mut self) {
        self.unpacksplash();
        self.setdhires();
        self.copy1to2();
        self.a = 0x2c;
        self.tpause();
        self.a = 0x70;
        self.DeltaExpPop();
        self.x = 0x50;
        self.a = 0x01;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn CleanScreen(&mut self) {
        self.a = self.ram[sym::PAGE2on];
        self.copy2to1();
        self.a = self.ram[sym::PAGE2off];
        return;
    }

    fn AuthorCredit(&mut self) {
        self.a = 0x2a;
        self.tpause();
        self.a = 0x72;
        self.DeltaExpPop();
        self.x = 0x50;
        self.a = 0x02;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn SilentTitle(&mut self) {
        self.unpacksplash();
        self.copy1to2();
        self.a = 0x14;
        self.tpause();
        self.a = 0x74;
        self.DeltaExpPop();
        self.a = 0xa0;
        self.tpause();
        return;
    }

    fn TitleScreen(&mut self) {
        self.a = 0x26;
        self.tpause();
        self.a = 0x74;
        self.DeltaExpPop();
        self.x = 0x8c;
        self.a = 0x03;
        self.PlaySongI();
        self.CleanScreen();
        return;
    }

    fn Prolog1(&mut self) {
        self.a = 0x7c;
        self.ram[sym::RAMRDaux] = self.a;
        self.DblExpand();
        self.x = 0xfa;
        self.a = 0x04;
        self.PlaySongI();
        return;
    }

    fn PrincessScene(&mut self) {
        self.blackout();
        self.ReloadStuff();
        self.a = 0x00;
        self.cutprincess1();
        self.a = 0x00;
        self.xplaycut();
        return;
    }

    fn Prolog2(&mut self) {
        self.a = 0x60;
        self.ram[sym::RAMRDmain] = self.a;
        self.DblExpand();
        self.setdhires();
        self.x = 0xfa;
        self.a = 0x05;
        self.PlaySongI();
        return;
    }

    fn Epilog(&mut self) {
        self.a = self.ram[sym::IIGS];
        if self.a != 0x00 {
            self.SuperEpilog();
            return;
        }
        self.a = 0x76;
        self.ram[sym::RAMRDaux] = self.a;
        self.DblExpand();
        self.setdhires();
        self.a = 0x01;
        self.PlaySongNI();
        self.a = 0x0f;
        self.pauseNI();
        self.unpacksplash();
        self.a = 0x4b;
        self.pauseNI();
        self.a = 0x02;
        self.PlaySongNI();
        self.a = 0x3c;
        self.pauseNI();
        self.blackout();
        return;
    }

    fn unpacksplash(&mut self) {
        self.a = 0x40;
        self.ram[sym::RAMRDaux] = self.a;
        self.DblExpand();
        return;
    }

    fn SuperEpilog(&mut self) {
        self.a = 0x01;
        self.fadein();
        self.setaux();
        self.a = 0x01;
        self.PlaySongNI();
        self.fadeout();
        self.a = 0x00;
        self.fadein();
        self.setaux();
        self.a = 0x50;
        self.pauseNI();
        self.a = 0x02;
        self.PlaySongNI();
        self.a = 0xff;
        self.pauseNI();
        self.fadeout();
        self.*();
        return;
    }

    fn Demo(&mut self) {
        self.blackout();
        self.LoadStage3();
        self.setdemolevel();
        self.rdbluep();
        self.driveoff();
        self.a = 0x00;
        self.start();
        return;
    }

    // aliases: :loop
    fn pauseNI(&mut self) {
        self.ram[sym::pausetemp] = self.a;
        self.y = 0x14;
        // TODO(pass4): lower LabelStmt
        self.x = 0x00;
        // TODO(pass4): lower LabelStmt
        self.x = self.x.wrapping_sub(1);
        if self.x != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.y = self.y.wrapping_sub(1);
        if self.y != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.a = self.ram[sym::pausetemp];
        self.c = 1;
        let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        if self.a != 0x00 {
            self.:loop();
            return;
        }
        // TODO(pass4): lower LabelStmt
        return;
    }

    fn StartGame?(&mut self) {
        self.musickeys();
        if self.a < 0x80 {
            return;
        }
        if self.a == 0x04 {
            self.Demo();
            return;
        }
        self.LoadStage3();
        self.set1stlevel();
        self.rdbluep();
        self.driveoff();
        self.ram[sym::musicon] = 0x01;
        self.a = self.ram[sym::keypress];
        if self.a != 0x0c {
            self.a = 0x01;
            self.start();
            return;
        }
        self.a = 0x04;
        self.startresume();
        return;
    }

    // aliases: DOSTARTGAME
    fn :3(&mut self) {
        self.blackout();
        self.LoadStage3();
        self.set1stlevel();
        self.rdbluep();
        self.driveoff();
        self.ram[sym::musicon] = 0x01;
        self.a = self.ram[sym::keypress];
        if self.a != 0x0c {
            self.a = 0x01;
            self.start();
            return;
        }
        self.a = 0x04;
        self.startresume();
        return;
    }

    fn loadperm(&mut self) {
        self.a = 0x03;
        self.ram[sym::track] = self.a;
        self.setaux();
        self.rw18();
        self.rw18();
        self.setmain();
        self.a = 0x09;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0x13;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0x22;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.setaux();
        self.a = 0x01;
        self.ram[sym::MSset] = self.a;
        self.setmain();
        self.Tmoveauxlc();
        return;
    }

    fn LoadStage1A(&mut self) {
        self.driveon();
        self.a = 0x16;
        self.]lsub();
        self.setmain();
        self.rw18();
        self.rw18();
        self.loadmusic1();
        self.setaux();
        self.a = 0xff;
        self.ram[sym::BGset1] = self.a;
        self.ram[sym::BGset2] = self.a;
        self.ram[sym::CHset] = self.a;
        self.driveoff();
        return;
    }

    fn LoadStage1B(&mut self) {
        self.driveon();
        self.loadmusic3();
        self.a = self.ram[sym::IIGS];
        if self.a != 0x00 {
            self.loadsuper();
            self.driveoff();
            return;
        }
        self.a = 0x12;
        self.]lsub();
        self.driveoff();
        return;
    }

    fn ReloadStuff(&mut self) {
        self.driveon();
        // TODO(pass4): lower LabelStmt
        self.a = 0x04;
        self.ram[sym::track] = self.a;
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.a = 0x0f;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.driveoff();
        return;
    }

    fn LoadStage2(&mut self) {
        self.x = self.ram[sym::BBundID];
        let _o: u8 = 0xad;
        self.c = (self.x >= _o) as u8;
        self.z = (self.x == _o) as u8;
        self.n = self.x.wrapping_sub(_o) >> 7;
        if self.x == 0xad {
            self.LoadStage2B();
            return;
        }
        // TODO(pass4): lower LabelStmt
        self.driveon();
        self.a = 0x00;
        self.loadch7();
        self.a = 0x1d;
        // TODO(pass4): lower LabelStmt
        self.ram[sym::track] = self.a;
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0xff;
        self.ram[sym::BGset1] = self.a;
        self.ram[sym::BGset2] = self.a;
        self.ram[sym::CHset] = self.a;
        self.driveoff();
        return;
    }

    fn LoadStage2A(&mut self) {
        self.driveon();
        self.a = 0x00;
        self.loadch7();
        self.a = 0x1d;
        // TODO(pass4): lower LabelStmt
        self.ram[sym::track] = self.a;
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0xff;
        self.ram[sym::BGset1] = self.a;
        self.ram[sym::BGset2] = self.a;
        self.ram[sym::CHset] = self.a;
        self.driveoff();
        return;
    }

    fn loadch7(&mut self) {
        self.ram[sym::recheck0] = self.a;
        // TODO(pass4): lower LabelStmt
        self.a = 0x1c;
        self.ram[sym::track] = self.a;
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        // TODO(pass4): lower LabelStmt
        return;
    }

    fn LoadStage2B(&mut self) {
        self.driveon();
        self.a = 0x18;
        if self.a != 0x00 {
            self.]ls2();
            return;
        }
        // TODO(pass4): lower LabelStmt
        self.driveon();
        self.a = 0x04;
        self.ram[sym::track] = self.a;
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        self.rw18();
        self.setmain();
        self.rw18();
        self.rw18();
        self.setaux();
        self.a = 0x0d;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0x00;
        self.ram[sym::BGset1] = self.a;
        self.ram[sym::BGset2] = self.a;
        self.ram[sym::CHset] = self.a;
        self.loadmusic2();
        self.setaux();
        return;
    }

    fn LoadStage3(&mut self) {
        self.driveon();
        self.a = 0x04;
        self.ram[sym::track] = self.a;
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        self.rw18();
        self.setmain();
        self.rw18();
        self.rw18();
        self.setaux();
        self.a = 0x0d;
        self.ram[sym::track] = self.a;
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        self.a = 0x00;
        self.ram[sym::BGset1] = self.a;
        self.ram[sym::BGset2] = self.a;
        self.ram[sym::CHset] = self.a;
        self.loadmusic2();
        self.setaux();
        return;
    }

    fn PlaySongNI(&mut self) {
        self.setaux();
        self.xminit();
        loop {
            self.xmplay();
            let _o: u8 = 0x00;
            self.c = (self.a >= _o) as u8;
            self.z = (self.a == _o) as u8;
            self.n = self.a.wrapping_sub(_o) >> 7;
            if !(self.a != 0x00) {
                break;
            }
        }
        return;
    }

    fn PlaySongI(&mut self) {
        self.setaux();
        // TODO(pass4): lower RawIfStmt
        self.y = self.a;
        self.a = self.ram[sym::musicon];
        self.a &= self.ram[sym::soundon];
        if self.a == 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.a = self.y;
        self.xminit();
        // TODO(pass4): lower LabelStmt
        self.StartGame?();
        self.xmplay();
        let _o: u8 = 0x00;
        self.c = (self.a >= _o) as u8;
        self.z = (self.a == _o) as u8;
        self.n = self.a.wrapping_sub(_o) >> 7;
        if self.a != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        // TODO(pass4): lower LabelStmt
        return;
        // TODO(pass4): lower LabelStmt
        self.a = self.x;
        // TODO(pass4): lower LabelStmt
        // TODO(pass4): lower LabelStmt
        self.ram[sym::pausetemp] = self.a;
        self.y = 0x02;
        // TODO(pass4): lower LabelStmt
        self.x = 0x00;
        // TODO(pass4): lower LabelStmt
        self.StartGame?();
        self.x = self.x.wrapping_sub(1);
        if self.x != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.y = self.y.wrapping_sub(1);
        if self.y != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.a = self.ram[sym::pausetemp];
        self.c = 1;
        let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        if self.a != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        // TODO(pass4): lower LabelStmt
        return;
    }

    // aliases: :loop
    fn tpause(&mut self) {
        self.ram[sym::pausetemp] = self.a;
        self.y = 0x02;
        // TODO(pass4): lower LabelStmt
        self.x = 0x00;
        // TODO(pass4): lower LabelStmt
        self.StartGame?();
        self.x = self.x.wrapping_sub(1);
        if self.x != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.y = self.y.wrapping_sub(1);
        if self.y != 0x00 {
            // TODO(pass4): lower GotoStmt
        }
        self.a = self.ram[sym::pausetemp];
        self.c = 1;
        let _r = (self.a as u16) + (!0x01_u8) as u16 + (self.c as u16);
        self.a = _r as u8;
        self.c = (_r >> 8) as u8;
        if self.a != 0x00 {
            self.:loop();
            return;
        }
        // TODO(pass4): lower LabelStmt
        return;
    }

    fn error(&mut self) {
        self.driveoff();
        self.prompt();
        self.driveon();
        return;
    }

    fn ]lsub(&mut self) {
        self.ram[sym::track] = self.a;
        // TODO(pass4): lower LabelStmt
        self.rw18();
        // TODO(pass4): lower RawIfStmt
        self.error();
        // TODO(pass4): lower GotoStmt
        // TODO(pass4): lower LabelStmt
        self.rw18();
        self.rw18();
        self.rw18();
        self.rw18();
        return;
    }
}
