// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4: module + routine scaffolding with leaf-expression,
// control-flow, data-movement, carry-arithmetic, `(ptr),y` indirect,
// cmp/bit flag, 16-bit (`Wide16`), dispatch-fallback, stack, and SMC
// operand-patch lowering.
//
// State is decomposed into `Cpu { reg, flags, mem, stack, smc }`:
// registers `self.reg.{a,x,y}: u8`, flags `self.flags.{c,z,n,i,d}:
// bool`, memory `self.mem[addr]` (64 KiB), the `pha`/`pla` value
// stack `self.stack: Vec<u8>`, and recognised SMC operand variables
// `self.smc.<name>` (immediate) / `self.smc.<name>_lo`/`_hi`
// (address). RAM addresses keep their source symbol names via the
// `sym` constants below. Cross-module routine calls resolve once the
// modules are compiled together; opcode / branch-target SMC stays
// deferred as `// raw: …` comments.
//
// source: 01 POP Source/Source/SOUND.S

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
    // Local-label / Merlin-variable byte store, keyed by symbolic
    // `(name, offset)`: StoreLocal writes, LoadLocal/CmpLocal read.
    pub local: std::collections::HashMap<(&'static str, u8), u8>,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
            local: std::collections::HashMap::new(),
        }
    }

    // Register loads/transfers/arith set Z (result == 0) and N
    // (bit 7) on the 6502; these helpers keep that in one place so
    // every reg write stays flag-faithful. `set_nz` is for ops that
    // write memory but still set Z/N (inc/dec/shift on memory).
    #[inline]
    pub fn set_nz(&mut self, v: u8) {
        self.flags.z = v == 0;
        self.flags.n = (v >> 7) != 0;
    }
    #[inline]
    pub fn set_a(&mut self, v: u8) { self.reg.a = v; self.set_nz(v); }
    #[inline]
    pub fn set_x(&mut self, v: u8) { self.reg.x = v; self.set_nz(v); }
    #[inline]
    pub fn set_y(&mut self, v: u8) { self.reg.y = v; self.set_nz(v); }
}

#[allow(non_upper_case_globals)]
mod sym {
    pub const lookup: usize = 0x02f1;
    pub const savex: usize = 0x02f0;
    pub const soundon: usize = 0x0203;
    pub const soundtable: usize = 0xb6c0;
    pub const spkr: usize = 0xc030;
}

impl Cpu {
    // aliases: lookup, endlook
    fn ZEROSOUND(&mut self) {
        self.set_a(0x00);  // # sounds in table
        self.mem[sym::soundtable] = self.reg.a;
        return;
    }

    fn ADDSOUND(&mut self) {
        self.mem[sym::savex] = self.reg.x;
        self.set_x(self.mem[sym::soundtable]);
        if self.reg.x < 0x20 {
            self.set_x(self.reg.x.wrapping_add(1));
            self.mem[(sym::soundtable + self.reg.x as usize) & 0xffff] = self.reg.a;
            self.mem[sym::soundtable] = self.reg.x;
        }
        self.set_x(self.mem[sym::savex]);
        return;
    }

    fn PLAYBACK(&mut self) {
        self.set_a(self.mem[sym::soundon]);
        if self.reg.a == 0x00 {
        } else {
            self.set_x(self.mem[sym::soundtable]);
            if self.reg.x == 0x00 {
            } else {
                loop {
                    self.set_a(self.mem[(sym::soundtable + self.reg.x as usize) & 0xffff]);
                    self.mem[sym::savex] = self.reg.x;
                    self.makesound();
                    self.set_x(self.mem[sym::savex]);
                    self.set_x(self.reg.x.wrapping_sub(1));
                    if !(self.reg.x != 0x00) {
                        break;
                    }
                }
            }
        }
        return;
    }

    fn makesound(&mut self) {
        self.flags.c = (self.reg.a >> 7) != 0;
        self.set_a(self.reg.a.wrapping_shl(1));
        if self.reg.a >= 0x28 {
            return;
        }
        self.set_x(self.reg.a);
        self.set_a(self.mem[(sym::lookup + self.reg.x as usize) & 0xffff]);
        self.local.insert((":sm", 1), self.reg.a);
        self.set_a(self.mem[(sym::lookup + 1 + self.reg.x as usize) & 0xffff]);
        self.local.insert((":sm", 2), self.reg.a);
        self._24ffff();
        return;
    }

    fn DoPlateDown(&mut self) {
        self.set_y(0x46);
        self.set_x(0x00);
        self.set_a(0x04);
        self.tone();
        return;
    }

    fn DoPlateUp(&mut self) {
        self.set_y(0x5a);
        self.set_x(0x00);
        self.set_a(0x04);
        self.tone();
        return;
    }

    fn DoGateDown(&mut self) {
        self.set_y(0x46);
        self.set_x(0x00);
        self.set_a(0x04);
        self.tone();
        return;
    }

    fn DoJawsClash(&mut self) {
        self.set_y(0x0a);
        self.set_x(0x00);
        self.set_a(0x32);
        self.tone();
        return;
    }

    // aliases: DoSwordClash1, DoSwordClash2
    fn DoSpecialKey1(&mut self) {
        self.set_y(0x0f);
        self.set_x(0x00);
        self.set_a(0x32);
        self.tone();
        return;
    }

    fn DoSpecialKey2(&mut self) {
        self.set_y(0x28);
        self.set_x(0x00);
        self.set_a(0x32);
        self.tone();
        return;
    }

    fn DoSplat(&mut self) {
        self.set_y(0xe8);
        self.set_x(0x03);
        self.set_a(0x03);
        self.tone();
        return;
    }

    fn DoMirrorCrack(&mut self) {
        self.DoSplat();
        return;
    }

    fn DoLooseCrash(&mut self) {
        self.DoSplat();
        return;
    }

    // aliases: DoFlashMsg
    fn DoGotKey(&mut self) {
        self.set_a(0x02);
        loop {
            let tmp0 = self.reg.a;
            self.set_y(0xf4);
            self.set_x(0x01);
            self.set_a(0x0f);
            self.tone();
            self.set_y(0x64);
            self.set_x(0x00);
            self.set_a(0x19);
            self.tone();
            self.reg.a = tmp0;
            self.flags.c = true;
            let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
            self.flags.c = (_r >> 8) != 0;
            self.set_a(_r as u8);
            if !(self.reg.a != 0x00) {
                break;
            }
        }
        return;
    }

    fn DoFootstep(&mut self) {
        self.set_y(0x23);
        self.set_x(0x00);
        self.set_a(0x03);
        self.tone();
        return;
    }

    fn DoRaisingExit(&mut self) {
        self.set_y(0x28);
        self.set_x(0x00);
        self.set_a(0x06);
        self.tone();
        return;
    }

    fn DoRaisingGate(&mut self) {
        self.set_y(0x14);
        self.set_x(0x00);
        self.set_a(0x02);
        self.tone();
        return;
    }

    fn DoLowerGate(&mut self) {
        self.set_y(0x07);
        self.set_x(0x00);
        self.set_a(0x08);
        self.tone();
        return;
    }

    fn DoSmackWall(&mut self) {
        self.set_y(0xe8);
        self.set_x(0x03);
        self.set_a(0x03);
        self.tone();
        return;
    }

    fn DoImpaled(&mut self) {
        self.DoSmackWall();
        return;
    }

    fn DoGateSlam(&mut self) {
        self.DoSmackWall();
        return;
    }

    fn tone(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.local.insert((":pitch", 0), self.reg.y);
                    self.local.insert((":pitch", 1), self.reg.x);
                    pc = 1;
                }
                1 => {
                    let _o: u8 = self.mem[sym::spkr];
                    self.flags.z = (self.reg.a & _o) == 0;
                    self.flags.n = (_o >> 7) != 0;
                    self.set_x(0x00);
                    pc = 2;
                }
                2 => {
                    self.set_y(0x00);
                    pc = 3;
                }
                3 => {
                    self.set_y(self.reg.y.wrapping_add(1));
                    let _o: u8 = self.local.get(&(":pitch", 0)).copied().unwrap_or(0);
                    self.flags.c = self.reg.y >= _o;
                    self.flags.z = self.reg.y == _o;
                    self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                    if !self.flags.c {
                        pc = 3;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.set_x(self.reg.x.wrapping_add(1));
                    let _o: u8 = self.local.get(&(":pitch", 1)).copied().unwrap_or(0);
                    self.flags.c = self.reg.x >= _o;
                    self.flags.z = self.reg.x == _o;
                    self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
                    if !self.flags.c {
                        pc = 2;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
                    self.flags.c = (_r >> 8) != 0;
                    self.set_a(_r as u8);
                    if self.reg.a != 0x00 {
                        pc = 1;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    return;
                }
                7 => {
                    // build-time RW18 disk write (no bytes emitted): usr $a9,20,$e00,*-org  ; SOUND.S:359
                    return;
                }
                _ => unreachable!(),
            }
        }
    }
}
