// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4: module + routine scaffolding with leaf-expression,
// control-flow, data-movement, carry-arithmetic, `(ptr),y` indirect,
// cmp/bit flag, 16-bit (`Wide16`), dispatch-fallback, stack, and SMC
// operand-patch lowering.
//
// State is decomposed into `Cpu { reg, flags, mem, stack, smc }`:
// registers `self.reg.{a,x,y}: u8`, flags `self.flags.{c,z,n,i,d}:
// bool`, memory `self.mem[addr]` (64 KiB), the `pha`/`pla` value
// stack `self.stack: Vec<u8>`, and recognised SMC operand variables
// `self.smc.<name>` (immediate) / `self.smc.<name>_lo`/`_hi`
// (address). RAM addresses keep their source symbol names via the
// `sym` constants below. Cross-module routine calls resolve once the
// modules are compiled together; opcode / branch-target SMC stays
// deferred as `// raw: …` comments.
//
// source: 01 POP Source/Source/SPECIALK.S

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
    pub sm1: u8,
    pub sm2: u8,
    pub smod_hi: u8,
    pub smod_lo: u8,
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
        }
    }
}

#[allow(non_upper_case_globals)]
mod sym {
    pub const AMtimer: usize = 0x00c7;
    pub const BBundID: usize = 0x03f5;
    pub const BOTCUT: usize = 0x0013;
    pub const BlockBot: usize = 0x1279;
    pub const BlueSpec: usize = 0x0026;
    pub const BlueType: usize = 0x0024;
    pub const ChgKidStr: usize = 0x00cf;
    pub const ChgOppStr: usize = 0x00d2;
    pub const FrameCount: usize = 0x0306;
    pub const JSTKX: usize = 0x0018;
    pub const JSTKY: usize = 0x0019;
    pub const KidBlockY: usize = 0x0055;
    pub const KidLife: usize = 0x005f;
    pub const KidY: usize = 0x0052;
    pub const ManCtrl: usize = 0x00de;
    pub const MinLeft: usize = 0x0300;
    pub const NextLevel: usize = 0x031c;
    pub const NextTimeMsg: usize = 0x0301;
    pub const OFFSET: usize = 0x0003;
    pub const PAGE: usize = 0x0000;
    pub const SINGSTEP: usize = 0x0021;
    pub const SPEED: usize = 0x030c;
    pub const SavLevel: usize = 0xb6f0;
    pub const SecLeft: usize = 0x0302;
    pub const SongCount: usize = 0x0308;
    pub const SongCue: usize = 0x0319;
    pub const VisScrn: usize = 0x00cb;
    pub const XCO: usize = 0x0001;
    pub const YCO: usize = 0x0002;
    pub const blackflag: usize = 0x0022;
    pub const btn: usize = 0x003d;
    pub const clrB: usize = 0x00d5;
    pub const clrD: usize = 0x00d7;
    pub const clrDESEL: usize = 0x0313;
    pub const clrF: usize = 0x00d4;
    pub const clrSEL: usize = 0x030e;
    pub const clrU: usize = 0x00d6;
    pub const clrbtn: usize = 0x00d8;
    pub const develment: usize = 0x020e;
    pub const fredbuf: usize = 0x5e78;
    pub const guardprog: usize = 0x00dd;
    pub const kbdX: usize = 0x0039;
    pub const kbdY: usize = 0x003a;
    pub const keybuf: usize = 0x03ac;
    pub const keybufptr: usize = 0x00ca;
    pub const keydown: usize = 0x0210;
    pub const keypress: usize = 0x020f;
    pub const level: usize = 0x03f4;
    pub const msgtimer: usize = 0x00db;
    pub const redrawflg: usize = 0x0097;
    pub const soundtable: usize = 0xb6c0;
    pub const timerequest: usize = 0x031f;
    pub const timetable: usize = 0x0332;
    pub const torchclip: usize = 0x032d;
    pub const torchcount: usize = 0x032e;
    pub const torchstate: usize = 0x032c;
    pub const torchx: usize = 0x032a;
    pub const torchy: usize = 0x032b;
}

impl Cpu {
    fn KEYS(&mut self) {
        self.reg.a = self.mem[sym::SINGSTEP];
        if self.reg.a == 0x00 {
            self.KEYS1();
            return;
        }
        loop {
            self.reg.a = self.mem[0xc000];
            if !((self.reg.a as i8) >= 0) {
                break;
            }
        }
        let _o: u8 = 0x9b;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a == 0x9b {
            self.reg.a = 0x01;
            self.mem[sym::SINGSTEP] = self.reg.a;
            self.mem[0xc010] = self.reg.a;
            self.mem[sym::keypress] = self.reg.a;
            return;
        }
        self.reg.x = 0x00;
        self.mem[sym::SINGSTEP] = self.reg.x;
        self.reg.a = 0x00;
        if self.reg.a == 0x00 {
            self.KEYS2();
            return;
        }
        self.reg.a = 0x01;
        self.mem[sym::SINGSTEP] = self.reg.a;
        self.mem[0xc010] = self.reg.a;
        self.mem[sym::keypress] = self.reg.a;
        return;
    }

    fn freeze(&mut self) {
        self.reg.a = self.mem[0xc000];
        if (self.reg.a as i8) >= 0 {
            self.freeze();
            return;
        }
        if self.reg.a != 0x9b {
            self.reg.x = 0x00;
            self.mem[sym::SINGSTEP] = self.reg.x;
            self.reg.a = 0x00;
            if self.reg.a == 0x00 {
                self.KEYS2();
                return;
            }
        }
        self.reg.a = 0x01;
        self.mem[sym::SINGSTEP] = self.reg.a;
        self.mem[0xc010] = self.reg.a;
        self.mem[sym::keypress] = self.reg.a;
        return;
    }

    fn KEYS1(&mut self) {
        self.mem[sym::keypress] = self.mem[0xc000];
        self.mem[sym::keydown] = self.mem[0xc010];
        self.KREAD();
        self.reg.a = self.mem[sym::keypress];
        if (self.reg.a as i8) >= 0 {
            return;
        }
        'b13: {
            self.reg.x = self.mem[sym::develment];
            if self.reg.x != 0x00 {
                let _o: u8 = 0x30;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a >= 0x30 {
                    let _o: u8 = 0x3a;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a < 0x3a {
                        self.reg.a = 0x1a;
                        self.reg.x = 0x03;
                        self.checkcode();
                        if !self.flags.z {
                            self.reg.a = 0x1b;
                            self.reg.x = 0x03;
                            self.checkcode();
                            if !self.flags.z {
                                break 'b13;
                            } else {
                                self.reg.a = 0x0a;
                                if self.reg.a == 0x00 {
                                    break 'b13;
                                }
                            }
                        } else {
                            self.reg.a = 0x00;
                        }
                        self.flags.c = false;
                        let _r = (self.reg.a as u16) + self.mem[sym::keypress] as u16 + (self.flags.c as u16);
                        self.reg.a = _r as u8;
                        self.flags.c = (_r >> 8) != 0;
                        self.flags.c = true;
                        let _r = (self.reg.a as u16) + (!0x30_u8) as u16 + (self.flags.c as u16);
                        self.reg.a = _r as u8;
                        self.flags.c = (_r >> 8) != 0;
                        let _o: u8 = 0x04;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a < 0x04 {
                            return;
                        }
                        let _o: u8 = 0x0d;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a >= 0x0d {
                            return;
                        }
                        self.mem[sym::NextLevel] = self.reg.a;
                        self.shortentime();
                        return;
                    }
                }
            }
        }
        self.reg.a = self.mem[sym::keypress];
        self.addkey();
        self.reg.a = 0x19;
        self.reg.x = 0x03;
        self.checkcode();
        if !self.flags.z {
            self.reg.a = 0x18;
            self.reg.x = 0x03;
            self.checkcode();
            if self.flags.z {
                self.reg.a = 0x03;
                self.reg.x = self.mem[sym::develment];
                if self.reg.x != 0x00 {
                    self.reg.a = 0x0b;
                }
                let _o: u8 = self.mem[sym::level];
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a >= self.mem[sym::level] {
                    self.mem[sym::NextLevel] = self.mem[sym::NextLevel].wrapping_add(1);
                    self.shortentime();
                }
            }
            self.LegitKeys();
            self.DevelKeys();
            self.TempDevel();
            return;
        }
        self.reg.a = 0x01;
        self.mem[sym::develment] = self.reg.a;
        self.gtone();
        return;
    }

    fn KEYS2(&mut self) {
        self.mem[sym::keypress] = self.reg.a;
        self.mem[sym::keydown] = self.mem[0xc010];
        self.KREAD();
        self.reg.a = self.mem[sym::keypress];
        if (self.reg.a as i8) >= 0 {
            return;
        }
        'b12: {
            self.reg.x = self.mem[sym::develment];
            if self.reg.x != 0x00 {
                let _o: u8 = 0x30;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a >= 0x30 {
                    let _o: u8 = 0x3a;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a < 0x3a {
                        self.reg.a = 0x1a;
                        self.reg.x = 0x03;
                        self.checkcode();
                        if !self.flags.z {
                            self.reg.a = 0x1b;
                            self.reg.x = 0x03;
                            self.checkcode();
                            if !self.flags.z {
                                break 'b12;
                            } else {
                                self.reg.a = 0x0a;
                                if self.reg.a == 0x00 {
                                    break 'b12;
                                }
                            }
                        } else {
                            self.reg.a = 0x00;
                        }
                        self.flags.c = false;
                        let _r = (self.reg.a as u16) + self.mem[sym::keypress] as u16 + (self.flags.c as u16);
                        self.reg.a = _r as u8;
                        self.flags.c = (_r >> 8) != 0;
                        self.flags.c = true;
                        let _r = (self.reg.a as u16) + (!0x30_u8) as u16 + (self.flags.c as u16);
                        self.reg.a = _r as u8;
                        self.flags.c = (_r >> 8) != 0;
                        let _o: u8 = 0x04;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a < 0x04 {
                            return;
                        }
                        let _o: u8 = 0x0d;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a >= 0x0d {
                            return;
                        }
                        self.mem[sym::NextLevel] = self.reg.a;
                        self.shortentime();
                        return;
                    }
                }
            }
        }
        self.reg.a = self.mem[sym::keypress];
        self.addkey();
        self.reg.a = 0x19;
        self.reg.x = 0x03;
        self.checkcode();
        if !self.flags.z {
            self.reg.a = 0x18;
            self.reg.x = 0x03;
            self.checkcode();
            if self.flags.z {
                self.reg.a = 0x03;
                self.reg.x = self.mem[sym::develment];
                if self.reg.x != 0x00 {
                    self.reg.a = 0x0b;
                }
                let _o: u8 = self.mem[sym::level];
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a >= self.mem[sym::level] {
                    self.mem[sym::NextLevel] = self.mem[sym::NextLevel].wrapping_add(1);
                    self.shortentime();
                }
            }
            self.LegitKeys();
            self.DevelKeys();
            self.TempDevel();
            return;
        }
        self.reg.a = 0x01;
        self.mem[sym::develment] = self.reg.a;
        self.gtone();
        return;
    }

    fn LegitKeys(&mut self) {
        self.reg.a = self.mem[sym::keypress];
        let _o: u8 = 0x9b;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0x9b {
            let _o: u8 = 0x12;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a != 0x12 {
                let _o: u8 = 0x01;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x01 {
                    self._3a1b();
                    return;
                }
                self.restart();
                return;
            }
            self.goattract();
            return;
        }
        self.freeze();
        return;
    }

    fn DevelKeys(&mut self) {
        self.reg.a = self.mem[sym::develment];
        if self.reg.a == 0x00 {
            return;
        }
        self.checkcodes();
        self.reg.a = self.mem[sym::keypress];
        if self.reg.a != 0x0d {
            return;
        }
        self.reg.a = 0x00;
        self.mem[sym::develment] = self.reg.a;
        return;
    }

    // aliases: ]sm
    fn postload(&mut self) {
        self.reg.a = 0xa9;
        self.mem[sym::BBundID] = self.reg.a;
        return;
    }

    fn preload(&mut self) {
        self.reg.a = self.mem[sym::BBundID];
        // raw: patch *]sm+1 = a            ; SPECIALK.S:555
        self.reg.a = 0xa9;
        self.mem[sym::BBundID] = self.reg.a;
        return;
    }

    fn addkey(&mut self) {
        self.reg.x = self.mem[sym::keybufptr];
        self.reg.x = self.reg.x.wrapping_add(1);
        if self.reg.x >= 0x0a {
            self.reg.x = 0x00;
        }
        self.mem[sym::keybufptr] = self.reg.x;
        self.mem[sym::keybuf + self.reg.x as usize] = self.reg.a;
        return;
    }

    fn checkcode(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.smc.smod_lo = self.reg.a;
                    self.smc.smod_hi = self.reg.x;
                    self.reg.x = self.mem[sym::keybufptr];
                    self.reg.y = 0x00;
                    pc = 1;
                }
                1 => {
                    pc = 2;
                }
                2 => {
                    self.reg.a = self.mem[((self.smc.smod_hi as usize) << 8 | (self.smc.smod_lo as usize)) + self.reg.y as usize];
                    if self.reg.a == 0x00 {
                        pc = 10;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    let _o: u8 = self.mem[sym::keybuf + self.reg.x as usize];
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a == self.mem[sym::keybuf + self.reg.x as usize] {
                        pc = 7;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    let _o: u8 = 0x41;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a < 0x41 {
                        pc = 9;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    let _o: u8 = 0x5b;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a >= 0x5b {
                        pc = 9;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    self.reg.a |= 0x20;
                    let _o: u8 = self.mem[sym::keybuf + self.reg.x as usize];
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != self.mem[sym::keybuf + self.reg.x as usize] {
                        pc = 9;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    self.reg.y = self.reg.y.wrapping_add(1);
                    self.reg.x = self.reg.x.wrapping_sub(1);
                    if (self.reg.x as i8) >= 0 {
                        pc = 1;
                    } else {
                        pc = 8;
                    }
                }
                8 => {
                    self.reg.x = 0x09;
                    if (self.reg.x as i8) >= 0 {
                        pc = 1;
                    } else {
                        pc = 9;
                    }
                }
                9 => {
                    self.reg.a = 0xff;
                    pc = 10;
                }
                10 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn KREAD(&mut self) {
        self.mem[sym::kbdX] = 0x00;
        self.mem[sym::kbdY] = 0x00;
        self.reg.a = self.mem[sym::keypress];
        if (self.reg.a as i8) >= 0 {
            self.reg.x = self.mem[sym::keydown];
            if (self.reg.x as i8) >= 0 {
                return;
            }
            self.reg.a |= 0x80;
        }
        'b6: {
            let _o: u8 = 0x6a;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a != 0x6a {
                let _o: u8 = 0x4a;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x4a {
                    'b10: {
                        let _o: u8 = 0x6c;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a != 0x6c {
                            let _o: u8 = 0x4c;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a != 0x4c {
                                break 'b10;
                            }
                        }
                        self.reg.a = 0x01;
                        if self.reg.a != 0x00 {
                            break 'b6;
                        }
                    }
                    'b13: {
                        let _o: u8 = 0x69;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a != 0x69 {
                            let _o: u8 = 0x49;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a != 0x49 {
                                'b17: {
                                    let _o: u8 = 0x6b;
                                    self.flags.c = self.reg.a >= _o;
                                    self.flags.z = self.reg.a == _o;
                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                    if self.reg.a != 0x6b {
                                        let _o: u8 = 0x4b;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a != 0x4b {
                                            break 'b17;
                                        }
                                    }
                                    self.reg.a = 0x01;
                                    if self.reg.a != 0x00 {
                                        break 'b13;
                                    }
                                }
                                'b20: {
                                    let _o: u8 = 0x75;
                                    self.flags.c = self.reg.a >= _o;
                                    self.flags.z = self.reg.a == _o;
                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                    if self.reg.a != 0x75 {
                                        let _o: u8 = 0x55;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a != 0x55 {
                                            break 'b20;
                                        }
                                    }
                                    self.reg.a = 0xff;
                                    self.mem[sym::kbdX] = self.reg.a;
                                    if !self.flags.z {
                                        break 'b13;
                                    }
                                }
                                'b23: {
                                    let _o: u8 = 0x6f;
                                    self.flags.c = self.reg.a >= _o;
                                    self.flags.z = self.reg.a == _o;
                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                    if self.reg.a != 0x6f {
                                        let _o: u8 = 0x4f;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a != 0x4f {
                                            break 'b23;
                                        }
                                    }
                                    self.reg.a = 0x01;
                                    self.mem[sym::kbdX] = self.reg.a;
                                    self.reg.a = 0xff;
                                    self.mem[sym::kbdY] = self.reg.a;
                                    if !self.flags.z {
                                        break 'b13;
                                    }
                                }
                                return;
                            }
                        }
                        self.reg.a = 0xff;
                    }
                    self.mem[sym::kbdY] = self.reg.a;
                    return;
                }
            }
            self.reg.a = 0xff;
        }
        self.mem[sym::kbdX] = self.reg.a;
        return;
    }

    fn FACEJSTK(&mut self) {
        self.reg.a = 0x00;
        self.flags.c = true;
        let _r = (self.reg.a as u16) + (!self.mem[sym::JSTKX]) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        self.mem[sym::JSTKX] = self.reg.a;
        self.reg.x = self.mem[sym::clrF];
        self.reg.a = self.mem[sym::clrB];
        self.mem[sym::clrF] = self.reg.a;
        self.mem[sym::clrB] = self.reg.x;
        return;
    }

    fn SAVESELECT(&mut self) {
        self.reg.x = 0x04;
        loop {
            self.reg.a = self.mem[sym::clrF + self.reg.x as usize];
            self.mem[sym::clrSEL + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn LOADSELECT(&mut self) {
        self.reg.x = 0x04;
        loop {
            self.reg.a = self.mem[sym::clrSEL + self.reg.x as usize];
            self.mem[sym::clrF + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn SAVEDESEL(&mut self) {
        self.reg.x = 0x04;
        loop {
            self.reg.a = self.mem[sym::clrF + self.reg.x as usize];
            self.mem[sym::clrDESEL + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn LOADDESEL(&mut self) {
        self.reg.x = 0x04;
        loop {
            self.reg.a = self.mem[sym::clrDESEL + self.reg.x as usize];
            self.mem[sym::clrF + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn INITINPUT(&mut self) {
        self.reg.a = 0x00;
        self.reg.x = 0x04;
        loop {
            self.mem[sym::clrDESEL + self.reg.x as usize] = self.reg.a;
            self.mem[sym::clrSEL + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn CLRJSTK(&mut self) {
        'b6: {
            self.reg.a = self.mem[sym::clrF];
            if (self.reg.a as i8) >= 0 {
                'b5: {
                    self.reg.x = self.mem[sym::JSTKX];
                    if (self.reg.x as i8) >= 0 {
                        self.reg.a = 0x00;
                        if self.reg.a == 0x00 {
                            break 'b5;
                        }
                    }
                    if self.reg.a != 0x00 {
                        break 'b6;
                    } else {
                        self.reg.a = 0xff;
                    }
                }
                self.mem[sym::clrF] = self.reg.a;
            }
        }
        'b12: {
            self.reg.a = self.mem[sym::clrB];
            if (self.reg.a as i8) >= 0 {
                'b11: {
                    self.reg.x = self.mem[sym::JSTKX];
                    if self.reg.x != 0x01 {
                        self.reg.a = 0x00;
                        if self.reg.a == 0x00 {
                            break 'b11;
                        }
                    }
                    if self.reg.a != 0x00 {
                        break 'b12;
                    } else {
                        self.reg.a = 0xff;
                    }
                }
                self.mem[sym::clrB] = self.reg.a;
            }
        }
        'b18: {
            self.reg.a = self.mem[sym::clrU];
            if (self.reg.a as i8) >= 0 {
                'b17: {
                    self.reg.x = self.mem[sym::JSTKY];
                    if (self.reg.x as i8) >= 0 {
                        self.reg.a = 0x00;
                        if self.reg.a == 0x00 {
                            break 'b17;
                        }
                    }
                    if self.reg.a != 0x00 {
                        break 'b18;
                    } else {
                        self.reg.a = 0xff;
                    }
                }
                self.mem[sym::clrU] = self.reg.a;
            }
        }
        'b24: {
            self.reg.a = self.mem[sym::clrD];
            if (self.reg.a as i8) >= 0 {
                'b23: {
                    self.reg.x = self.mem[sym::JSTKY];
                    if self.reg.x != 0x01 {
                        self.reg.a = 0x00;
                        if self.reg.a == 0x00 {
                            break 'b23;
                        }
                    }
                    if self.reg.a != 0x00 {
                        break 'b24;
                    } else {
                        self.reg.a = 0xff;
                    }
                }
                self.mem[sym::clrD] = self.reg.a;
            }
        }
        'b30: {
            self.reg.a = self.mem[sym::clrbtn];
            if (self.reg.a as i8) >= 0 {
                'b29: {
                    self.reg.x = self.mem[sym::btn];
                    if (self.reg.x as i8) >= 0 {
                        self.reg.a = 0x00;
                        if self.reg.a == 0x00 {
                            break 'b29;
                        }
                    }
                    if self.reg.a != 0x00 {
                        break 'b30;
                    } else {
                        self.reg.a = 0xff;
                    }
                }
                self.mem[sym::clrbtn] = self.reg.a;
            }
        }
        return;
    }

    fn ZEROSOUND(&mut self) {
        self.reg.a = 0x00;
        self.mem[sym::soundtable] = self.reg.a;
        return;
    }

    fn ADDSOUND(&mut self) {
        // raw: patch *]temp1 = x            ; SPECIALK.S:993
        self.reg.x = self.mem[sym::soundtable];
        let _o: u8 = 0x20;
        self.flags.c = self.reg.x >= _o;
        self.flags.z = self.reg.x == _o;
        self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
        if self.reg.x < 0x20 {
            self.reg.x = self.reg.x.wrapping_add(1);
            self.mem[sym::soundtable + self.reg.x as usize] = self.reg.a;
            self.mem[sym::soundtable] = self.reg.x;
        }
        // raw: ??? ldx ]temp1            ; SPECIALK.S:1003
        return;
    }

    fn DEMOKEYS(&mut self) {
        'b6: {
            self.reg.a = self.mem[sym::level];
            if self.reg.a == 0x00 {
                self.reg.a = self.mem[0xc061];
                self.reg.a |= self.mem[0xc062];
                if (self.reg.a as i8) >= 0 {
                    self.reg.a = self.mem[sym::keypress];
                    if (self.reg.a as i8) >= 0 {
                        break 'b6;
                    } else {
                        if self.reg.a == 0x9b {
                            break 'b6;
                        } else {
                            if self.reg.a == 0x13 {
                                break 'b6;
                            }
                        }
                    }
                }
                self.reg.a = 0xff;
                return;
            }
        }
        self.reg.a = 0x00;
        return;
    }

    fn LISTTORCHES(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.reg.a = 0x00;
                    self.mem[0x00f0] = self.reg.a;
                    self.reg.a = self.mem[sym::VisScrn];
                    self.calcblue();
                    self.reg.y = 0x1d;
                    pc = 1;
                }
                1 => {
                    self._3asub();
                    self.reg.x = self.mem[0x00f0];
                    let _o: u8 = 0x08;
                    self.flags.c = self.reg.x >= _o;
                    self.flags.z = self.reg.x == _o;
                    self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.x >= 0x08 {
                        pc = 4;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.reg.y = self.reg.y.wrapping_sub(1);
                    if (self.reg.y as i8) >= 0 {
                        pc = 1;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.reg.x = self.mem[0x00f0];
                    pc = 4;
                }
                4 => {
                    self.reg.a = 0xff;
                    self.mem[sym::torchx + self.reg.x as usize] = self.reg.a;
                    self.mem[sym::torchcount] = self.reg.a;
                    pc = 9;
                }
                5 => {
                    return;
                }
                6 => {
                    self.reg.a = self.mem[(self.mem[sym::BlueType] as usize | (self.mem[sym::BlueType + 1] as usize) << 8) + self.reg.y as usize];
                    self.reg.a &= 0x1f;
                    let _o: u8 = 0x13;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x13 {
                        pc = 9;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    self.reg.a = self.mem[sym::fredbuf + 1 + self.reg.y as usize];
                    self.mem[sym::BOTCUT] = self.reg.a;
                    self.reg.a = self.reg.y;
                    self.stack.push(self.reg.a);
                    self.unindex();
                    self.stack.push(self.reg.a);
                    self.reg.a = self.reg.x;
                    self.reg.x = self.mem[0x00f0];
                    self.reg.y = self.reg.a;
                    self.reg.a = self.mem[sym::BlockBot + 1 + self.reg.y as usize];
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x03_u8) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    self.mem[sym::torchy + self.reg.x as usize] = self.reg.a;
                    self.reg.a = self.mem[sym::BOTCUT];
                    self.mem[sym::torchclip + self.reg.x as usize] = self.reg.a;
                    self.reg.a = self.stack.pop().expect("pla on empty stack");
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.flags.c = false;
                    let _r = (self.reg.a as u16) + (0x01) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    let _o: u8 = 0x0a;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a >= 0x0a {
                        pc = 9;
                    } else {
                        pc = 8;
                    }
                }
                8 => {
                    self.flags.c = (self.reg.a >> 7) != 0;
                    self.reg.a = self.reg.a.wrapping_shl(1);
                    self.flags.c = (self.reg.a >> 7) != 0;
                    self.reg.a = self.reg.a.wrapping_shl(1);
                    self.mem[sym::torchx + self.reg.x as usize] = self.reg.a;
                    self.reg.a = self.stack.pop().expect("pla on empty stack");
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.y = self.reg.a;
                    self.reg.a = self.mem[(self.mem[sym::BlueSpec] as usize | (self.mem[sym::BlueSpec + 1] as usize) << 8) + self.reg.y as usize];
                    self.mem[sym::torchstate + self.reg.x as usize] = self.reg.a;
                    self.mem[0x00f0] = self.mem[0x00f0].wrapping_add(1);
                    pc = 9;
                }
                9 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn BURN(&mut self) {
        self.reg.a = self.mem[sym::torchx];
        if (self.reg.a as i8) < 0 {
            return;
        }
        self.reg.x = self.mem[sym::torchcount];
        self.reg.x = self.reg.x.wrapping_add(1);
        self.reg.a = self.mem[sym::torchx + self.reg.x as usize];
        if (self.reg.a as i8) < 0 {
            self.reg.x = 0x00;
        }
        self.mem[sym::torchcount] = self.reg.x;
        self.mem[sym::XCO] = self.mem[sym::torchx + self.reg.x as usize];
        self.mem[sym::YCO] = self.mem[sym::torchy + self.reg.x as usize];
        self.mem[sym::BOTCUT] = self.mem[sym::torchclip + self.reg.x as usize];
        self.reg.a = self.mem[sym::torchstate + self.reg.x as usize];
        self.getflameframe();
        self.mem[sym::torchstate + self.reg.x as usize] = self.reg.a;
        self.reg.x = self.reg.a;
        self.setupflame();
        self.reg.a = self.mem[sym::BOTCUT];
        if self.reg.a != 0x00 {
            self.initlay();
            self.mem[sym::OFFSET] = 0x00;
            self.reg.a = self.mem[sym::YCO];
            self.flags.c = true;
            let _r = (self.reg.a as u16) + (!0x04_u8) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
            self.mem[sym::BOTCUT] = self.reg.a;
            self.lay();
            return;
        }
        self.fastlay();
        return;
    }

    fn GETMINLEFT(&mut self) {
        self.mem[0x00f1] = 0x00;
        self.mem[0x00f2] = 0x00;
        self.reg.a = 0x42;
        self.smc.sm1 = self.reg.a;
        self.reg.a = 0x04;
        self.smc.sm2 = self.reg.a;
        self._3asub();
        self.mem[sym::MinLeft] = self.reg.y;
        let _o: u8 = 0x02;
        self.flags.c = self.reg.y >= _o;
        self.flags.z = self.reg.y == _o;
        self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
        if self.reg.y >= 0x02 {
            return;
        }
        self.mem[0x00f1] = 0x36;
        self.mem[0x00f2] = 0xfb;
        self.reg.a = 0x12;
        self.smc.sm1 = self.reg.a;
        self.reg.a = 0x00;
        self.smc.sm2 = self.reg.a;
        self._3asub();
        self.mem[sym::SecLeft] = self.reg.y;
        return;
    }

    fn KEEPTIME(&mut self) {
        self.reg.a = self.mem[sym::level];
        if self.reg.a == 0x00 {
            return;
        }
        self.reg.a = self.mem[sym::KidLife];
        if (self.reg.a as i8) >= 0 {
            return;
        }
        self.mem[sym::FrameCount] = self.mem[sym::FrameCount].wrapping_add(1);
        if self.flags.z {
            self.mem[sym::FrameCount + 1] = self.mem[sym::FrameCount + 1].wrapping_add(1);
        }
        if self.flags.z {
            self.reg.a = 0xff;
            self.mem[sym::FrameCount] = self.reg.a;
            self.mem[sym::FrameCount + 1] = self.reg.a;
        }
        self.reg.y = self.mem[sym::NextTimeMsg];
        // raw: ??? cpy #nummsg            ; SPECIALK.S:1283
        if self.flags.c {
            return;
        }
        self.reg.a = self.mem[sym::FrameCount + 1];
        let _o: u8 = self.mem[sym::timetable + 1 + self.reg.y as usize];
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a < self.mem[sym::timetable + 1 + self.reg.y as usize] {
            return;
        }
        self.reg.a = self.mem[sym::FrameCount];
        let _o: u8 = self.mem[sym::timetable + self.reg.y as usize];
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a < self.mem[sym::timetable + self.reg.y as usize] {
            return;
        }
        self.reg.a = self.mem[sym::msgtimer];
        if self.reg.a != 0x00 {
            return;
        }
        self.mem[sym::NextTimeMsg] = self.mem[sym::NextTimeMsg].wrapping_add(1);
        self.mem[sym::NextTimeMsg] = self.mem[sym::NextTimeMsg].wrapping_add(1);
        self.reg.a = 0x02;
        self.mem[sym::timerequest] = self.reg.a;
        return;
    }

    fn SHORTENTIME(&mut self) {
        self.reg.y = self.mem[sym::NextTimeMsg];
        if self.reg.y >= 0x14 {
            return;
        }
        self.reg.y = 0x12;
        self.mem[sym::NextTimeMsg] = self.reg.y;
        self.mem[sym::FrameCount] = self.mem[sym::timetable + self.reg.y as usize];
        self.reg.a = self.mem[sym::timetable + 1 + self.reg.y as usize];
        self.mem[sym::FrameCount + 1] = self.reg.a;
        return;
    }

    fn CUESONG(&mut self) {
        self.mem[sym::SongCue] = self.reg.a;
        self.mem[sym::SongCount] = self.reg.x;
        return;
    }

    // aliases: STROBE
    fn DLOOP(&mut self) {
        self.keys();
        self.controller();
        return;
    }

    fn TempDevel(&mut self) {
        self.reg.a = self.mem[sym::develment];
        if self.reg.a == 0x00 {
            return;
        }
        self.reg.a = self.mem[sym::keypress];
        let _o: u8 = 0x06;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0x06 {
            let _o: u8 = 0x42;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a != 0x42 {
                let _o: u8 = 0x11;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x11 {
                    let _o: u8 = 0x53;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x53 {
                        let _o: u8 = 0x46;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a != 0x46 {
                            let _o: u8 = 0x29;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a != 0x29 {
                                let _o: u8 = 0x2b;
                                self.flags.c = self.reg.a >= _o;
                                self.flags.z = self.reg.a == _o;
                                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                if self.reg.a != 0x2b {
                                    self.reg.a = self.mem[sym::keypress];
                                    let _o: u8 = 0x30;
                                    self.flags.c = self.reg.a >= _o;
                                    self.flags.z = self.reg.a == _o;
                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                    if self.reg.a >= 0x30 {
                                        let _o: u8 = 0x3a;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a < 0x3a {
                                            self.flags.c = true;
                                            let _r = (self.reg.a as u16) + (!0x30_u8) as u16 + (self.flags.c as u16);
                                            self.reg.a = _r as u8;
                                            self.flags.c = (_r >> 8) != 0;
                                            self.mem[sym::guardprog] = self.reg.a;
                                            self.gtone();
                                            return;
                                        }
                                    }
                                    let _o: u8 = 0x03;
                                    self.flags.c = self.reg.a >= _o;
                                    self.flags.z = self.reg.a == _o;
                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                    if self.reg.a != 0x03 {
                                        let _o: u8 = 0x5d;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a != 0x5d {
                                            let _o: u8 = 0x5b;
                                            self.flags.c = self.reg.a >= _o;
                                            self.flags.z = self.reg.a == _o;
                                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                            if self.reg.a != 0x5b {
                                                let _o: u8 = 0x40;
                                                self.flags.c = self.reg.a >= _o;
                                                self.flags.z = self.reg.a == _o;
                                                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                if self.reg.a != 0x40 {
                                                    let _o: u8 = 0x05;
                                                    self.flags.c = self.reg.a >= _o;
                                                    self.flags.z = self.reg.a == _o;
                                                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                    if self.reg.a != 0x05 {
                                                        let _o: u8 = 0x44;
                                                        self.flags.c = self.reg.a >= _o;
                                                        self.flags.z = self.reg.a == _o;
                                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                        if self.reg.a != 0x44 {
                                                            let _o: u8 = 0x41;
                                                            self.flags.c = self.reg.a >= _o;
                                                            self.flags.z = self.reg.a == _o;
                                                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                            if self.reg.a != 0x41 {
                                                                let _o: u8 = 0x10;
                                                                self.flags.c = self.reg.a >= _o;
                                                                self.flags.z = self.reg.a == _o;
                                                                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                                if self.reg.a != 0x10 {
                                                                    'b42: {
                                                                        let _o: u8 = 0x3c;
                                                                        self.flags.c = self.reg.a >= _o;
                                                                        self.flags.z = self.reg.a == _o;
                                                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                                        if self.reg.a != 0x3c {
                                                                            let _o: u8 = 0x3e;
                                                                            self.flags.c = self.reg.a >= _o;
                                                                            self.flags.z = self.reg.a == _o;
                                                                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                                            if self.reg.a == 0x3e {
                                                                                self.reg.a = 0x02;
                                                                                if self.reg.a != 0x00 {
                                                                                    break 'b42;
                                                                                }
                                                                            }
                                                                            let _o: u8 = 0x2a;
                                                                            self.flags.c = self.reg.a >= _o;
                                                                            self.flags.z = self.reg.a == _o;
                                                                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                                            if self.reg.a != 0x2a {
                                                                                let _o: u8 = 0x4d;
                                                                                self.flags.c = self.reg.a >= _o;
                                                                                self.flags.z = self.reg.a == _o;
                                                                                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                                                                if self.reg.a != 0x4d {
                                                                                    return;
                                                                                }
                                                                                self.reg.a = 0xff;
                                                                                self.mem[sym::FrameCount + 1] = self.reg.a;
                                                                                return;
                                                                            }
                                                                            self.reg.a = 0xff;
                                                                            self.mem[sym::SavLevel] = self.reg.a;
                                                                            self.DoSaveGame();
                                                                            return;
                                                                        }
                                                                        self.reg.a = 0xfe;
                                                                    }
                                                                    self.flags.c = false;
                                                                    let _r = (self.reg.a as u16) + self.mem[sym::FrameCount + 1] as u16 + (self.flags.c as u16);
                                                                    self.reg.a = _r as u8;
                                                                    self.flags.c = (_r >> 8) != 0;
                                                                    self.mem[sym::FrameCount + 1] = self.reg.a;
                                                                    return;
                                                                }
                                                                self.mem[sym::level] = 0x01;
                                                                self.reg.a = 0x02;
                                                                self.mem[sym::NextLevel] = self.reg.a;
                                                                return;
                                                            }
                                                            self.reg.a = self.mem[sym::ManCtrl];
                                                            self.reg.a ^= 0xff;
                                                            self.mem[sym::ManCtrl] = self.reg.a;
                                                            return;
                                                        }
                                                        self.mem[sym::ChgKidStr] = self.mem[sym::ChgKidStr].wrapping_sub(1);
                                                        return;
                                                    }
                                                    self.reg.a = self.mem[sym::KidY];
                                                    self.flags.c = true;
                                                    let _r = (self.reg.a as u16) + (!0x3f_u8) as u16 + (self.flags.c as u16);
                                                    self.reg.a = _r as u8;
                                                    self.flags.c = (_r >> 8) != 0;
                                                    self.mem[sym::KidY] = self.reg.a;
                                                    self.mem[sym::KidBlockY] = self.mem[sym::KidBlockY].wrapping_sub(1);
                                                    return;
                                                }
                                                self.reg.a = self.mem[sym::PAGE];
                                                self.screendump();
                                                return;
                                            }
                                            self.gtone();
                                            self.reg.a = self.mem[sym::SPEED];
                                            self.flags.c = false;
                                            let _r = (self.reg.a as u16) + (0x04) as u16 + (self.flags.c as u16);
                                            self.reg.a = _r as u8;
                                            self.flags.c = (_r >> 8) != 0;
                                            self.mem[sym::SPEED] = self.reg.a;
                                            return;
                                        }
                                        self.reg.a = self.mem[sym::SPEED];
                                        let _o: u8 = 0x05;
                                        self.flags.c = self.reg.a >= _o;
                                        self.flags.z = self.reg.a == _o;
                                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                                        if self.reg.a < 0x05 {
                                            self.reg.a = 0x01;
                                            self.mem[sym::SPEED] = self.reg.a;
                                            return;
                                        }
                                        self.flags.c = true;
                                        let _r = (self.reg.a as u16) + (!0x04_u8) as u16 + (self.flags.c as u16);
                                        self.reg.a = _r as u8;
                                        self.flags.c = (_r >> 8) != 0;
                                        self.mem[sym::SPEED] = self.reg.a;
                                        self.gtone();
                                        return;
                                    }
                                    self.preload();
                                    self.reg.a = 0x02;
                                    self.mem[sym::redrawflg] = self.reg.a;
                                    self.reload();
                                    self.postload();
                                    return;
                                }
                                self.reg.a = self.mem[sym::level];
                                self.flags.c = false;
                                let _r = (self.reg.a as u16) + (0x05) as u16 + (self.flags.c as u16);
                                self.reg.a = _r as u8;
                                self.flags.c = (_r >> 8) != 0;
                                self.mem[sym::NextLevel] = self.reg.a;
                                return;
                            }
                            self.mem[sym::NextLevel] = self.mem[sym::NextLevel].wrapping_add(1);
                            return;
                        }
                        self.boostmeter();
                        return;
                    }
                    self.mem[sym::ChgKidStr] = self.mem[sym::ChgKidStr].wrapping_add(1);
                    self.mem[sym::ChgOppStr] = self.mem[sym::ChgOppStr].wrapping_add(1);
                    return;
                }
                self.reg.a = 0x0a;
                self.mem[sym::AMtimer] = self.reg.a;
                return;
            }
            self.reg.a = self.mem[sym::blackflag];
            self.reg.a ^= 0xff;
            self.mem[sym::blackflag] = self.reg.a;
            return;
        }
        self.mem[sym::redrawflg] = 0x02;
        self.reg.a = 0x00;
        self.mem[sym::blackflag] = self.reg.a;
        return;
    }

    fn checkcodes(&mut self) {
        return;
    }

    fn _3asub(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.reg.y = 0x61;
                    pc = 1;
                }
                1 => {
                    self.reg.a = self.mem[0x00f2];
                    let _o: u8 = self.mem[sym::FrameCount + 1];
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a < self.mem[sym::FrameCount + 1] {
                        pc = 4;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    if !self.flags.z {
                        pc = 8;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.reg.a = self.mem[0x00f1];
                    let _o: u8 = self.mem[sym::FrameCount];
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a >= self.mem[sym::FrameCount] {
                        pc = 8;
                    } else {
                        pc = 4;
                    }
                }
                4 => {
                    self.reg.a = self.mem[0x00f1];
                    self.flags.c = false;
                    pc = 5;
                }
                5 => {
                    let _r = (self.reg.a as u16) + (0x42) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    self.mem[0x00f1] = self.reg.a;
                    self.reg.a = self.mem[0x00f2];
                    pc = 6;
                }
                6 => {
                    let _r = (self.reg.a as u16) + (0x04) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    self.mem[0x00f2] = self.reg.a;
                    self.flags.d = true;
                    self.reg.a = self.reg.y;
                    self.flags.c = true;
                    let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
                    self.reg.a = _r as u8;
                    self.flags.c = (_r >> 8) != 0;
                    self.flags.d = false;
                    self.reg.y = self.reg.a;
                    if (self.reg.y as i8) >= 0 {
                        pc = 1;
                    } else {
                        pc = 7;
                    }
                }
                7 => {
                    self.reg.y = 0x00;
                    pc = 8;
                }
                8 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }
}
