// @generated by pop_lifter — DO NOT EDIT.
//
// Pass 4: module + routine scaffolding with leaf-expression,
// control-flow, data-movement, carry-arithmetic, `(ptr),y` indirect,
// cmp/bit flag, 16-bit (`Wide16`), dispatch-fallback, stack, and SMC
// operand-patch lowering.
//
// State is decomposed into `Cpu { reg, flags, mem, stack, smc }`:
// registers `self.reg.{a,x,y}: u8`, flags `self.flags.{c,z,n,i,d}:
// bool`, memory `self.mem[addr]` (64 KiB), the `pha`/`pla` value
// stack `self.stack: Vec<u8>`, and recognised SMC operand variables
// `self.smc.<name>` (immediate) / `self.smc.<name>_lo`/`_hi`
// (address). RAM addresses keep their source symbol names via the
// `sym` constants below. Cross-module routine calls resolve once the
// modules are compiled together; opcode / branch-target SMC stays
// deferred as `// raw: …` comments.
//
// source: 01 POP Source/Source/SUBS.S

#[derive(Default)]
pub struct Regs { pub a: u8, pub x: u8, pub y: u8 }

// 6502 status flags, modelled as booleans (V is not tracked).
#[derive(Default)]
pub struct Flags { pub c: bool, pub z: bool, pub n: bool, pub i: bool, pub d: bool }

// Self-modifying-code operand variables: instruction operands the
// routine patches at runtime, recovered by pass-3 SMC recognition.
#[derive(Default)]
pub struct Smc {
    pub sm: u8,
}

pub struct Cpu {
    pub reg: Regs,
    pub flags: Flags,
    pub mem: Box<[u8; 0x10000]>,
    pub stack: Vec<u8>,
    pub smc: Smc,
    // Local-label / Merlin-variable byte store, keyed by symbolic
    // `(name, offset)`: StoreLocal writes, LoadLocal/CmpLocal read.
    pub local: std::collections::HashMap<(&'static str, u8), u8>,
}

impl Cpu {
    pub fn new() -> Self {
        Cpu {
            reg: Regs::default(),
            flags: Flags::default(),
            mem: Box::new([0u8; 0x10000]),
            stack: Vec::new(),
            smc: Smc::default(),
            local: std::collections::HashMap::new(),
        }
    }
}

#[allow(non_upper_case_globals)]
mod sym {
    pub const BlueSpec: usize = 0x0026;
    pub const BlueType: usize = 0x0024;
    pub const CharAction: usize = 0x0046;
    pub const CharBlockX: usize = 0x0044;
    pub const CharBlockY: usize = 0x0045;
    pub const CharFace: usize = 0x0043;
    pub const CharID: usize = 0x004d;
    pub const CharLife: usize = 0x004f;
    pub const CharPosn: usize = 0x0040;
    pub const CharScrn: usize = 0x004b;
    pub const CharSword: usize = 0x004e;
    pub const CharX: usize = 0x0041;
    pub const CharXVel: usize = 0x0047;
    pub const CharY: usize = 0x0042;
    pub const CharYVel: usize = 0x0048;
    pub const FCharIndex: usize = 0x0075;
    pub const FloorY: usize = 0x127e;
    pub const GdStartBlock: usize = 0xbf47;
    pub const GdStartSeqH: usize = 0xbfbf;
    pub const GdStartX: usize = 0xbf77;
    pub const GlassState: usize = 0x0213;
    pub const INFO: usize = 0xbf00;
    pub const KidLife: usize = 0x005f;
    pub const KidPosn: usize = 0x0050;
    pub const KidStartBlock: usize = 0xbf41;
    pub const KidStartFace: usize = 0xbf42;
    pub const KidStartScrn: usize = 0xbf40;
    pub const KidStrength: usize = 0x00ce;
    pub const MaxKidStr: usize = 0x00d0;
    pub const MinLeft: usize = 0x0300;
    pub const Mult10: usize = 0x1200;
    pub const OFFSET: usize = 0x0003;
    pub const PAGE: usize = 0x0000;
    pub const PlayCount: usize = 0x00a0;
    pub const PreRecPtr: usize = 0x0309;
    pub const SCRNUM: usize = 0x0023;
    pub const SPEED: usize = 0x030c;
    pub const SceneCount: usize = 0x0338;
    pub const SecLeft: usize = 0x0302;
    pub const ShadPosn: usize = 0x0060;
    pub const VisScrn: usize = 0x00cb;
    pub const XCO: usize = 0x0001;
    pub const YCO: usize = 0x0002;
    pub const clrbtn: usize = 0x00d8;
    pub const droppedout: usize = 0x00e7;
    pub const exitopen: usize = 0x0086;
    pub const height: usize = 0x0004;
    pub const invert: usize = 0x009f;
    pub const jarabove: usize = 0x00cd;
    pub const keypress: usize = 0x020f;
    pub const lastpotion: usize = 0x00e0;
    pub const level: usize = 0x03f4;
    pub const lightcolor: usize = 0x0089;
    pub const lightning: usize = 0x0088;
    pub const message: usize = 0x030b;
    pub const milestone: usize = 0x0212;
    pub const msgtimer: usize = 0x00db;
    pub const musicon: usize = 0x031a;
    pub const offguard: usize = 0x008a;
    pub const origstrength: usize = 0x00e1;
    pub const psandcount: usize = 0x0346;
    pub const pstarcount: usize = 0x0347;
    pub const ptorchcount: usize = 0x0345;
    pub const ptorchoff: usize = 0x0342;
    pub const ptorchstate: usize = 0x0344;
    pub const ptorchx: usize = 0x0341;
    pub const ptorchy: usize = 0x0343;
    pub const purpleflag: usize = 0x00da;
    pub const redrawglass: usize = 0x0214;
    pub const scrnAbove: usize = 0x0033;
    pub const scrnLeft: usize = 0x0031;
    pub const scrncolor: usize = 0x031d;
    pub const soundon: usize = 0x0203;
    pub const tempblockx: usize = 0x0091;
    pub const tempblocky: usize = 0x0092;
    pub const tempscrn: usize = 0x0093;
    pub const tempstate: usize = 0x00f2;
    pub const timebomb: usize = 0x007d;
    pub const timerequest: usize = 0x031f;
    pub const trloc: usize = 0xb600;
    pub const trscrn: usize = 0xb620;
    pub const vibes: usize = 0x0318;
    pub const waitingtojump: usize = 0x00a7;
    pub const weightless: usize = 0x00c5;
    pub const yellowflag: usize = 0x007c;
}

impl Cpu {
    fn CRUMBLE(&mut self) {
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        let _o: u8 = 0x0d;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0x0d {
        } else {
            self.reg.a = self.mem[sym::VisScrn];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            let _o: u8 = 0x17;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a == 0x17 {
                self.mem[sym::tempscrn] = self.mem[sym::scrnAbove];
                self.reg.a = 0x02;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.mem[sym::tempblocky] = self.reg.a;
                self.reg.x = 0x07;
                self.flags.z = self.reg.x == 0;
                self.flags.n = (self.reg.x >> 7) != 0;
                loop {
                    self.mem[sym::tempblockx] = self.reg.x;
                    self._3atrigloose();
                    self.reg.x = self.mem[sym::tempblockx];
                    self.flags.z = self.reg.x == 0;
                    self.flags.n = (self.reg.x >> 7) != 0;
                    let _v = self.reg.x.wrapping_sub(1);
                    self.reg.x = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    let _o: u8 = 0x02;
                    self.flags.c = self.reg.x >= _o;
                    self.flags.z = self.reg.x == _o;
                    self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
                    if !(self.reg.x >= 0x02) {
                        break;
                    }
                }
            } else {
                let _o: u8 = 0x10;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x10 {
                } else {
                    self.mem[sym::tempscrn] = self.mem[sym::scrnAbove];
                    self.reg.a = 0x02;
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.mem[sym::tempblocky] = self.reg.a;
                    self.reg.x = 0x07;
                    self.flags.z = self.reg.x == 0;
                    self.flags.n = (self.reg.x >> 7) != 0;
                    loop {
                        self.mem[sym::tempblockx] = self.reg.x;
                        self._3atrigloose();
                        self.reg.x = self.mem[sym::tempblockx];
                        self.flags.z = self.reg.x == 0;
                        self.flags.n = (self.reg.x >> 7) != 0;
                        let _v = self.reg.x.wrapping_sub(1);
                        self.reg.x = _v;
                        self.flags.z = _v == 0;
                        self.flags.n = (_v >> 7) != 0;
                        let _o: u8 = 0x02;
                        self.flags.c = self.reg.x >= _o;
                        self.flags.z = self.reg.x == _o;
                        self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
                        if !(self.reg.x >= 0x02) {
                            break;
                        }
                    }
                }
            }
        }
        return;
    }

    fn ADDTORCHES(&mut self) {
        self.reg.a = self.mem[sym::VisScrn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.calcblue();
        self.reg.y = 0x1d;
        self.flags.z = self.reg.y == 0;
        self.flags.n = (self.reg.y >> 7) != 0;
        loop {
            self.reg.a = self.mem[(self.mem[sym::BlueType] as usize | (self.mem[sym::BlueType + 1] as usize) << 8) + self.reg.y as usize];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.reg.a &= 0x1f;
            let _o: u8 = 0x13;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a != 0x13 {
                let _o: u8 = 0x0a;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x0a {
                    let _o: u8 = 0x16;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x16 {
                    } else {
                        self.reg.a = self.reg.y;
                        let tmp0 = self.reg.a;
                        self.reg.a = self.mem[sym::VisScrn];
                        self.flags.z = self.reg.a == 0;
                        self.flags.n = (self.reg.a >> 7) != 0;
                        self.trigsword();
                        self.reg.a = tmp0;
                        self.reg.y = self.reg.a;
                    }
                } else {
                    self.reg.a = self.reg.y;
                    let tmp2 = self.reg.a;
                    self.reg.a = self.mem[sym::VisScrn];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.trigflask();
                    self.reg.a = tmp2;
                    self.reg.y = self.reg.a;
                    if (self.reg.y as i8) >= 0 {
                    } else {
                        let _o: u8 = 0x16;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a != 0x16 {
                        } else {
                            self.reg.a = self.reg.y;
                            let tmp1 = self.reg.a;
                            self.reg.a = self.mem[sym::VisScrn];
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            self.trigsword();
                            self.reg.a = tmp1;
                            self.reg.y = self.reg.a;
                        }
                    }
                }
            } else {
                self.reg.a = self.reg.y;
                let tmp6 = self.reg.a;
                self.reg.a = self.mem[sym::VisScrn];
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.trigtorch();
                self.reg.a = tmp6;
                self.reg.y = self.reg.a;
                if (self.reg.y as i8) >= 0 {
                } else {
                    let _o: u8 = 0x0a;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x0a {
                        let _o: u8 = 0x16;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a != 0x16 {
                        } else {
                            self.reg.a = self.reg.y;
                            let tmp3 = self.reg.a;
                            self.reg.a = self.mem[sym::VisScrn];
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            self.trigsword();
                            self.reg.a = tmp3;
                            self.reg.y = self.reg.a;
                        }
                    } else {
                        self.reg.a = self.reg.y;
                        let tmp5 = self.reg.a;
                        self.reg.a = self.mem[sym::VisScrn];
                        self.flags.z = self.reg.a == 0;
                        self.flags.n = (self.reg.a >> 7) != 0;
                        self.trigflask();
                        self.reg.a = tmp5;
                        self.reg.y = self.reg.a;
                        if (self.reg.y as i8) >= 0 {
                        } else {
                            let _o: u8 = 0x16;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a != 0x16 {
                            } else {
                                self.reg.a = self.reg.y;
                                let tmp4 = self.reg.a;
                                self.reg.a = self.mem[sym::VisScrn];
                                self.flags.z = self.reg.a == 0;
                                self.flags.n = (self.reg.a >> 7) != 0;
                                self.trigsword();
                                self.reg.a = tmp4;
                                self.reg.y = self.reg.a;
                            }
                        }
                    }
                }
            }
            let _v = self.reg.y.wrapping_sub(1);
            self.reg.y = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if !((self.reg.y as i8) >= 0) {
                break;
            }
        }
        return;
    }

    // aliases: :outer
    fn PAUSE(&mut self) {
        self.stack.push(self.reg.a);
        self.reg.x = 0x00;
        for _ in 0..256usize {
            self.reg.x = self.reg.x.wrapping_sub(0x01);
        }
        self.reg.a = self.stack.pop().expect("pla on empty stack");
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.flags.c = true;
        let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        if self.reg.a != 0x00 {
            self.PAUSE();
            return;
        }
        return;
    }

    fn DOFLASHON(&mut self) {
        self.lrclse();
        self.vblank();
        self.reg.a = self.mem[0xc054];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.a = self.mem[0xc056];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        return;
    }

    fn DOFLASHOFF(&mut self) {
        self.vblank();
        self.reg.a = self.mem[sym::PAGE];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            self.reg.a = self.mem[0xc055];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        }
        self.reg.a = self.mem[0xc057];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        return;
    }

    fn LRCLSE(&mut self) {
        if self.reg.a == self.mem[sym::scrncolor] {
            return;
        }
        self.lrcls();
        return;
    }

    fn ADDSLICERS(&mut self) {
        self.mem[sym::tempstate] = 0x0f;
        self.reg.a = self.mem[sym::CharScrn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.calcblue();
        self.reg.y = self.mem[sym::CharBlockY];
        self.flags.z = self.reg.y == 0;
        self.flags.n = (self.reg.y >> 7) != 0;
        let _o: u8 = 0x03;
        self.flags.c = self.reg.y >= _o;
        self.flags.z = self.reg.y == _o;
        self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
        if self.reg.y >= 0x03 {
        } else {
            self.reg.a = self.mem[sym::Mult10 + self.reg.y as usize];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.reg.y = self.reg.a;
            self.flags.c = false;
            let _r = (self.reg.a as u16) + (0x0a) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
            self.smc.sm = self.reg.a;
            loop {
                self.reg.a = self.mem[(self.mem[sym::BlueType] as usize | (self.mem[sym::BlueType + 1] as usize) << 8) + self.reg.y as usize];
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.reg.a &= 0x1f;
                let _o: u8 = 0x12;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != 0x12 {
                } else {
                    self.reg.a = self.mem[(self.mem[sym::BlueSpec] as usize | (self.mem[sym::BlueSpec + 1] as usize) << 8) + self.reg.y as usize];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.x = self.reg.a;
                    self.reg.a &= 0x7f;
                    if self.reg.a == 0x00 {
                        self.reg.a = self.reg.x;
                        self.reg.a &= 0x80;
                        self.reg.a |= self.mem[sym::tempstate];
                        self.trigslicer();
                        self.getnextstate();
                    } else {
                        let _o: u8 = 0x06;
                        self.flags.c = self.reg.a >= _o;
                        self.flags.z = self.reg.a == _o;
                        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.a < 0x06 {
                        } else {
                            self.reg.a = self.reg.x;
                            self.reg.a &= 0x80;
                            self.reg.a |= self.mem[sym::tempstate];
                            self.trigslicer();
                            self.getnextstate();
                        }
                    }
                }
                let _v = self.reg.y.wrapping_add(1);
                self.reg.y = _v;
                self.flags.z = _v == 0;
                self.flags.n = (_v >> 7) != 0;
                let _o: u8 = self.smc.sm;
                self.flags.c = self.reg.y >= _o;
                self.flags.z = self.reg.y == _o;
                self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                if !(self.reg.y < self.smc.sm) {
                    break;
                }
            }
        }
        return;
    }

    fn getnextstate(&mut self) {
        self.reg.a = self.mem[sym::tempstate];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.flags.c = true;
        let _r = (self.reg.a as u16) + (!0x03_u8) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        if self.reg.a < 0x06 {
            self.flags.c = false;
            let _r = (self.reg.a as u16) + (0x0a) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
        }
        self.mem[sym::tempstate] = self.reg.a;
        return;
    }

    fn pburn(&mut self) {
        self.reg.x = self.mem[sym::ptorchcount];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        let _v = self.reg.x.wrapping_add(1);
        self.reg.x = _v;
        self.flags.z = _v == 0;
        self.flags.n = (_v >> 7) != 0;
        self.reg.a = self.mem[sym::ptorchx + self.reg.x as usize];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if (self.reg.a as i8) < 0 {
            self.reg.x = 0x00;
            self.flags.z = self.reg.x == 0;
            self.flags.n = (self.reg.x >> 7) != 0;
        }
        self.mem[sym::ptorchcount] = self.reg.x;
        self.mem[sym::XCO] = self.mem[sym::ptorchx + self.reg.x as usize];
        self.mem[sym::OFFSET] = self.mem[sym::ptorchoff + self.reg.x as usize];
        self.mem[sym::YCO] = self.mem[sym::ptorchy + self.reg.x as usize];
        self.reg.a = self.mem[sym::ptorchstate + self.reg.x as usize];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.getflameframe();
        self.mem[sym::ptorchstate + self.reg.x as usize] = self.reg.a;
        self.reg.x = self.reg.a;
        self.psetupflame();
        self.lay();
        return;
    }

    fn pflow(&mut self) {
        self.reg.x = self.mem[sym::psandcount];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        if (self.reg.x as i8) < 0 {
            return;
        }
        let _v = self.reg.x.wrapping_add(1);
        self.reg.x = _v;
        self.flags.z = _v == 0;
        self.flags.n = (_v >> 7) != 0;
        if self.reg.x >= 0x03 {
            self.reg.x = 0x00;
            self.flags.z = self.reg.x == 0;
            self.flags.n = (self.reg.x >> 7) != 0;
        }
        self.mem[sym::psandcount] = self.reg.x;
        self.reg.y = self.mem[sym::GlassState];
        self.flags.z = self.reg.y == 0;
        self.flags.n = (self.reg.y >> 7) != 0;
        self.flow();
        return;
    }

    fn pstars(&mut self) {
        self.reg.x = 0x03;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        loop {
            self.reg.a = self.mem[sym::pstarcount + self.reg.x as usize];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            if self.reg.a == 0x00 {
            } else {
                let _v = self.mem[sym::pstarcount + self.reg.x as usize].wrapping_sub(1);
                self.mem[sym::pstarcount + self.reg.x as usize] = _v;
                self.flags.z = _v == 0;
                self.flags.n = (_v >> 7) != 0;
                if !self.flags.z {
                } else {
                    self.reg.a = self.reg.x;
                    let tmp0 = self.reg.a;
                    self.twinkle();
                    self.reg.a = tmp0;
                    self.reg.x = self.reg.a;
                }
            }
            let _v = self.reg.x.wrapping_sub(1);
            self.reg.x = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        self.rnd();
        let _o: u8 = 0x0a;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a >= 0x0a {
            return;
        }
        self.rnd();
        self.reg.a &= 0x03;
        self.flags.c = false;
        let _r = (self.reg.a as u16) + (0x05) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        let tmp1 = self.reg.a;
        self.rnd();
        self.rnd();
        self.reg.a &= 0x03;
        self.reg.x = self.reg.a;
        self.reg.a = tmp1;
        self.mem[sym::pstarcount + self.reg.x as usize] = self.reg.a;
        self.twinkle();
        return;
    }

    fn PAGEFLIP(&mut self) {
        self.normspeed();
        self.reg.a = self.mem[sym::PAGE];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.mem[sym::PAGE] = 0x00;
            self.reg.a = self.mem[0xc055];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        } else {
            self.mem[sym::PAGE] = 0x20;
            self.reg.a = self.mem[0xc054];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        }
        self.reg.a = self.mem[0xc057];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.a = self.mem[0xc050];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.a = self.mem[sym::vibes];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            self.reg.a = self.mem[0xc05f];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            return;
        }
        self.reg.a = self.mem[0xc05e];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        return;
    }

    fn PLAYCUT(&mut self) {
        let tmp0 = self.reg.a;
        self.initit();
        self.reg.a = tmp0;
        self.reg.x = self.reg.a;
        self.PlayCut4();
        return;
    }

    fn PlayCut8(&mut self) {
        self.getglass();
        self.addglass();
        self.startP8();
        self.SaveShad();
        self.startM8();
        self.SaveKid();
        self.reg.a = 0x14;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x6b;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x14;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x6f;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x14;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.mem[sym::KidPosn] = 0x00;
        self.reg.x = 0x32;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = 0x10;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySongX();
        return;
    }

    fn PlayCut4(&mut self) {
        self.getglass();
        self.addglass();
        self.startP4();
        self.SaveShad();
        self.startM4();
        self.SaveKid();
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x70;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x09;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x72;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x3a;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        return;
    }

    fn PlayCut7(&mut self) {
        self.mem[sym::SPEED] = 0x08;
        self.mem[sym::soundon] = 0x01;
        self.mem[sym::musicon] = 0x01;
        self.startP7();
        self.SaveShad();
        self.reg.a = 0x08;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.startK7();
        self.SaveKid();
        self.reg.a = 0x08;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x6c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x0d;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.mem[sym::KidPosn] = 0x00;
        self.reg.a = 0x09;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x0f;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySong();
        self.startM7();
        self.SaveKid();
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x65;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x1e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        return;
    }

    fn PlayCut6(&mut self) {
        self.mem[sym::SPEED] = 0x16;
        self.reg.x = 0x08;  // empty hourglass
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.addglass();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x0e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySong();
        self.reg.a = 0x64;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        return;
    }

    fn PlayCut5(&mut self) {
        self.getglass();
        if self.reg.x >= 0x07 {
            self.Ominous();
            return;
        }
        self.PlayCut1();
        return;
    }

    fn Ominous(&mut self) {
        self.getglass();
        self.addglass();
        self.startP5();
        self.SaveShad();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x32;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = 0x10;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySongX();
        self.reg.a = 0x62;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x14;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = 0x03;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySongX();
        return;
    }

    fn PlayCut2(&mut self) {
        self.getglass();
        self.addglass();
        self.startP2();
        self.SaveShad();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x32;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = 0x10;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySongX();
        return;
    }

    // aliases: PlayCut3
    fn PlayCut1(&mut self) {
        self.getglass();
        self.addglass();
        self.startP1();
        self.SaveShad();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x32;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = 0x0d;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.PlaySongX();
        return;
    }

    fn PlayCut0(&mut self) {
        self.startV0();
        self.SaveKid();
        self.startP0();
        self.SaveShad();
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x07;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x08;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x62;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x09;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x08;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x00;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        self.mem[sym::SPEED] = 0x07;
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x60;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x06;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x61;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x04;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x09;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x0c;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        self.reg.a = 0x04;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x60;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x1e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x61;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x04;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x0a;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x19;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        self.reg.a = 0x66;  // raises arms
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x01;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x63;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x0d;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x00;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.addglass1();
        self.mem[sym::lightning] = 0x05;
        self.mem[sym::lightcolor] = 0xff;
        self.mem[sym::SPEED] = 0x0c;
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.mem[sym::psandcount] = 0x00;
        self.reg.a = 0x0b;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x08;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        self.mem[sym::SPEED] = 0x07;
        self.reg.a = 0x64;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.kjumpseq();
        self.reg.a = 0x11;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.x = 0x01;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.addglass1();
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.reg.a = 0x71;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pjumpseq();
        self.reg.a = 0x1c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.play();
        self.mem[sym::SPEED] = 0x0c;
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x14;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.PlaySongI();
        return;
    }

    fn addglass(&mut self) {
        self.mem[sym::psandcount] = 0x00;
        self.mem[sym::GlassState] = self.reg.x;
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::redrawglass] = self.reg.a;
        return;
    }

    fn addglass1(&mut self) {
        self.mem[sym::GlassState] = self.reg.x;
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::redrawglass] = self.reg.a;
        return;
    }

    fn PlaySongX(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.reg.y = self.reg.a;
                    self.reg.a = self.mem[sym::soundon];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.a &= self.mem[sym::musicon];
                    if self.reg.a != 0x00 {
                        pc = 2;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.reg.a = self.reg.x;
                    self.play();
                    return;
                }
                2 => {
                    self.reg.a = self.reg.y;
                    pc = 3;
                }
                3 => {
                    self.minit();
                    self.swpage();
                    pc = 4;
                }
                4 => {
                    self.reg.a = 0x01;
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.strobe();
                    self.reg.a = self.mem[0xc061];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.a |= self.mem[0xc062];
                    self.reg.a |= self.mem[sym::keypress];
                    if (self.reg.a as i8) < 0 {
                        pc = 6;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.pburn();
                    self.pstars();
                    self.pflow();
                    self.mplay();
                    let _o: u8 = 0x00;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x00 {
                        pc = 4;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    self.swpage();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn PlaySong(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.minit();
                    self.swpage();
                    pc = 1;
                }
                1 => {
                    self.reg.a = 0x01;
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.strobe();
                    self.reg.a = self.mem[0xc061];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.a |= self.mem[0xc062];
                    self.reg.a |= self.mem[sym::keypress];
                    if (self.reg.a as i8) < 0 {
                        pc = 3;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.pburn();
                    self.pstars();
                    self.pflow();
                    self.mplay();
                    let _o: u8 = 0x00;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x00 {
                        pc = 1;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.swpage();
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn PlaySongI(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.reg.y = self.reg.a;
                    self.reg.a = self.mem[sym::soundon];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.a &= self.mem[sym::musicon];
                    if self.reg.a != 0x00 {
                        pc = 3;
                    } else {
                        pc = 1;
                    }
                }
                1 => {
                    self.reg.a = self.reg.x;
                    if self.reg.a == 0x00 {
                        pc = 8;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.play();
                    return;
                }
                3 => {
                    self.reg.a = self.reg.y;
                    self.minit();
                    self.swpage();
                    pc = 4;
                }
                4 => {
                    self.musickeys();
                    let _o: u8 = 0x80;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a >= 0x80 {
                        pc = 7;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.pburn();
                    self.pstars();
                    self.pflow();
                    self.mplay();
                    let _o: u8 = 0x00;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x00 {
                        pc = 4;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    self.swpage();
                    return;
                }
                7 => {
                    self.dostartgame();
                    return;
                }
                8 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn swpage(&mut self) {
        self.reg.a = self.mem[sym::PAGE];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.a ^= 0x20;
        self.mem[sym::PAGE] = self.reg.a;
        return;
    }

    fn flashon(&mut self) {
        self.reg.a = self.mem[sym::lightning];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            return;
        }
        self.reg.a = self.mem[sym::lightcolor];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.doflashon();
        return;
    }

    fn flashoff(&mut self) {
        self.reg.a = self.mem[sym::lightning];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            return;
        }
        let _v = self.mem[sym::lightning].wrapping_sub(1);
        self.mem[sym::lightning] = _v;
        self.flags.z = _v == 0;
        self.flags.n = (_v >> 7) != 0;
        self.doflashoff();
        return;
    }

    fn play(&mut self) {
        let mut pc: u32 = 0;
        loop {
            match pc {
                0 => {
                    self.mem[sym::SceneCount] = self.reg.a;
                    pc = 1;
                }
                1 => {
                    self.rnd();
                    self.reg.a = self.mem[sym::SPEED];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.pause();
                    self.strobe();
                    self.reg.a = self.mem[sym::level];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    if self.reg.a != 0x00 {
                        pc = 4;
                    } else {
                        pc = 2;
                    }
                }
                2 => {
                    self.demokeys();
                    if !self.flags.n {
                        pc = 5;
                    } else {
                        pc = 3;
                    }
                }
                3 => {
                    self.reg.a = 0x01;
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.dostartgame();
                    return;
                }
                4 => {
                    self.reg.a = self.mem[0xc061];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.reg.a |= self.mem[0xc062];
                    self.reg.a |= self.mem[sym::keypress];
                    if (self.reg.a as i8) < 0 {
                        pc = 9;
                    } else {
                        pc = 5;
                    }
                }
                5 => {
                    self.NextFrame();
                    self.flashon();
                    self.FrameAdv();
                    self.flashoff();
                    self.reg.a = self.mem[sym::soundon];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    if self.reg.a == 0x00 {
                        pc = 7;
                    } else {
                        pc = 6;
                    }
                }
                6 => {
                    self.playback();
                    self.zerosound();
                    pc = 7;
                }
                7 => {
                    let _v = self.mem[sym::SceneCount].wrapping_sub(1);
                    self.mem[sym::SceneCount] = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if !self.flags.z {
                        pc = 1;
                    } else {
                        pc = 8;
                    }
                }
                8 => {
                    return;
                }
                9 => {
                    return;
                }
                _ => unreachable!(),
            }
        }
    }

    fn playloop(&mut self) {
        self.rnd();
        self.reg.a = self.mem[sym::SPEED];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.pause();
        self.strobe();
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.reg.a = self.mem[0xc061];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.reg.a |= self.mem[0xc062];
            self.reg.a |= self.mem[sym::keypress];
            if (self.reg.a as i8) < 0 {
                return;
            }
        } else {
            self.demokeys();
            if self.flags.n {
                self.reg.a = 0x01;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.dostartgame();
                return;
            }
        }
        self.NextFrame();
        self.flashon();
        self.FrameAdv();
        self.flashoff();
        self.reg.a = self.mem[sym::soundon];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.playback();
            self.zerosound();
        }
        let _v = self.mem[sym::SceneCount].wrapping_sub(1);
        self.mem[sym::SceneCount] = _v;
        self.flags.z = _v == 0;
        self.flags.n = (_v >> 7) != 0;
        if !self.flags.z {
            self.playloop();
            return;
        }
        return;
    }

    fn NextFrame(&mut self) {
        self.DoKid();
        self.DoShad();
        return;
    }

    fn FrameAdv(&mut self) {
        self.DoFast();
        self.vblank();
        self.PageFlip();
        return;
    }

    fn DoKid(&mut self) {
        self.LoadKid();
        self.reg.a = self.mem[sym::CharPosn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            return;
        }
        self.ctrlkidchar();
        self.animchar();
        self.SaveKid();
        return;
    }

    fn DoShad(&mut self) {
        self.LoadShadwOp();
        self.reg.a = self.mem[sym::CharPosn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            return;
        }
        self.ctrlshadchar();
        self.animchar();
        self.SaveShad();
        return;
    }

    fn ctrlkidchar(&mut self) {
        return;
    }

    fn ctrlshadchar(&mut self) {
        return;
    }

    fn DoFast(&mut self) {
        self.zerolsts();
        self.reg.a = self.mem[sym::redrawglass];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            let _v = self.mem[sym::redrawglass].wrapping_sub(1);
            self.mem[sym::redrawglass] = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            self.reg.x = self.mem[sym::GlassState];
            self.flags.z = self.reg.x == 0;
            self.flags.n = (self.reg.x >> 7) != 0;
            self.drawglass();
        }
        self.LoadKid();
        self.reg.a = self.mem[sym::CharPosn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.setupchar();
            self.reg.a = 0x1e;
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.mem[sym::FCharIndex] = self.reg.a;
            self.addkidobj();
        }
        self.LoadShad();
        self.reg.a = self.mem[sym::CharPosn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.setupchar();
            self.reg.a = 0x1e;
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.mem[sym::FCharIndex] = self.reg.a;
            self.addkidobj();
            self.pmask();
        }
        self.fast();
        self.drawpost();
        self.pburn();
        self.pburn();
        self.pstars();
        self.drawall();
        self.pflow();
        return;
    }

    fn pjumpseq(&mut self) {
        let tmp0 = self.reg.a;
        self.LoadShad();
        self.reg.a = tmp0;
        self.jumpseq();
        self.SaveShad();
        return;
    }

    // aliases: mjumpseq, vjumpseq
    fn kjumpseq(&mut self) {
        let tmp0 = self.reg.a;
        self.LoadKid();
        self.reg.a = tmp0;
        self.jumpseq();
        self.SaveKid();
        return;
    }

    fn startM8(&mut self) {
        self.startM4();
        self.mem[sym::CharX] = 0x90;
        self.reg.a = 0x6a;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startM4(&mut self) {
        self.mem[sym::CharID] = 0x18;
        self.mem[sym::CharX] = 0xc7;
        self.mem[sym::CharY] = 0x98;
        self.mem[sym::CharFace] = 0xff;
        self.reg.a = 0x69;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startP8(&mut self) {
        self.startP0();
        self.mem[sym::CharX] = 0x82;
        self.mem[sym::CharY] = 0x9a;
        self.reg.a = 0x6e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startP4(&mut self) {
        self.startP1();
        self.mem[sym::CharX] = 0x8e;
        self.mem[sym::CharY] = 0x9a;
        self.reg.a = 0x5e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startP5(&mut self) {
        self.startP0();
        self.reg.a = 0xa0;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::CharX] = self.reg.a;
        return;
    }

    fn startP2(&mut self) {
        self.startP0();
        self.mem[sym::CharX] = 0x59;
        self.mem[sym::CharY] = 0x97;
        self.reg.a = 0x67;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startP1(&mut self) {
        self.startP0();
        self.reg.a = 0x00;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::CharFace] = self.reg.a;
        return;
    }

    fn startP7(&mut self) {
        self.startP0();
        self.mem[sym::CharX] = 0x88;
        self.mem[sym::CharY] = 0x95;
        self.reg.a = 0x6d;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x01;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        if self.reg.x != self.mem[sym::purpleflag] {
            self.reg.a = 0x78;  // crash (copy protect)
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        }
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startM7(&mut self) {
        self.startM4();
        self.reg.a = 0x95;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::CharY] = self.reg.a;
        return;
    }

    fn startP0(&mut self) {
        self.mem[sym::CharID] = 0x05;
        self.mem[sym::CharX] = 0x78;
        self.mem[sym::CharY] = 0x97;
        self.mem[sym::CharFace] = 0xff;
        self.reg.a = 0x5e;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startV0(&mut self) {
        self.mem[sym::CharID] = 0x06;
        self.mem[sym::CharX] = 0xc5;
        self.mem[sym::CharY] = 0x97;
        self.mem[sym::CharFace] = 0xff;
        self.reg.a = 0x5f;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn startK7(&mut self) {
        self.mem[sym::CharID] = 0x00;
        self.mem[sym::CharX] = 0xc6;
        self.mem[sym::CharY] = 0x95;
        self.mem[sym::CharFace] = 0xff;
        self.reg.a = 0x01;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.animchar();
        return;
    }

    fn DEMO(&mut self) {
        self.reg.a = 0x79;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x03;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.AutoPlayback();
        return;
    }

    fn initit(&mut self) {
        self.mem[sym::scrncolor] = 0x20;
        self.reg.a = 0x00;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::vibes] = self.reg.a;
        self.mem[sym::redrawglass] = self.reg.a;
        self.mem[sym::KidPosn] = self.reg.a;
        self.mem[sym::ShadPosn] = self.reg.a;
        self.mem[sym::ptorchcount] = self.reg.a;
        self.reg.x = 0x03;
        loop {
            self.mem[sym::pstarcount + self.reg.x as usize] = self.reg.a;
            self.reg.x = self.reg.x.wrapping_sub(0x01);
            if !((self.reg.x as i8) >= 0) {
                break;
            }
        }
        self.mem[sym::psandcount] = 0xff;
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::SPEED] = self.reg.a;
        self.zeropeels();
        self.zerored();
        self.zerosound();
        return;
    }

    fn getglass(&mut self) {
        self.getminleft();
        self.reg.x = 0x07;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.reg.a = self.mem[sym::MinLeft];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a >= 0x06 {
            let _v = self.reg.x.wrapping_sub(1);
            self.reg.x = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if self.reg.a >= 0x11 {
                let _v = self.reg.x.wrapping_sub(1);
                self.reg.x = _v;
                self.flags.z = _v == 0;
                self.flags.n = (_v >> 7) != 0;
                if self.reg.a >= 0x21 {
                    let _v = self.reg.x.wrapping_sub(1);
                    self.reg.x = _v;
                    self.flags.z = _v == 0;
                    self.flags.n = (_v >> 7) != 0;
                    if self.reg.a >= 0x41 {
                        let _v = self.reg.x.wrapping_sub(1);
                        self.reg.x = _v;
                        self.flags.z = _v == 0;
                        self.flags.n = (_v >> 7) != 0;
                    }
                }
            }
        }
        return;
    }

    fn SHOWTIME(&mut self) {
        self.reg.a = self.mem[sym::timerequest];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x00 {
            return;
        }
        self.reg.a = self.mem[sym::KidLife];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if (self.reg.a as i8) >= 0 {
            return;
        }
        'b7: {
            self.getminleft();
            self.reg.a = self.mem[sym::MinLeft];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            let _o: u8 = 0x02;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a < 0x02 {
                self.reg.a = self.mem[sym::SecLeft];
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                if self.reg.a != 0x00 {
                    self.reg.a = self.mem[sym::level];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    let _o: u8 = 0x0e;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a >= 0x0e {
                        break 'b7;
                    } else {
                        if !self.flags.c {
                            self.reg.a = self.mem[sym::SecLeft];
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            let _o: u8 = 0x02;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a < 0x02 {
                                self.reg.a = 0x00;
                                self.flags.z = self.reg.a == 0;
                                self.flags.n = (self.reg.a >> 7) != 0;
                                self.mem[sym::timerequest] = self.reg.a;
                                self.mem[sym::msgtimer] = self.reg.a;
                                return;
                            }
                            self.reg.a = self.mem[sym::message];
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            let _o: u8 = 0x03;
                            self.flags.c = self.reg.a >= _o;
                            self.flags.z = self.reg.a == _o;
                            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                            if self.reg.a != 0x03 {
                                self.reg.a = self.mem[sym::msgtimer];
                                self.flags.z = self.reg.a == 0;
                                self.flags.n = (self.reg.a >> 7) != 0;
                                if self.reg.a != 0x00 {
                                    return;
                                }
                                self.reg.a = 0x03;
                                self.flags.z = self.reg.a == 0;
                                self.flags.n = (self.reg.a >> 7) != 0;
                                self.mem[sym::message] = self.reg.a;
                            }
                            self.reg.a = 0x01;
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            self.mem[sym::timerequest] = self.reg.a;
                            self.reg.a = 0x01;
                            self.flags.z = self.reg.a == 0;
                            self.flags.n = (self.reg.a >> 7) != 0;
                            self.mem[sym::msgtimer] = self.reg.a;
                            return;
                        }
                    }
                }
                self.reg.a = self.mem[sym::timerequest];
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                let _o: u8 = 0x03;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a < 0x03 {
                    return;
                }
            }
        }
        self.reg.a = self.mem[sym::msgtimer];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            return;
        }
        self.mem[sym::message] = 0x03;
        self.reg.a = 0x14;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = self.mem[sym::timerequest];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        let _o: u8 = 0x04;
        self.flags.c = self.reg.x >= _o;
        self.flags.z = self.reg.x == _o;
        self.flags.n = (self.reg.x.wrapping_sub(_o) >> 7) != 0;
        if self.reg.x >= 0x04 {
            self.reg.a = 0x19;  // delay 5 cycles
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        }
        self.mem[sym::msgtimer] = self.reg.a;
        self.reg.a = 0x00;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::timerequest] = self.reg.a;
        return;
    }

    fn ADDLOWERSOUND(&mut self) {
        self.flags.c = (self.reg.a & 1) != 0;
        self.reg.a = self.reg.a.wrapping_shr(1);
        if !self.flags.c {
            return;
        }
        'b12: {
            self.reg.a = self.mem[sym::level];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            let _o: u8 = 0x03;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a == 0x03 {
                self.reg.a = self.mem[sym::trscrn];
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                let _o: u8 = 0x02;
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a == 0x02 {
                    break 'b12;
                }
            }
            self.reg.a = self.mem[sym::trscrn];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            let _o: u8 = self.mem[sym::scrnLeft];
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a != self.mem[sym::scrnLeft] {
                let _o: u8 = self.mem[sym::VisScrn];
                self.flags.c = self.reg.a >= _o;
                self.flags.z = self.reg.a == _o;
                self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                if self.reg.a != self.mem[sym::VisScrn] {
                    return;
                }
                self.reg.y = self.mem[sym::trloc];
                self.flags.z = self.reg.y == 0;
                self.flags.n = (self.reg.y >> 7) != 0;
                let _o: u8 = 0x09;
                self.flags.c = self.reg.y >= _o;
                self.flags.z = self.reg.y == _o;
                self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                if self.reg.y == 0x09 {
                    return;
                }
                let _o: u8 = 0x13;
                self.flags.c = self.reg.y >= _o;
                self.flags.z = self.reg.y == _o;
                self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                if self.reg.y == 0x13 {
                    return;
                }
                let _o: u8 = 0x1d;
                self.flags.c = self.reg.y >= _o;
                self.flags.z = self.reg.y == _o;
                self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                if self.reg.y == 0x1d {
                    return;
                }
            } else {
                self.reg.y = self.mem[sym::trloc];
                self.flags.z = self.reg.y == 0;
                self.flags.n = (self.reg.y >> 7) != 0;
                let _o: u8 = 0x09;
                self.flags.c = self.reg.y >= _o;
                self.flags.z = self.reg.y == _o;
                self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                if self.reg.y != 0x09 {
                    let _o: u8 = 0x13;
                    self.flags.c = self.reg.y >= _o;
                    self.flags.z = self.reg.y == _o;
                    self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.y != 0x13 {
                        let _o: u8 = 0x1d;
                        self.flags.c = self.reg.y >= _o;
                        self.flags.z = self.reg.y == _o;
                        self.flags.n = (self.reg.y.wrapping_sub(_o) >> 7) != 0;
                        if self.reg.y != 0x1d {
                            return;
                        }
                    }
                }
            }
        }
        self.reg.a = 0x0c;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.addsound();
        return;
    }

    fn REMOVEOBJ(&mut self) {
        self.mem[sym::lastpotion] = self.reg.a;
        self.reg.x = 0x01;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.mem[sym::clrbtn] = self.reg.x;
        self.mem[(self.mem[sym::BlueType] as usize | (self.mem[sym::BlueType + 1] as usize) << 8) + self.reg.y as usize] = 0x01;
        self.mem[(self.mem[sym::BlueSpec] as usize | (self.mem[sym::BlueSpec + 1] as usize) << 8) + self.reg.y as usize] = 0x00;
        self.mem[sym::height] = 0x23;
        self.reg.a = 0x02;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.markwipe();
        self.markred();
        return;
    }

    fn SETINITIALS(&mut self) {
        self.reg.a = self.mem[sym::INFO];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.flags.c = true;
        let _r = (self.reg.a as u16) + (!0x01_u8) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        self.mem[sym::SCRNUM] = self.reg.a;
        loop {
            self.DoScrn();
            let _v = self.mem[sym::SCRNUM].wrapping_sub(1);
            self.mem[sym::SCRNUM] = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if self.flags.z {
                break;
            }
        }
        return;
    }

    fn DoScrn(&mut self) {
        self.reg.a = self.mem[sym::SCRNUM];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.calcblue();
        self.reg.y = 0x1d;
        self.flags.z = self.reg.y == 0;
        self.flags.n = (self.reg.y >> 7) != 0;
        loop {
            self.getinitobj();
            if !self.flags.c {
            } else {
                self.mem[(self.mem[sym::BlueSpec] as usize | (self.mem[sym::BlueSpec + 1] as usize) << 8) + self.reg.y as usize] = self.reg.a;
            }
            let _v = self.reg.y.wrapping_sub(1);
            self.reg.y = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if !((self.reg.y as i8) >= 0) {
                break;
            }
        }
        return;
    }

    fn STARTKID(&mut self) {
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x03 {
            self.reg.a = self.mem[sym::milestone];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            if self.reg.a != 0x00 {
                self.mem[sym::KidStartFace] = 0xff;
                self.mem[sym::KidStartScrn] = 0x02;
                self.mem[sym::KidStartBlock] = 0x06;
                self.reg.a = 0x07;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.reg.x = 0x04;
                self.flags.z = self.reg.x == 0;
                self.flags.n = (self.reg.x >> 7) != 0;
                self.reg.y = 0x00;
                self.flags.z = self.reg.y == 0;
                self.flags.n = (self.reg.y >> 7) != 0;
                self.rdblock();
                self.reg.a = 0x00;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.mem[(self.mem[sym::BlueType] as usize | (self.mem[sym::BlueType + 1] as usize) << 8) + self.reg.y as usize] = self.reg.a;
            }
        }
        self.mem[sym::CharScrn] = self.mem[sym::KidStartScrn];
        self.reg.a = self.mem[sym::KidStartBlock];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.unindex();
        self.mem[sym::CharBlockX] = self.reg.a;
        self.mem[sym::CharBlockY] = self.reg.x;
        self.reg.a = self.mem[sym::CharBlockX];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.getblockej();
        self.flags.c = false;
        let _r = (self.reg.a as u16) + (0x0e) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        self.mem[sym::CharX] = self.reg.a;
        self.reg.a = self.mem[sym::KidStartFace];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.a ^= 0xff;
        self.mem[sym::CharFace] = self.reg.a;
        self.reg.a = self.mem[sym::origstrength];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = self.mem[sym::level];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        if self.reg.x == 0x00 {
            self.reg.a = 0x04;
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
        }
        self.mem[sym::MaxKidStr] = self.reg.a;
        self.mem[sym::KidStrength] = self.reg.a;
        self.reg.a = 0x05;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.jumpseq();
        self.reg.x = self.mem[sym::CharBlockY];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.mem[sym::CharY] = self.mem[sym::FloorY + 1 + self.reg.x as usize];
        self.mem[sym::CharLife] = 0xff;
        self.mem[sym::CharID] = 0x00;
        self.reg.a = 0x00;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::CharXVel] = self.reg.a;
        self.mem[sym::CharYVel] = self.reg.a;
        self.mem[sym::waitingtojump] = self.reg.a;
        self.mem[sym::weightless] = self.reg.a;
        self.mem[sym::invert] = self.reg.a;
        self.mem[sym::jarabove] = self.reg.a;
        self.mem[sym::droppedout] = self.reg.a;
        self.mem[sym::CharSword] = self.reg.a;
        self.mem[sym::offguard] = self.reg.a;
        self.animchar();
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x07 {
            self.SaveKid();
            return;
        }
        self.reg.a = self.mem[sym::yellowflag];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if (self.reg.a as i8) >= 0 {
            self.reg.a = 0x40;
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.mem[sym::timebomb] = self.reg.a;
        }
        self.reg.a = self.mem[sym::CharScrn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x11 {
            self.SaveKid();
            return;
        }
        self.reg.a = 0x03;  // down
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.cut();
        self.SaveKid();
        return;
    }

    fn STARTKID1(&mut self) {
        self.reg.x = self.mem[sym::CharBlockY];
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.mem[sym::CharY] = self.mem[sym::FloorY + 1 + self.reg.x as usize];
        self.mem[sym::CharLife] = 0xff;
        self.mem[sym::CharID] = 0x00;
        self.reg.a = 0x00;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.mem[sym::CharXVel] = self.reg.a;
        self.mem[sym::CharYVel] = self.reg.a;
        self.mem[sym::waitingtojump] = self.reg.a;
        self.mem[sym::weightless] = self.reg.a;
        self.mem[sym::invert] = self.reg.a;
        self.mem[sym::jarabove] = self.reg.a;
        self.mem[sym::droppedout] = self.reg.a;
        self.mem[sym::CharSword] = self.reg.a;
        self.mem[sym::offguard] = self.reg.a;
        self.animchar();
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x07 {
            self.SaveKid();
            return;
        }
        self.reg.a = self.mem[sym::yellowflag];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if (self.reg.a as i8) >= 0 {
            self.reg.a = 0x40;
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.mem[sym::timebomb] = self.reg.a;
        }
        self.reg.a = self.mem[sym::CharScrn];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x11 {
            self.SaveKid();
            return;
        }
        self.reg.a = 0x03;  // down
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.cut();
        self.SaveKid();
        return;
    }

    fn GRAVITY(&mut self) {
        self.reg.a = self.mem[sym::CharAction];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        let _o: u8 = 0x04;
        self.flags.c = self.reg.a >= _o;
        self.flags.z = self.reg.a == _o;
        self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
        if self.reg.a != 0x04 {
            return;
        }
        self.reg.a = self.mem[sym::weightless];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x00 {
            self.reg.a = self.mem[sym::CharYVel];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.flags.c = false;
            let _r = (self.reg.a as u16) + (0x01) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
            let _o: u8 = 0x04;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a >= 0x04 {
                self.reg.a = 0x04;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                if !self.flags.c {
                    self.mem[sym::CharY] = (self.mem[sym::CharYVel]).wrapping_add(self.mem[sym::CharY]);
                    self.reg.a = self.mem[sym::CharAction];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    let _o: u8 = 0x04;
                    self.flags.c = self.reg.a >= _o;
                    self.flags.z = self.reg.a == _o;
                    self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
                    if self.reg.a != 0x04 {
                        return;
                    }
                    self.reg.a = self.mem[sym::CharXVel];
                    self.flags.z = self.reg.a == 0;
                    self.flags.n = (self.reg.a >> 7) != 0;
                    self.addcharx();
                    self.mem[sym::CharX] = self.reg.a;
                    self.rereadblocks();
                    return;
                }
            }
        } else {
            self.reg.a = self.mem[sym::CharYVel];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            self.flags.c = false;
            let _r = (self.reg.a as u16) + (0x03) as u16 + (self.flags.c as u16);
            self.reg.a = _r as u8;
            self.flags.c = (_r >> 8) != 0;
            let _o: u8 = 0x21;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a >= 0x21 {
                self.reg.a = 0x21;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
            }
        }
        self.mem[sym::CharYVel] = self.reg.a;
        return;
    }

    fn ADDFALL(&mut self) {
        self.reg.a = self.mem[sym::CharYVel];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.flags.c = false;
        let _r = (self.reg.a as u16) + self.mem[sym::CharY] as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        self.mem[sym::CharY] = self.reg.a;
        self.reg.a = self.mem[sym::CharAction];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a != 0x04 {
            return;
        }
        self.reg.a = self.mem[sym::CharXVel];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.addcharx();
        self.mem[sym::CharX] = self.reg.a;
        self.rereadblocks();
        return;
    }

    fn INITIALGUARDS(&mut self) {
        self.reg.y = 0x18;  // screen #
        self.flags.z = self.reg.y == 0;
        self.flags.n = (self.reg.y >> 7) != 0;
        loop {
            self.reg.a = self.mem[sym::GdStartBlock - 1 + self.reg.y as usize];
            self.flags.z = self.reg.a == 0;
            self.flags.n = (self.reg.a >> 7) != 0;
            let _o: u8 = 0x1e;
            self.flags.c = self.reg.a >= _o;
            self.flags.z = self.reg.a == _o;
            self.flags.n = (self.reg.a.wrapping_sub(_o) >> 7) != 0;
            if self.reg.a >= 0x1e {
            } else {
                self.unindex();
                self.getblockej();
                self.flags.c = false;
                let _r = (self.reg.a as u16) + (0x0e) as u16 + (self.flags.c as u16);
                self.reg.a = _r as u8;
                self.flags.c = (_r >> 8) != 0;
                self.mem[sym::GdStartX - 1 + self.reg.y as usize] = self.reg.a;
                self.reg.a = 0x00;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.mem[sym::GdStartSeqH - 1 + self.reg.y as usize] = self.reg.a;
            }
            let _v = self.reg.y.wrapping_sub(1);
            self.reg.y = _v;
            self.flags.z = _v == 0;
            self.flags.n = (_v >> 7) != 0;
            if !(self.reg.y != 0x00) {
                break;
            }
        }
        return;
    }

    fn DEADENEMY(&mut self) {
        self.reg.a = self.mem[sym::level];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        match self.reg.a {
            0x00 => {
                self.mem[sym::milestone] = 0x01;
                self.reg.a = 0x00;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.mem[sym::PreRecPtr] = self.reg.a;
                self.mem[sym::PlayCount] = self.reg.a;
                return;
            }
            0x0d => {
                self.reg.a = 0x09;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.reg.x = 0x19;
                self.flags.z = self.reg.x == 0;
                self.flags.n = (self.reg.x >> 7) != 0;
                self.cuesong();
                self.mem[sym::lightcolor] = 0xff;
                self.mem[sym::lightning] = 0x0a;
                self.mem[sym::exitopen] = 0x01;
                self.mem[sym::timerequest] = 0x04;
                self.reg.a = 0x18;
                self.flags.z = self.reg.a == 0;
                self.flags.n = (self.reg.a >> 7) != 0;
                self.reg.x = 0x00;
                self.flags.z = self.reg.x == 0;
                self.flags.n = (self.reg.x >> 7) != 0;
                self.reg.y = 0x00;
                self.flags.z = self.reg.y == 0;
                self.flags.n = (self.reg.y >> 7) != 0;
                self.rdblock();
                self.pushpp();
                return;
            }
            _ => {}
        }
        self.reg.a = self.mem[sym::CharID];
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        if self.reg.a == 0x01 {
            return;
        }
        self.reg.a = 0x07;
        self.flags.z = self.reg.a == 0;
        self.flags.n = (self.reg.a >> 7) != 0;
        self.reg.x = 0x19;
        self.flags.z = self.reg.x == 0;
        self.flags.n = (self.reg.x >> 7) != 0;
        self.cuesong();
        return;
    }

    fn _3atrigloose(&mut self) {
        self.rdblock1();
        if self.reg.a != 0x0b {
            return;
        }
        self.rnd();
        self.reg.a &= 0x0f;
        self.reg.a ^= 0xff;
        self.flags.c = false;
        let _r = (self.reg.a as u16) + (0x01) as u16 + (self.flags.c as u16);
        self.reg.a = _r as u8;
        self.flags.c = (_r >> 8) != 0;
        self.breakloose1();
        return;
    }
}
